= 2. 贵重的灵魂

你看过穿着漂亮婚纱的人体模型吗？你和娃娃或人体模型有什么不同呢？它也是用物质造成的，不是和你的模样差不多吗？你说没有生命？对！可是他里面为什么没有生命或灵魂呢？生命是从哪儿来的呢？生命体为什么非得从生命 体中出来呢？生命体为什么要生老病死呢？死后又会怎么样呢？

模仿人造出来的机器就是电脑。其中作为输入设备的键盘相当于人的感觉器 官，显示器相当于人的口，模仿人的大脑造出来的主机具有记忆功能、思考功能、比较判断功能。以后科学家们还要开发出人工智能电脑、巨容电脑。从某 种角度来看，虽然机器人或电脑具有比人更超越的能力。但是，人比那些机械更要尊贵的理由何在呢？

娃娃、人体模型、电脑、机器人等，不过是物质造出来的东西而已。模样或 技能方面也许比人好一些、超级一些，但里面没有“心”，没有心灵的世界，没有灵魂的世界。可人却有珍贵的灵魂世界、深深的心灵世界、奥妙的内心世 界。

你看过给雏燕叨食物的燕子吗？你看过因为忘不掉别离的牛犊而哭叫，甚至 不吃草的牛吗？看过能找回自己的家，又能听懂人语的动物吗？你看过紧紧跟着珍惜自己的主人、而回避折磨自己之人的狗吗？

牲畜也有知觉、感情和意志。就象你里头有肉体和心里本能的欲望一样，牲 畜里头也是这本能的欲望在起着作用。这么说，人和牲畜有什么不同呢？根椐一位人类学家在高等学校的教科书上所阐明的，区别人与动物的原始特征：是 人的直立行走与使用火，更高层次的特征是人使用了语言(HomoLoquens)与能思考的理性存在(HomoSapiens)。所以使人象个人，又称人为万物之灵长，是 因为有语言与理性的存在。但这一切不能说是本质方面的，只不过是技能方面而已。

在人类当中也有不如牲畜有知觉的人，也有很多语言表达能力与牲畜没有两 样的人。还有许多虽然超越了知觉，但做出来的事情却连牲畜都不如的人。那么，弱智儿与高智能的牲畜相比，哪一个是更尊贵的存在呢？对主人忠诚又伶 俐的狗与弱智的自己子女相比，你会觉得狗更尊贵吗？发动了战争、杀害众多的人民、惨害尊亲、近亲乱轮、同性恋、恐怖活动、拐卖人口等等残暴无情的 事，并毫不犹豫地做出无耻下流之事的人和温顺的牲畜相比，哪一个更尊贵呢？发动战争、牺牲众人性命的日本天皇或希特勒与为了人类而筋断骨折地事奉，劳苦一生，最后甚至把自己的肉体提供给人类的牛相比，哪一个是尊贵的 存在呢？你和牲畜在本质上有什么不同呢？

动物也有魂的世界。魂里有知、情、意。但是，动物因为只有肉体和魂，所 以不明白灵里的世界，没有灵里的欲望。

因为人有在动物身上查找不到的灵，才寻找属灵的存在，既渴慕又敬畏，并 且有通过属灵的经验要享受灵里满足的心。

TIP: “凡活物的生命和人类的气息都在他手中。”(伯12：10)

人都想寻找永远的世界、永远的幸福，获得永远的生命。永远的生命、幸福 和永远的处所在永远的国度里。圣经称那个国度为天国。当你发现那个国度的时候，你就会得到真正的安息、真正的盼望。人就算得到物质和肉身欲望的满 足，也不能享受既完全又满足的幸福之原因是，他没有得到灵(魂)里欲望的满足。

人比万物贵重，称为万物之灵长的原因，在于他是属灵的存在。当人们得到 灵里的满足时，就会感到真正的满足。即使肉体很健康，享用丰盛的物质生活，但如果灵魂枯干、灵魂疲倦、灵魂生病、灵魂陷入在污秽可恶的罪恶当 中；如果灵魂被死亡的惧怕和对生活的不安、痛苦、绝望与疑心充满着，那么，他的生活不就在痛苦、混沌、黑暗当中吗？这一点不言自明。物质文明在 不断发展，对于物质生活方面，我们过得比过去任何一个时代都要丰盛。即使这样，也不能证明这是幸福和心里的满足。虽然拥有得多、学得多；虽然充满 了物质的需求，人们的心却更空虚、混沌，生活无意义、孤独，深深地沉浸在缺乏感当中。我们的生活变得越来越不安、刻薄、枯燥，灵魂的问题仍然停 留在原点。

人与牲畜的不同，在于人追求灵魂的幸福，不断地探索灵魂的安身之处。离 开创造主(耶38：16)绝对得不到灵魂的安息。所以众人都在寻找“上帝”，寻找“天堂”。因此，每个人、每个民族都有宗教。从广义来说，无神论者也是 一种信心，一种信仰。
看过狗进行祭祀的场面吗？看过猪在岩石下祈祷吗？看过牛求天地神名、鸡行巫术、熊祈祷吗？
因为动物没有灵，对灵里的世界也没有关心，感觉上也没有灵里的苦恼与满 足。牲畜没有灵里的欲望、属灵的经验、属灵的眼睛。牲畜不会为了“我是谁？”“我为什么要在这里？”“我从哪儿来？往哪儿去？”“我为什么要这么 活着？”的问题而苦恼。若牲畜苦恼，那也只不过是因为食欲、性欲、睡眠欲等肉体的欲望没有得到满足而已。
肉体想吃、想睡、想休息享受，是因为有发动那样欲望的肉体。如果没有肉 体，我们的身上也不会有这些欲望产生。肉体有欲望的需求产生，是因为有发动欲望的肉体存在。

一方面，人还有魂，即精神的欲望。如果不存在这颗心，也不会有知、情、 意的需求，也不会产生追求良善等等心里的需求。因为有心里的世界，才有心里的需求。有了心(魂)，才有心愿，才有心里的喜乐，才有心里的痛苦。

那么，为什么会产生灵里的欲望呢？因为人里面有灵，人是属灵的存在。所 以惟独人在寻求神，敬畏绝对者；惟独人在祭祀、礼拜、行巫术、拜偶像。这就表明了人单有肉体和魂的欲望是得不到满足的。添满了灵里的欲望才能得到 真正的满足和安息。灵里的欲望得不到满足，人在任何一个地方也得不到真正的满足、幸福、自由、安息和盼望。你没有感到灵魂的干渴、灵魂的饥荒吗？

TIP: “日子将到，我必命饥荒降在地上。人饥饿非因无饼，干渴非因无水，乃因 不听耶和华的话。他们必飘流，从这海到那海，从北边到东边，往来奔跑寻求耶和华的话，却寻不着。当那日，美貌的处女和少年的男子必因干渴发昏。” (摩8：11～13)

不论哪一个民族、哪一个时代、哪一个地区都提出了关于自我存在的根本问 题。都想知道自己存在的原因，以及生活的目的和意义；都想知道自己的未来和生活的结局。所以算卦、看手相、相面、看风水，想分明地预测一下自己的 将来，好让自己有个准备。学习、赚钱、买房子、上保险、存款、沙龙聚会、设计晚年蓝图……但是，圣经已经给你的未来算了很重要的一卦：

TIP: “按着定命，人人都有一死，死后且有审判。”(来9：27)

这一卦准能命中你的身世。这是你应该深思熟虑的、有关你将来的问题。不 管你对自己是怎样想的，死亡已经向你宣告了，死刑已经确定了。有一位人类学家说，人与动物的差别在于人修造坟墓，动物却不知道自己会死，只是按着 本能活着，又那么死去。但是，人却知道自己要老，还要死，并且还想知道死后会有什么。因为他知道自己必定要走向死亡那边世界的严肃事实。有些人 说：“死了就结束了。”若是有感知的人，他至少会想到，死亡是一个肉体生活的结束，而不是灵魂生活的结束。虽然按着定命，人人都有一死，但你若是不 以此为结束，就要注目一下“死后……”这段神的话语。

关于死亡那边世界的答案，是在神所命定作为审判活人死人之主的耶稣基督 那里(徒10：42)；关于你灵魂的一切秘密和疑问，公开在创造一切灵魂之神的话语里。专心去寻找神的人，他必能藉着圣灵的启示得知这一切。

手表坏了的时候，拿着那块手表去生产厂家，是肯定能修好的；你的肉体病 了，应该去医院；你的灵魂病了且濒临死亡时，应该去什么地方呢？应该归到造你灵魂的神那里去，接受神的话语。神的话语是医治我们的灵魂，使我们的 灵魂复生的神奇之药。你不想倾听创造万物、主管万物的全能者的话语吗？

人。你相信你自己只是单纯的物质结晶体，只是单纯原子的精巧组织体吗？ 你不是无生物体膨胀的精巧结晶体。虽然你的肉体创造得非常神秘、奥妙、精巧的，但其内的灵魂更可贵、更精密。真不知心里的世界有多深、有多宽、有 多复杂。我们的心可升高也可降低，可宽阔也可狭隘，可受伤又可愈合；可疏远又可接近，可关闭又可打开，可火热又可冷淡，可柔和又可刚硬，可烦闷又 可畅快。心确实奇怪。有时被撕裂，有时受疼痛，有时在颤抖，有时又被压制。心有时也会生病，有时也会死去。
如同有肉身的眼睛一样，也有心灵的眼睛；有可以用肉身的耳朵听到的，也 有可以用心灵的耳朵听到的。我们看起来是一个光滑的表面，但若用高倍显微镜来看，那却是凹凸不平的。用我们的肉眼所看不到太阳光的颜色，通过三棱 镜就可以看到七种颜色。声音也是如此，有很多声波我们的耳朵不能听到。

用我们的耳朵、眼睛感觉到的，用我们的想法理解到的世界并不是一切。为 了正确地认识一下你自己，需要一个正确的尺。那尺就是创造你和创造大千世界的神的话语。神把你很想知道的事情，以及你必须要明白的真理，都启示在有他的话语里——圣经。

圣经里启示了这个物质世界存在之前的世界。那个世界是灵的世界。圣经里 分明地显明了创造这个世界和人类的动机、过程以及目的。不但如此，还详细地预言了这个世界将来的结局，启示了关于结束这个世界后要接续的永远世界 的秘密。比任何一件事都重要的是，从圣经中可以明白神向我们灵魂所发的那深深的爱，启示着可以拯救你灵魂的福音。你不想得到全能神的无限恩典和怜 恤，不想得到没有任何条件的神的爱吗？

宇宙中只有一次的你的生命，只有一次的你的人生！你若遇不到基督，那珍 贵的生命和你的人生也只能是虚空的了。但因为你是可以进到耶稣基督里的人，又是可以作神儿女的人，所以你才是一个可贵的存在。

神在深深地关心着你的灵魂，他真的是在爱着你。不但如此，他还迫切地期 待你来认识他、爱他。请你真挚地、谦虚地来倾听一下他的话语。如果你敞开心门对待他的话语，你必会遇见他。在他的恩典和爱里，你的灵魂会得到真正 的安歇；你的灵魂会从罪和死亡当中被拯救出来；会得到永远的生命和活泼的盼望；你会看到想象之外的新的世界。

