= 3. 生与死，之后...

人是由尘土造的肉体和神吹进的灵魂合成的存在。人活着是指灵魂居住在肉 体里的状态而言的。肉体在不继地成长、老化，在不断地变化着。你的肉体也是以60兆～100兆的细胞构成的。其中每天有2%(1兆2千亿～2兆)的细胞在 体内重新生成。那些老化的细胞被分解排除到体外。就这样，因为新陈代谢的作用，你的身体从体内的血液开始，到肌肉以及140亿的脑蛋白为止，不过 120天就更换一新了。虽然是这样，但我们的意识还有记忆，仍然存在着，灵魂的世界依旧。虽然肉身是在不断地变化着，自我意识却依然如故。这一点你 不觉得奇怪吗？只要对这样的事情稍微考虑衣，就会清楚地认识到不断变化的肉体，不是我们真正形象的事实。
人体中约有65%是水分。把构成肉体的成份通过化学分析，就可以明白与圣经里的证据是一样的，果然是由尘土般的物质构成的。以体重70公斤的人为标准，构成人体的物质相当于7块肥皂的脂肪，可以刷一间房子的石灰，相 当于13公斤焦炭的碳素，2200根火柴的磷；相当于2·5厘米长的铁钉，一汤匙的硫磺，含量为30克的金属。把这些当作矿物质讲，价值也只不过是5美 元。

若是论物质，没有灵魂的我们的肉体，还不到一斤牛肉的价值，更不到一条 狗、一头猪的价值，仅仅相当于一只鸡的价值。那么说，人为什么还是那么尊贵的存在呢？不用说，是因为有灵魂。

TIP: “眼泪”用肉眼看只不过是一滴水。把“眼泪”再仔细地进行化学分析，就 会知道有水分、少量的盐，以及微量的无机物。但是，这也不是眼泪的全部，一滴泪中还有非常大的悲哀、喜乐、感激、惊愕溶解在内。虽是一滴泪，也关 乎着灵魂的世界，关乎着心里的状态。这灵魂才是你真正的形象。肉体的出生、成长、老化、生病、损伤，甚至还出现残疾。即使这样，你也不能成为别 人，那是因为你的灵魂没有改变。若说肉体贵重的原因，是因为一时作了一个灵魂的住处。神说：“没有灵魂的身体是死的。”(雅2：26)

神说我们的身体是“地上的帐棚”(林后5：1)。我们的灵魂在这用尘土造成 的帐棚里度过一生，最后，还要搬到永远的家、永远的世界。这就是死亡。地上的帐棚，即我们的肉身被拆毁，并不是一切的结束；如果肉身被拆毁了，我 们的灵魂就要归到永远的住处了。那地方就是圣经所讲的天国和地狱。“死亡” 并不是肉体和灵魂的“消灭”，乃是指肉体和灵魂的“分离”。灵魂离开肉体的 状态就是死亡。因为人生的始与终，即出生与死亡之间有“时间”在间隔着的缘故，人们才不能深刻地认识到生活的总体和结局而活着。但是，若除掉那个 “时间”，我们肉体的最后形象就只能变成尘土了。那么灵魂会怎么样呢？
你也必定要有脱下这肉身的衣服留在这地上，去迎接那灵魂越过死亡之河的 日子。到那日，你的灵魂就会归到创造你灵魂的神那里去了。

TIP: “尘土归于地，灵仍归于赐灵的神。”(传12：7)

无论什么时候，只要脱掉肉身，你的灵魂就要站在神的宝座前。就象从长 长的睡梦中醒来一样，你会在神的宝座前遇见神的。神为了让人明白人生就象一场梦，死亡就象从睡梦中醒来一样的事实，才允许了“梦”这种神秘的经历。
“人死了”和生物学上所说的细胞100%的消灭是不同的。“死亡”意味着灵 魂离开“土房”(肉体)(伯4：19)，到永远的世界去。有趣的是，对于“死亡”的说法有很多种。“故去了”、“去世了”、“他界了”。“故去了”是指着“归到原来的地方去了。”意思是说，“死亡”意味着“归回”。因为肉体是出于土，仍要归于土；灵魂是从神来的，也要归于神。死又 称“去世”。灵魂离别肉体、离别这个世界后，去了特别的世界。神称那特别的世界为天国和地狱。死又称“他界了”，即到其他世界的意思。

也许到目前为止你轻视了永远的世界。但是，你们的灵魂却分明地愿意知道那永远的世界，敬畏那永有者。现在你应该对你的灵魂、你的死亡以及永远的世界持着真挚的关心。
或许你轻视神的话语，便说：“喂！你说，死了就结束了，哪还有什么天国 地狱的。你去看过呀？那都是等到死后才明白的事。”当然，死后会明白的。但是，神己经在圣经中敞开了那个世界的门，以至于让你在临死之前明白死亡 那边的世界。

请你想一想，即使是接到一位真挚朋友的来信，难道你也不相信其中的内容 吗？看了新闻报道也不相信那些内容吗？圣经记者不会记载虚谎的奇事的。他们是照着听到的最真实之神口里所说出来的话语，接着原样记录下来的。难道 你非要到了非洲才能相信非洲大陆的存在吗？没有去过美丽的港口，就不能相信美丽港口的存在吗？没死就不能相信死亡向你走来的事实吗？没有入狱或出 狱的经历，就简直不能相信监狱的存在吗？因为现在没有一个人看过李顺臣将军、拿破仑等人，就根本不能相信他们是真实的历史人物吗？

通过可靠的地图，不就可以知道别的地域的存在，通过历史的记载不就可以 知道过去的事情吗？看过葬礼仪式吗？棺材被埋在地里或是火葬的骨灰都撒完了之后，好象一切都结束了，但肉体虽死，灵魂却是活着的。灵魂不能死，也 不能治死。灵魂是不灭的。参加葬礼时，看见躺在棺材里的尸体，但那只不过是灵魂住过的肉体而已。

那么，死了之后会发生什么事呢？等待灵魂的是什么事情呢？能够明确地解 答这个问题的，只有经历了死亡，又从死里复活的神的儿子耶稣基督。耶稣品尝了死味，击败了死亡的权势，又复活了。所以，对死后的事有最高的权威， 也能说出分明的事实。耶稣很分明地给我们说明了死亡那边的天国世界，是多么美好、多么幸福的住处，也确实地说明了地狱是多么痛苦、多么可怕的地方。

神是无所不能、无所不知的，是信实的。他绝对不是以谎言来恐吓戏弄你的 无耻之人。

若想很容易地明白汽车的构造及使用方法，去查找汽车厂家制定的使用说明 书，把那个熟知就行了；我们通过家电产品的使用说明书，就可以明白家用电器的存在、用法、构造和功能；我们通过设计、完成地狱和天国之神的见证， 就可以正确地明白天国和地狱的存在与用处。神在圣经里详细地解明了你对天国和地狱所顾虑的一切事情。

启示录21～22章详细地介绍了天国的形象。天国是一个有完全的爱与幸福、 永远的生命与和平、惊奇的安息与喜乐的地方。使徒保罗在哥林多后书12章说，自己藉着神的启示看到了那个天国。圣经里有好几个人看到那惊奇又辉煌 的天堂。那个国度永远没有罪和死亡、没有悲哀与痛苦。神赐你机会，让你在神所许下的生涯中，做好通过耶稣基督到天国的确实的准备。

地狱，不是神居住的地方，那里有永远的痛苦与刑罚、绝望和咒诅在等待着 你；那里没有盼望，也没有得救的可能性。神创造众星，又创造太阳这样热的火球，岂不更能创造地狱的火湖吗？假如你想知道地狱的具体形象以及地狱的 痛苦，请你翻开启示录或马太福音10章28节、马可福音9章43～49节、马太福音5章20～30节看一看。

因为死亡之幕挡在你的面前，所以你看不到死亡那边的世界。但不能说那边 什么都没有。你要特别地留意这一点。第一个人亚当犯了罪之后，死刑的宣告就已经临到了众人。所有人都生活在这称为世界的巨大监狱里等待着死亡之 刑。如果你藉着神的道重生了，就会对这一切事实一目了然了。你再怎么想否认神的存在、神的公义和严厉的审判，你再怎么想从心里轻视“地狱”这个词，也绝对不能成功。有一位哲学家说：“迫切地期待没有监狱的是谁呢？那就是 应该下监的人。”期待没有地狱的人又是谁呢？那就是该下地狱的人。撒但(魔鬼)不断地通过我们的想法作工，以至于让我们对神的话语起疑心、不信。虽 然神不断地给我们机会，又引领我们的心，使我们明白神的话语以及你灵魂得救的问题。但是，你若否认圣灵的引导，就只能受撒但的引导，也只能下到永 远的地狱火湖里。这是全能的、公义的、真实的、并照着自己所说出来的话必要成全一切之神宣布。
警告你“危险！”的路标，是放在危险来临之前让你发现和小心的。如同告 知敌人空袭的警报响在攻击开始之前一样。神期待你还没有落在地狱之前，让你明白地狱的危险以至于得救。神创造地狱是有他明确的动机和目的的。对地 狱的可怕作出警告最多的一位，就是神的儿子。请你不要固执“死了才能明白”的观念，请你放弃刚硬之心，快悔改吧！
“你竟任着你刚硬不悔改的心，为自己积蓄忿怒以致神震怒，显他公义审判 的日子来到。”(罗2：5)

