= 4.怎样认识活神的存在

神真的活着吗？对，神真是活着的。我们能清楚地认识到神吗？能。不但能 认识到，还能相信他。我们不但能尝到还能享受神的恩典与能力。

有很多基督徒从前也象你一样，活在怀疑和不信当中，后来才认识到神，得 见神的儿子耶稣基督。听耶稣基督的话语，与他交通，与他同行，得到他的引导。认识神、相信耶稣基督的事情，绝不是不可能的事、困难的事。只是因为 不知道既容易又正确的道路，才觉得那么难。再怎么容易简单的问题，如果不知道就难了。但是问题再怎么难，如果知道了解决的方法，就很容易了。关于 神的问题也是如此，如果找到了正路就会很容易地解决。

不懂英语的人，想理解英语书本，那是不可能的。但是，精通英语的人理解 英语书本，那是太容易的事了。根本不懂英语的我，想和美国人对话，那是不可能的事情。但是美国人学了朝鲜语，而且学得很有实力，能自由地运用朝鲜语，我们与他们对话就很容易了。

神与人之间的交通方法也是如此。神是灵(Spirit)，灵无骨也无肉(路24：39)； 灵不是物质，乃是神。所以靠肉眼是看不到的。我们的肉眼有视野(可视范围) 的限定，只能看到物质世界。所以想用肉眼看见神，这本身就是无知。神是 灵，你靠着肉体是绝对感觉不出来的。再说，也不是靠着人的心能想出来、靠着人的智慧能认识出来的。所以人本身再怎么挣扎，也不可能理解神。也许你 会反问：“那么怎样才能认识神、相信神呢？”因为人靠着自己的感觉、自己的想法是认识不了神的，所以神就通过四种方法亲自显明自己、启示自己，以 至于让我们来认识他，并能相信他。因为神亲自启示给了我们，我们就可以认识神、相信神了。神藉着所造之物显明了神的永能和神性(罗1：20)，通过话 语详细地启示了自己的旨意和计划，又藉着耶稣基督彰显了自己的恩典与慈爱，更藉着圣灵将自己显给我们看。如果你仔细地查考这四个证据，就不难发 现证明“神不存在”是不可能的，就会只能相信神是一位永活神。

**1)藉着所造之物显明了神的永能、智慧和神性**

地球好象是一块围绕太阳每365日5小时48秒转一圈的正确的表。精密的 钟表绝不是偶然装配成的，是藉着人的设计、组合造成的。组装得完全的表，虽然是藉着表内的物理法则来转动，但是设计师可以让表快一点，也可以让表 慢一点。你再怎么以科学方法探索表的内部构造和材料，也不能从中找出设计或组装那表的人。只要表不是偶然的产物，就会有设计表的人，也有制作者， 这是不告而知的。我们虽然没有见过表的设计师、制作者，却不能否认他的存在。不是吗？无论对于任何的存在或对象，产生“因为看不见，就不能相信它 的存在”的想法，那是从“只存在眼所能见的”这样的错误观点、错误前提下得出的无知的结论。

多功能摄像机是自己构成的吗？如果不是这样，肯定会有设计、制作摄像机 的人。因为你“没看见”设计制作摄像机的人，就可以说“没有”设计、制作摄像机的人吗？我们通过制造出来的摄像机，就会知道制造者的智慧和能力以及他的技术。
我们想一下你的眼睛。你的眼睛造得比这世上最精密的摄像机还要精密。自 动调整焦距与光圈，颜色的立体性，并且连续不断地照出物像。这样的超微型多功能摄像机，能是偶然造成的吗？更何况这精密的人的眼睛，是起初被造时 安装在人体内的超微型摄像机。在人类的科学、光学文明还没有胎动的时候，这样的摄像机就已经安装在人体内了。你不觉得这些事情很惊奇吗？更惊奇的 是，在这多功能摄像机里还装置着超微型巨容电脑设备。能说这惊奇的摄像机是偶然的产物吗？圣经上是这么说的：**
“能听的耳，能看的眼，都是耶和华所造的。”(箴20：12)**

不觉得创造主的本领惊人吗？

观察一下雪的结晶体，是那么精致，并且一定是六角形的花纹，从天上降落 下来的那许多雪花都是一定的、精致的结晶体。你觉得这都是“偶然”形成的吗？这都是在显明神惊人的设计和本领。

生存在这世界的生物虽然很复杂，却有着惊人的秩序并且互相协调地生活。 生物体的细胞里带有很复杂的遗传因素，那遗传秩序的维持得惊人般的严紧。如果没有情报(信息)的输入(Mput)，就不能有任何情报的输出(Output)。这是一 个情报科学的基本常识。生物的细胞里都带有遗传情报，这就足以说明必有情报输入者。边解读那情报，边追想那情报输入者，即神，是理所当然的理论。

如果你对于这茫茫宇宙和其中惊奇的秩序进行研究所证实出来的事实稍微观 察一下，就会明白这宇宙和万物绝不是偶然的产物，而是藉着有无限智慧和能力的创造主按照奥妙又完美的设计造出来的事实。

TIP: “你们向上举目，看谁创造这万象。”(赛40：26)

人类连原子世界都不太明白，却想理解无限的神。我们虽然不知道手表的制 作者，却在使用他所造出来的表；我们虽然不知道制作摄像机的人，却也在使用他所制作的摄像机。但基督徒呢，不但知道发明的产品，也知道发明家。德 国的天文学家开普勒说：“科学家是神所创造的被造物的观察者。”

看不见神，但不意味着神不存在；很难相信他的存在，也不意味着他不存 在。神是实实在在的存在着，只是我们瞎了能认识神的灵眼，没有眼力而已。

无神论不过是缺乏对神的认识而产生的想法，不过是相信“没有神”的想法 而已。神是灵，所以用肉眼是看不到的。但是我们的周围有惊奇又奥妙的世界和秩序，所以能明白安置这一切之神的存在。在这个世界，从不显眼的微生物 到茫茫宇宙，都有复杂又细致的构造。所以都是那么井然有序地互相协调着，都是某种目的在起作用。这些事情是不可能偶然产生的，有着非常的智慧和能 力之神的存在是很分明的。

自然界中小小的草叶，也比科学家设计的最复杂的宇宙飞船还要精巧，知道 这个事实吗？既然知道宇宙飞船、飞机都不是偶然的产物，对于一棵草，怎么能说它是偶然的产物呢？从一棵草里怎能看不出神的本领呢？自然界一切的秩 序和法则都是显示神的手段和能力的。

想一想课本的形成。是自由飘荡在空中的字偶然地合成词语、构成句子、形 成文章的吗？不是的。乃是有人带着某种意图把它们排列成有意义的篇章。所以书本分明都是有作者的，是由谁写出来的。一幅画有画家，建筑物有建筑 者。照样，这世界也是藉着创造主神的计划创造出来的。圣经称这位伟大设计者、创造者、建筑者为神。

发掘了埋藏在地里很长时间的土器或金罐，就毫无疑问地说那是古代的遗 物。和那些根本不成对比的精致又复杂的生命体，更不能说是自己形成的吧？前不久，我们的国家也为了纪念定都汉城600周年，造了Time Capsule(时空容器)。Time Capsule是收集能体现出现时代生活气息的各样物件，并以 Capsule的形式造成，埋在地里能保管几百年。我们的后代子孙发掘Time Capsule就会确信这是祖先的人为产物。能够确信Time Capsule是人为的遗物，却把比Time Capsule更精致、更复杂的宇宙，以及在这世上的生命体说成是自然形成的，那是否该怀疑一下你的智能呢？

我们再想一下建造物。你目睹过既小又漂亮的狗窝是自己造的吗？肯定是有 人特意造的。若长时间不理这窝，就会进化成草屋；长时间不理这草屋，就进化成别墅；别墅放一段时间就进化成巨大又复杂的高楼大厦般的建筑。可能 吗？反而那房子随着时间的流失会陈旧、会拆毁的。但是几千年前没有现代的尖端建筑技术，却造出了比现代的建筑物还要精致、复杂的房子。那么，这些 房子是谁造的呢？

你会问：“古代真有这样的建筑物吗？是的，有。就是人的肉体。圣经称人 体为“土房”(伯4：19)，也称为“地上的帐棚”。(林后5：1)对，我们的身体是灵魂居住的房子，材料是水和土，但是要比高楼大厦精密几十万倍。

我们的眼睛好比建筑物的窗户。虽然小了一点，但如果睁开自动窗户的眼 皮，该看的就都能看到了。当然，视力太不好会成为问题，但如果太好了，甚至能看到细菌，那我们就会精神失常的。还有眼泪这个洗涤液能自动滋润、清 洗这窗户。

我们的耳朵既是天线又收发机。抓住外界一切声音，给你识辩的超能收发 机。如果听外界声音的听力超出了现在的范围，象狗那样灵敏，就会因为外界喧哗的声音连觉都睡不好的。相反，听力远远不如现在呢？和别人说话就会很 不方便。无论视力还是听力，神造得都恰到好处。

我们的鼻子是调节器。鼻孔里装有鼻毛和糊状的粘液，以防止灰尘和小虫子 等类随便地进到肺里，相当于上好的空气清洁器。鼻液是抓住通过鼻毛进来的灰尘或微生物并向外排泄。肺泡表面积是全身表面积的20～30倍，通过鼻孔 吸入到体内的空气，每分钟以15～18次的速度不停地换气。空气通过鼻孔的时候，为了使热气凉下来，使凉气变暖，把鼻腔设计成了曲线型。

骨骼相当于建筑物的钢筋。建筑工程学说，按H—Bin工法建造的建筑物 是最坚固的。伟大的建筑家—神，起初造我们的骨胳时，就是按H—Bin工法设计建筑的。人体有206块骨头，神在这骨头上加添了肌肉，在人体的每个重 要部分都设了保护装置：用肋骨保护五脏六腑，用头盖骨保护重要的大脑，使之能承受一般性的冲击。

人体的大脑是用这世上最超能的巨容电脑来指挥整个建筑物的管理室。右边 的管理室担当了空间的、直观的、创造的艺术性；左边的管理室担当了理论的思考、数学的推理、语言的表达等功能。
连络网也散布在身体的每个部位，我们称它为神经网。神经传递信息的速度 可达320千米/小时。
心脏是维持体温的锅炉，可以保证你一生恒定的体温。心脏每天平均跳动 10万次左右，如果以70年为标准计算，就是可以不停地跳动26亿次的超能性锅炉。连接锅炉房的血管是不仅调节体温、又兼作输送网、长约16千米的导 肾脏是性能优越的净化器。抗体是担当了识别、捕捉外部罪犯；作为警卫的抗原体是一生也不退役的预备军。手是多才多艺的万能奴仆，口是可以播放各样声音的播音室，又是引进 燃料的大门肛门就象污物排泄口。

这一切器官的性能不知有多优越，靠着人类的科学和医术所造出来的产品， 远远不及与生俱来的器官。人工造出来的眼睛、心脏、骨头、肾脏、肛门等等，干脆就不能和神的作品相提并论。具备这样设施、功能的房子，不但可以 移动，还能躺着；能折叠，又能倒立；既能浮在水面上，又能爬到树上，一般的地方都可以移动。对这样的事实不觉得惊奇吗？这土房子就算放进水里，也 不是那么容易被破坏的。

尤其这称为肉体的房子是用“细胞”这个材料造成的。大约有60兆～100 兆的细胞形成各种组织和器官。它们互相之间有着深深的关联性，在一定的秩序下，各自发挥着固有的作用，形成了内在的宇宙。那每一个细胞都象比繁华 城市还要复杂的集成电路一样。听说当用电子显微镜观察细胞时，会因着细胞的复杂和精密而赞叹不已的。那中央有DNA链，把人的DNA链解开长达1· 5米左右。那根链象弹簧一样，成为平行螺旋式阶梯，在那阶梯中串连着50 亿以上的遗传因子。50亿这个数字相当于收集在1000册大百科词典中的词汇 量。这么多的遗传情报都包含在用显微镜才可以看出来的一个细胞核里。是有惊人容量的超迷你型集成电路吧？人所开发的最优越的集成电路和DNA相比 实在是太简陋了。那么，是谁把这超容量的情报链输入在如此这般细微的细胞核里的呢？作为一个有常识的人能相信这是偶然的产物吗？有的科学家说，只要把这遗传情报完全释读下来，就可以阐明生命的秘密，DNA就可以成为新的Bible(圣经)。但是严格地说，DNA是造出生命的物质设计图，绝不是生命 的设计图。靠着现在的科学也许能提取或收集一点构成生命体的物质材料，但绝对造不出生命本身。构成细胞的基本元素99%是氢、碳、氮、氧等10多个 元素。虽然阐明了形成细胞的组成成份，但是把这些组合成份都合成了，也造不出生命来。到目前为止，人类的科学仍造不出一个极小的细菌。

人体为了维持高度的生命体形成了惊奇又精密的经营，拥有着再怎么精密的 机械也赶不上的惊奇系统。你的灵魂就住在如此惊奇的房屋里。虽然是用土和水造成的，却又是那么了不起的房子(肉体)。就好像虽然你不知道你所住的房 子是谁在什么时候造的，却住在其中一样。现在你不就是居住在神所创造的宇宙里、神所造的肉体里吗？
你灵魂所住的那惊奇的房子，绝不是偶然被建造的。因为若没有一位超级工 程师，是不会造出这般惊奇、复杂、美好的房屋的。

**“房屋都必有人建造，但建造万物的就是神。”(来3：4)**这句话语中，若在“神” 的位置上换上孔子、释迦摩尼、苏格拉底再读一下，多别扭啊！如果是神，又 是多么自然啊！你现在不想走到为你的灵魂造这般惊奇房屋的神面前吗？你不想谦卑地走到为你建造美好房屋的神面前吗？神既然“为你的灵魂”建造了这 般精巧又美好的房屋，可想而知神是多么爱你的灵魂啊！这位建筑家对你的灵魂带有多么大的关心啊！难道不正是因为住在房屋里的比房屋还要贵重的缘故 吗？

TIP: “自从造天地以来，神的永能和神性是明明可知的，虽是眼不能见，但藉着 所造之物就可以晓得，叫人无可推诿。”(罗1：20)

万物证明神的能力，自然法则证明神的智慧，人的良心在本能地见证神的神 性。你的良心、你的灵魂准确地感觉着你的不义和罪恶，又意识着圣洁的神和神的审判。

并且神所创造的一切被造物，都有它分明的被造目的。人也是，过一种与被 造目的相称的生活时，才能活出有福、有价值、又美好的生活。若脱离了神的创造目的而生活，那就是违背创造宇宙之神的秩序。

**2)藉着圣经可以信神。**

综上所述，神藉着万物显明了神自己的存在与能力、本领与智慧，但藉着这 些，还很难明白神具体的心意。所以神藉着别的方法，即通过圣经话语详细又细致地显明了神自己的世界。

圣经，这个词源于 B.C 十一世纪埃及。造纸原料的名字Papyrus，是希语 的Biblia，后来被称为英语的Bible。

圣经是被圣灵感动的人，按着神的启示记录下来的(彼后1：21)。共有66卷。 是世上到目前为止所记载的最惊奇、最神秘的书。圣经可以看作是引到天国的地图，也可以说是神写给人类的66封信。看地图时最重要的是找出自己要去 的目的地和自己所在的位置；看信的时候，重要的是要读出来信者的心意。

一本圣经分66卷，又可以把这些大体分为旧约和新约两个部分。圣经中最 早记载的几卷书，是在耶稣诞生前1500年记载的。最后一卷的启示录，是在耶稣诞生后100年记载的。这么说圣经是经过1600年才记载完的。如果说旧 约圣经是在耶稣降生之前，神通过自己的先知对关于耶稣基督拯救(赦免罪)人类的应许和预告，那么说新约圣经就是证明了那些应许和预言是通过耶稣基督 成全的事实。如果旧约圣经是建筑物的设计图，耶稣基督则是实施并完成这建筑物的。新约圣经就象介绍建筑物概况的小册子。

圣经记载了从远古的亚洲巴比伦至欧洲罗马的三大陆。旧约圣经大部分是用 古代闪部落语言体系——希伯来语记载的，还有一部分是亚兰语；新约圣经是用希腊语记载的。记载圣经的人至少也有40名，但是，他们的职业、年龄、身 份、阶层各不相同。
其中有路加(医生)、彼得(渔夫)、约书亚(元帅)、阿摩司(牧人)、马太(税吏)、 大卫和所罗门(王)、以斯拉(祭司)、以斯帖(王后)、尼希米(巴比伦的俘虏)、保罗(哲学家)、耶利米(少年)等，还有些我们不知道的人。

圣经作者们并不是集中在一个地方记载圣经的。因为作者们的生存时代不一 样，地域也不一样，并且交通或通讯，也不象今天这样发达，所以圣经作者们各自在不同的地方记录着自己所得到的启示。
摩西是在游行旷野的时候记载了圣经，保罗是在监狱里记载了圣经；但以理 是在王宫里，约翰是在寂寞的岛上记载了圣经。大卫是和敌军争战或被敌军追赶的时候，记下了诗篇的一部分。

圣经的构成还有各种体裁。其中有民族历史，有个人传记；有些是诗歌，有 些是收集了律法的书卷，也有给别人写的书信，还有的书卷是正确地预言了将来要发生的事情。

象这样，圣经是通过很多人、经过很长时间、用不同语言、在不同地点、按 不同形式记载下来的。但很惊奇的是，这66卷的内容不是异质的混和物，整体都是为显明一个主题、一个意义。把66卷整本内容互相有机地调和，便显 出了惊奇的统一性和一致性。任何一个人也不能把这样的碎片组合得这么完整。

即使是把一个世纪期间的书，从各层、各界、不同职业的40作余名作者的 著作中，选择66卷合成一本书之后，再作一下内容比较，那些书能具有一个主题，在同一个意义内有机地调和且带来统一性吗？又怎能象圣经这样通过全 书的每一卷都显明同一个意义呢？

理由很简单。虽然圣经的记录人有40余名，但是作者却只有一位，就是神。

TIP: “你们要查考宣读耶和华的书。……因为我的口已经吩咐，他的灵将他们聚 集。”(赛34：16)

我曾经在高等学校给学生们指导过几年作文。在同一位教师、同一教学过 程、同一种语言、同一本教科书、同一个教室，同一个的时间里，给差不多是同龄的学生们说明和指导写好一篇文章的要点、主题的选立，材料的收集与选 择、构成与心思想、执笔与投稿的要领。

指导完理论知识，便开始让他们实际写作。给学生们同样4个小时的时间， 让他们用自由的主题写一篇随笔。这时候，虽然是在同一个教室里，在同一位教师的指导下，在同样的条件里写出来的文章，但是根据学生们各自不同的经 验、想法、价值观和能力，写出来的文章也各自不同。学生们一次也没写过有同样意识、同样内容的文章。根本就不能期待内容的统一性和一贯性。

但是圣经66卷如同由很多碎片组合成的一个画面一样，惊奇地显示着主题的一致性、有机的调和性与统一性。因为整本圣经分明是藉着神的启示记载下来的。

旧约圣经第一卷记载了亚当子孙的家谱，新约头一卷记载了耶稣基督的家 谱。属于罪人家谱里的人的生活以死亡为结束的，但属于耶稣基督家谱的人的生活却以生命延续着。在基督降世前所记载的旧约圣经最后一卷，是以惧怕与 诅咒结束的；在基督降世后所记载的新约圣经最后一卷书，是以恩典为结束的。创世记说明了人类的悲伤是怎么开始的；启示录说明了这悲伤什么时候结 束。就如圣经共有66卷一样，以赛亚书是66章；旧约圣经39卷的内容和以赛亚书1～39章的内容性格是一样的；新约圣经27卷的内容与以赛亚书40～ 66章(共27章)的内容性格又是一样的。就象以赛亚书40章以罪得赦免的内容为开始一样，圣经中第40卷的马太福音，是以耶稣基督为把我们从罪恶中拯 救出来而降世的内容为开始的。列王纪下的开头记载了以利亚升天之后，在以利亚身上的灵降临到以利沙身上，并通过以利沙拯救濒临死亡的灵魂的内容； 使徒行传的开头记载了耶稣基督升天之后，耶稣基督的灵降临在使徒们的身上，使灵魂活过来而显示了能力的内容。总而言之，圣经都是有伴偶的。

在其他方面也有确实的证据，可以说明圣经是藉着神的灵(神的启示)所写成 的事实。众所周知的旧约圣经，是大约在B.C1500～400年期间所写成的，其中有许多预言。虽然也有对于许多都市、国家和人类历史的预言，可成为核心 的预言，是关于耶稣基督生平的预言(参约5：39、46，路24：44)。

圣经与道德教科书以及别的宗教经典相比，其不同点之一就是，圣经是一本 预言书。圣经中记载了已经正确地成就了的数千条预言，也预言了将来要成就的事情。已经成就的预言当中，有300条以上的预言是通过耶稣基督的生平正 确地实现了。举一个例子，先知以赛亚在耶稣基督初次降世前700年，就正确地预言了弥赛亚由童贞女诞生(赛7：14)、十字架的受难(赛53章)。

你若怀疑预言是否真的成就，那么就请你首先仔细地读一下圣经。就如审判 长判决诉讼案件的时候，不能连一半都没有听完就下判决一样。如果你确认一下圣经中的预言和所成就的证据，以及圣经的科学性、悠久性、心灵的确实 性，你就会相信圣经的。
我们按着一定的环境和条件相结合地查看一下，临到雅各的预言所成就的可 能性。耶稣要生在雅各的后裔中这是已经命定的，雅各有12个儿子，儿子的中犹大支派要诞生弥赛亚的比例是1：12。

先知弥迦预言了耶稣要生在伯利恒。犹大支派生活的区域有100多个村庄， 照着弥迦的预言，耶稣要生在伯利恒的比例是1：100。这么说，两个预言，即雅各和弥迦的预言要同时成就的比例是1：12乘1：100，即1：1200。

据彼得史汤姆博士的著作《科学在说》中(通过美国科学协会的鉴定，1963 年慕迪出版社发行)，关于耶稣的八种预言(诞生，出生地，施洗约翰预备弥赛亚的道路，加略犹大卖主，卖银30两，十字架上的死，拈阄分衣服，葬在财 主的坟墓里)成就在一个人身上的数学比例是1：10乘10的17次方分之一。
说得更确切一点。如果把10的17次方、面额为1元的银币撒在美国德克萨 斯州全地，可以撒5尺多厚。在其中一个银币上标个记号，让一个朦上眼睛的人一下子找出那有记号的银币，就是这“一下子”的比例。

通过几个时代的几位先知所记录下来的300条预言，能够成就在一个人身上 的比例又会是什么程度呢？相当于在比地球还要大的银币堆里，一下子找出有标号的银币的比例。你能说这是偶然成就的吗？

哪怕读一遍路加福音17章21章、马太福音24章、但以理书、启示录等等 书卷，那你就会从中确信圣经正确地预言了人类的命运以及惊奇地成就着的。先知但以理大约在B.C七世纪初，就预言了将来要发生的列国的命运。在但以 理书2章，但以理预言了当时的大帝国巴比伦灭亡之后，会有玛代、波斯帝国兴起，在那之后，希腊帝国和罗马帝国会依次兴起。人类历史果然照预言成就 了。

神对进到迦南地的以色列百姓说，若违背律法，在神面前行恶惹他发怒，就 要把他们分散在列邦。(申4：25～31、28：58～68；利26：33；耶9：16)但是，以色列百姓没有听从神的话，仍在拜偶像行恶。神就照着自己的话，将以色列 百姓分散在列邦之中。A.D70年，耶路撒冷照着申命记28章52～53节的话语，被罗马军队完全占领了。城墙遭到毁坏，以色列百姓有的被杀，有的被卖为 奴。但是神应许他们说，分散在万民中的以色列百姓，若一心归向神，神要重新召集他们，不管他们处在什么地步，应许他们能够归回到故土。(申30：1～ 10)；照着耶利书31章7～11节、23章7～8节；以赛亚书43章5～6节、60章 4节；以西结书37章5～6节的预言，神又引领了大约在2000年之久没有国家的、在外邦做客旅的以色列百姓回到了故土。

1948年5月14日下午4点30分，以色列宣读了《独立宣言》。以此惊奇又 正确地成就了神向以色列百姓应许的预言。请具体地查考一下圣经与以色列的历史，你就能确认圣经真是神惊奇的话语，又能确信圣经里预告了人类历史和 命运的分明事实。

圣经告诉我们：我们现在的这世代就是末世(世界的末了)。圣经预言了末世 要发生的很多事情，这些预言现在又无可推诿地成就在我们眼前。

圣经预言，末世交通发达、知识急增(但12：4)；因着可怕的核战争会有很多 人凄惨地死去(亚14：12)。

虽然现在全世界都在努力地禁止核扩散，但还是面临着悲观的核危机状态。 又预言，末世民要攻打民，国要攻打国，地要大大地震动，多处必有饥荒，爱滋病等可怕的疾病(瘟疫)(路21：10)。按照那话语，现在地球上不正处在发生 人种和宗教与民族之间的矛盾以及大地震吗？严重的饥荒、癌症和以爱滋病为主的各种疾病，不正在到处蔓延着吗？基督徒都深信这一切是预告基督再临的 预兆，是耶稣基督再来的脚步声。不仅如此，圣经还预言世界的末了会有各种恐怖、残忍又非人性的犯罪、环境污染等可怕的事情，也会有气象改变与各种 自然灾害(路21：11)，在这世代谁能否认这些事情正按着圣经的预言成就呢？不久的将来就会出现电脑控制人类的时代。那时候敌基督要出现， 在众人的手 背和前额上受一个印记(启示录13：16～18)。这预言也会马上成就的。

马太福音和路加福音中说：世界的末了会有好些敌基督、假先知兴起来，行 神迹和各种奇事，冒着耶稣的名迷惑多人，误导的事情发生(太24：11)。所以现在也有很多假先知通过神迹(方言、治病、幻想附神、赶鬼)或奇事错误地引 导信仰的方向，使人们不接受罪得赦免、藉着圣灵重生的事情。不仅如此，新闻报纸也不断地报道着有同性恋、至亲残杀、性道德败坏等各种社会病态的不 法之事，从而成就了圣经话语：**“只因不法的事情增多，许多人的爱心才渐渐冷淡了。”(太24：12)**

不惧怕神的警告，将神的话语当作玩笑，只贪恋肉身的快乐，充满同性恋者 的所多玛城(创19章)，最后被火和硫磺毁灭。圣经预言耶稣再来的时候，这世代也会如此(路17：27)；又说末世的人要专顾自己、贪爱钱财、自夸、狂傲、 心不圣洁、不能自约、性情凶暴、不爱良善、爱宴乐等等(提后3：1～4)。

但比那一切更可怕的是，人们虽然听了这一切话和神的警告，也不顾自己的 灵魂，不归向神，不洗尽自己的众罪，甚至到了灭亡忽然临到的那瞬间，人们还不知道死亡来临的这个事实(太24：37～42)。耶稣的再临迫近了！**“所以， 你们要警醒，因为不知道你们的主是哪一天来到……所以，你们也要预备，因为在你们想不到的时候，人子就来了。”(太24：42～44)**。为解决我们的罪来到 这世上的耶稣，要第二次显现，为要拯救那些与罪无关的人到自己地方去(来 9：28)

如果你看一下圣经的预言和以色列的历史，就会在照着圣经的预言都成全的 事实面前大吃一惊的，圣经的属灵权威也会确切地立定在你的心里。

**“你以忠信诚实行过奇妙的事，成就你古时所定的。”(赛25：1)**与我们生活的这个时代相关联的预言，不也照样成就着吗？

**“耶和华成就了他所定的，应验了他古时所命定的。”(哀2：17)**

**“我从起初指明末后的事，从古时言明未成的事，说：‘我的筹算必立定，凡 我所喜悦的，我必成就。’”(赛46：10)**

你要信赖圣经、认定圣经权威的另一种理由之一是，因为不管从科学，还是 从考古学，以及历史方面都有确实又分明的证据。虽然圣经作者们没有用现代的术语表现科学原理，但是比现在的科学家更正确地理解自然，表现得也更 美。

随着历史学以及圣书考古学的发达，更坚定了圣经有毫无疑问、可信赖的价 值。如果你暂时注目一下圣书考古学的研究结果，就会相信圣经确实是真理。你可否知道到现在为止，没有一个人在圣经中发现一个谬论的事实吗？圣经是 引导你的灵魂进入真理的标竿。

神就是通过话语显明了自己，通过话语作工的。那话语是神的品格，是神的 应许，是神的能力。

**3)通过耶稣可以认识神**

人想靠肉眼看见神，想靠耳朵听见神的声音，想靠肉感感觉到神；但神是灵 (约4：24)，灵是没有肉、没有骨的神(路24：39)。所以靠着我们的五官是看不见，摸不着，感觉不到神的。再说，污秽的罪人直接见神，就会当场死去的。

TIP: “你不能看见我的面，因为人见我的面不能存活。”(出33：20)

TIP: “在神面前，月亮也无光亮，星宿也不清洁，何况如虫的人，如蛆的世人呢？” (伯25：5～6)

两眼能直盯着神所造的太阳吗？神所创造的太阳光都不能看，更何况比阳光 更亮的永远的光——神呢？所以神为了住在众人之中，为了在人们当中显明自己，便取了肉身，以人的形象临到了世上，全能的神就成了完全的人，那一位 就是耶稣基督。所以圣经见证：**“神本性一切的丰盛，都有形有体地居住在基督里面。”(西2：9)**又说：**“他本有神的形象……取了奴仆的形象，成为人的样式。”(腓2：6～8)**

TIP: “爱子是那不能看见之神的像，是首生的，在一切被造的以先。因为万 有都是靠他造的。无论是天上的、地上的、能看见的、不能看见的，或是有位的、主治的、执政的、掌权的，一概都是藉着他造的，又是为他造的。他在万 有之先，万有也靠他而立。”(西1：15～17)

有可以见到神的一条道路，那就是在将你心里的众罪永远洗净，你的灵魂得 以洁净的时候才有可能。

**“清心的人有福了，因为他们必得见神。”(太5：8)** 若心得以清洁，就可以用心灵的眼，通过信心见到神，与神交通，与神相 交，与神同行。

耶稣基督是既有完全的神性，又有完全人性的神，又是完全的人。所以从耶 稣基督感孕和出生、教训和行迹、人格与能力、受死与复活等整个生涯中可以看出，具有着在世上任何人身上也找不出的独特面貌，他的整个生涯既是属乎 人的，又是超乎人的。我们在耶稣基督的生涯和工作中可以看出神的神性和能力。

TIP: “从来没有人看见神，只有在父怀里的独生子将他表明出来。”(约1：18)

**基督本是神的像。”(林后4：4)** 因为在他的生涯和工作中显出来的神性和能力，甚至有些人还怀疑耶稣基督 的实际存在。他确实在这个世上生活过。关于他的降世和整个生涯，受死与复活，升天以及再临的事情，不是早已在旧约时代所记录下来的圣经中明白地预 言了吗？

以色列被罗马统治的时候，耶稣降生在一个叫伯利恒的小村子里。他是女人 的后裔(创3：15)，藉着有肉体的童女生的。所以不是承接了犯罪的亚当之血，是藉着童女的身子因圣灵感孕而生的。这件事是照着在耶稣诞生前700年作工 的以赛亚的预言成就的。(赛7：14)

他成长在木匠约瑟的家里，到了30岁通过施洗约翰的施洗，背负了世人的 罪孽，便开始了正式的工作，并在33岁那年受了十字架的刑罚。他的生涯成为人类历史的分水岭。

“历史”用英语讲是“History”。“History”原来是“His”和“Story”的合 成语，译为“他的故事”，就是“历史”这个词的由来。“他”就是指着耶稣基督讲的，历史大体可分为B.C和A.D。B.C是“Before Christ”的缩写。称耶稣降生之前的历史为B.C(主前、基督以前)不是吗？A.D是取拉丁语Anno Domini的缩写，是in the year of our lord的意思。

人类的历史是以耶稣基督为基点划分的，不是以孔子、释迦摩尼、穆罕默德 为基点划分的。耶稣基督的生涯在人类历史上，产生了划时代的影响。你个人的“History”也会因洗净众罪，接受耶稣基督而分为B.C和A.D的。在每个 人的“History”中，没有一件事会比遇见耶稣基督，迎接耶稣基督更重大的事件。

马太、马可、路加、约翰他们各自遇见了耶稣基督，领受了他的教训，经历 了他的能力，目睹了他的生与死和复活后，在四福音书中同一地见证着那个事实。记载大半新约圣经的保罗，曾极力逼迫跟从耶稣教训的人，后来遇见了耶 稣，并成了比任何人都火热地爱耶稣的人，在见证耶稣基督的事上比任何一个人都更愿献身。

耶稣的诞生虽然怪异，但对于相信旧约圣经的预言和神的全能的人来说，是 毫无疑问地可以相信的事实，是只能相信的事实。从某种角度来说：因为他的感孕、诞生、人格，独特又自然，所以他真是与众不同，是以神的能力感孕 的，是配得我们敬拜的。若是他的生活和能力与我们一样，那我们就没有必要去认识他、依靠他、敬畏他了。他的话语又是有权柄、有能力的。他用话语使海的波浪平静，使污鬼被赶出，使病人得医治，使死人复活。话语如此般的权柄、神迹、奇事就证明着他是主管、支配着属灵世界和自然以及 整个生命的神之事实。这世上没有一个人能像耶稣这样带有惊奇的话语、权柄和权势的。

查看一下耶稣的人格，会发现不同于世人。他不是藉着亚当的血生的，乃是 圣灵感孕，是无罪的；他一次也没有犯过神的法。圣经记载说：

TIP: “他并没有犯罪，口里也没有诡诈。他被骂不还口，受害不说威吓的话，只 将自己交托那按公义审判人的主……”(彼前2：22～24)

他从未有过失误、过错，也没有闯下应该思过的事。在他的生涯中也不会发 现自私的行为、嫉妒、自夸的心、恶念或淫念。

所以，他虽然带着与我们相同的肉体，却过着与我们不同的生活，过着我们 再怎么装模作样地过也过不出来的生活。即使耶稣是骗子，圣经是谎言，也当承认相信了骗子的谎言之后的那些人，生活有了根本的变化、成为圣洁、真 实、美好的事实。因为几千年以来凡以心灵接触耶稣话语的人，都得以成义，圣洁了。你曾看过骗子使人的生活带来这样惊奇的变化吗？曾看过这般有能力 又良善的说谎之人吗？你相信使众多的罪人成义、使悲伤的主人公变成快乐的主人公、换绝望的主人公为有美好盼望的主人公、赐那陷在惧怕和不安中的心 灵以平安、使他真幸福的骗子就是耶稣吗？我们通过他可以发现神。虽然基本上没有不认识耶稣的，但正确地认识耶稣的人却不太多。真知道耶稣的人，只能依靠耶稣、敬拜耶稣，只能求他的怜恤。

耶稣不是道德老师，他不是为了传授道德而被钉十字架的。他若是传授道 德，当时也许会得到众人的欢迎；若是为了道德，就不必非得流血受死了。他的话语是关于生命和灵魂的话语，虽然不是道德，却是超越这世的最高尚的道 德。耶稣也不是哲学家。人所造出来的哲学，是不断变化的。几千年以来人类虽然研究了人类本身，但哲学的结果，除我们只能要归到上帝那里去的事实之 外，没有什么别的可以传授。他不是苏格拉底的后辈，或萨特前辈中的一个新的哲学家，他是创造主神，是为了担当众人的罪而来的，是万民的审判者，他 是为了施神的恩典与慈爱而来的全人类的救主；他的教导虽然不是哲学，却是真正的永远的最高哲学。

耶稣虽不是科学家，他的话语却是最高的科学。我们不是相信有科学考证的 话语，乃是相信神用话语见证了的科学。

耶稣虽不是历史学家，但他的话语却是最正确最悠久的历史。圣经里记载最 古老的家谱，甚至记载了这物质世界被创造之前的历史，也明确了灵里的世界和物质的世界是怎样被创造、怎样存在的；记载了人类的起源、根源。

他虽不是大夫，却是惊奇的医师；他不仅能医治我们的肉体，也能医治我们 的心灵。

他是道路、真理、生命。他愿意成为您的道路、真理、生命。请您真诚地倾听一下耶稣的话语，他的话语是活泼长存、又是有权能的。

**4)藉着圣灵的启示可以认识神。**

在前面我们通过万物、通过圣经、通过耶稣基督的生涯和工作，查看了永远 之神存在的事实，以及他的智慧、能力、人格、神性等等。现在你该不得不承认永远之神的存在和圣经是神话语的事实，以及耶稣基督是作为人形之神的本 像了吧？

神愿把自己的存在和权能、属性、人格显明给我们。不但如此，他还愿显现 自己的旨意、计划、慈爱、怜恤、恩典给我们，以至于让人们深知神、信赖神，并与神和睦相处。

照着圣经里所说的具有意念和智慧、感情和意志、权势和能力的神(灵)，他 并不是靠着什么能量、影响力或法则存在的；也不是幽灵或超人,是有人格的活神。神具有几种神性。首先介绍一下其中的几点，然后通过圣灵的工作再查 看一下认识神的道路。
第一：神自我介绍说：**“我是自有永有的。”(出3：14)**

这世上的一切事物或生物体都是必须倚靠什么才能存在、才能生活；依靠别 的物体、别的存在、别的力才能存在。归根到底都存在于神的话语里。但神并不是依靠别的而存在，是自有永有的。他独自支配着包罗万象的事物，他是 **“将生命、气息、万物赐给万人的。”(徒17：25)**

第二：神是完全又是全知全能的。

神是无所不在、无所不见、无所不知、无所不能的。就象大卫在诗篇139篇 所说的一样，神知道我们的体质、意念和行为，他也知道我们的过去、现在、未来。神一眼就能够阅览这世上的开始到末了的一切事情。

TIP: “我坐下，我起来，你都晓得，你从远处知道我的意念。我行路，我躺卧， 你都细察，你也深知我一切所行的……我未成形的体质，你的眼早已看见了。你所定的日子，我尚未度的一日，你都写在你的册上了。”(参诗139：2～4，16)

神不会作不完全的事情，他的话语、恩典、能力以及所作的工作，都是完全 的。通过他所作的工作可以证明出这一点。他是主管永远世界和有限世界的全能者；他是有权能的，甚至能造出属灵的被造物和人，以及整个物质世界；他 造出永远的天国和永远的地狱；他能披戴肉身，又能脱去肉身；他是阿拉法，他是俄梅戛；他不受时间和空间的限制；他具有能把撒但和鬼神打入地狱的权 势，当然也具有把您打入地狱的权势。他一次就可以永远地赦免全人类的过去、现在、未来的罪；他具有一次就可以赦免你一切罪的能力，这样的事情只 有全能的神靠着全能才会作出来。他既能创造万物，也能靠着自己的话语重新收回万物。

他的智慧超越我们的理解能力，他的意念远远地高过我们的意念。(赛55：7)

第三：神是永远不变的。

神若经常变动应许、话语、旨意，或者经常更改自己的意念，我们就不会信 靠他；依赖他的本身也就无意义了。因为神的意念、神的应许、神的话语是永远不变的，神的能力、恩典也是永不改变的。所以我们才可以安心地依靠他、 信赖他。

TIP: “神非人，必不至说谎；也非人子，必不后悔。他说话岂不照着行呢？他发 言岂不要成就呢？”(民23：9)

TIP: “只是他心志已定，谁能使他转意呢？他心里所愿的，就行出来。”(伯23：13)
“神愿意……显明他的旨意是不更改的。”(来6：17)

第四：神是有人格的。

神向我们怀有很多的意念。因他是忌邪的，不能与罪同在；他有无限的怜 悯、慈爱和体恤；他既能恒久忍耐，也会嫉妒、发怒；神有时担心、叹息，也有时震怒。神很细密地鉴察着我们的意念和生活。

TIP: “还是你藐视他丰富的恩慈、宽容、忍耐，不晓得他的恩慈是领你悔改吗？ 你竟任着刚硬不悔改的心，为自己积蓄忿怒，以致神震怒，显他公义审判的日子来到。”(罗2：4～5)

神不但能够爱你、帮你、保守你，也能够引导你的生活。

他也和我们一样，拥有着内心世界。

第五：神是公义、圣洁的。

诗篇记载：**“公义和公平是你宝座的根基。”(诗89：14)**有的人说，因为神是 爱，所以不能把有罪的罪人打入永远的地狱火湖里。他们真是误解了。神是公义的审判官，他必分出罪人和义人，绝不会将有罪的罪人就那么带到天国的。 虽然神是爱，但并不是单单有爱，他是向罪人倾倒烈火般震怒的公义的审判官。务必要明白神是不爱罪恶的。

神是无罪的，是圣洁的。因为神不喜悦恶事(诗5：4)，所以哪怕有丝毫的罪， 也断不能站在神的面前。神不但不听罪人的祷告(约9：31)，如果有罪，便不能与神同住，也不能见到神。神不愿有罪的人在天国里得到永生。天国是不能带着罪进去的国度。神是圣洁的。他不分罪的大小，即使是隐藏的罪，也必要受到死亡的判决。但值得感谢的是，在圣经里有一次就可以罪得赦免的得救道路。

第六：神就是爱。

神爱全人类。神比爱这世上的任何一个被造物更爱人。那是因为人是照着神 的形象造的。更惊奇的事实是，这位神也是真正地爱着你。人爱儿女的理由，也可能是儿女很象自己的缘故吧？就算是这世上最丑陋、无知、污秽的罪人， 神也愿他罪得赦免、重生，为神圣洁的儿女。他虽然恨罪，却爱灵魂，好施怜恤。

如果幼小的孩子患上不治之症，因着病痛苦，生命危在旦夕。那么，不但孩 子痛苦，看守在一旁的父母又该多么焦急、痛苦、难过呢？父母对孩子的爱该有多深多迫切啊！因此，恨恶那病的心，想把孩子从病中拯救出来的心愿，给 孩子医病的心，想挽救生命的心理会更强烈。不是吗？若不能把自己的孩子从病中解救出来，做父母的也不会从痛苦中解脱出来的。只要是父母能做到的， 即使负出生命也愿医治孩子的病；若能代替，宁肯替孩子患病，也会替孩子减轻痛苦的。和那相似，神也看到我们的灵魂因罪患病、叹息、死去的样子，而 深感痛苦、焦急，便披戴与我们相同的肉体来到这世上，代替我们背负我们的罪恶和疾病。那一位就是耶稣基督。**“惟有我为自己的缘故涂抹你的过犯。”(赛 43：25)**

我们通过圣灵的启示就可以认识这样的神，通过话语就可以认识他、经历他 的世界；通过圣灵的工作可以尝到神的爱、神的恩典。当你听了罪赦免的福音，从罪中得救的时候，就是你首次与耶稣的相见。如果你听了神的话语，藉 着主耶稣的宝血罪得赦免了，神的圣灵就会临到你的心里。圣灵会临到所有敞开心门接受神的话语而成义的、重生的人心里，并引导他的生活。到现在为 止，有很多人藉着圣灵的启示，领悟到福音的秘密，经历了神。如果你也听到罪得赦免、迎接圣灵，听到基督的话语，也会确实地遇见耶稣的。

TIP: “那靠着从天上差来的圣灵传福音给你们的人，现在将这些事报给你们。”(彼 前1：12)

圣经里出现的挪亚、亚伯拉罕、雅各、约瑟、摩西、约书亚、大卫、尼希 米、但以理、施洗约翰、彼得、使徒保罗……等，都是因听了并相信了那藉着耶稣基督的宝血众罪得以赦免的得救的福音，而接受了圣灵，靠着圣灵引导生 活的人。

圣经满有确信地宣布说：**“有许多的见证人，如同云彩围着我们。”(希12：1) **是有许多的见证人。

神是满有能力的，不管你是何等人，他都能拯救、改变。问题是你并没有如 饥似渴地想遇见神，想靠着他的恩典罪得赦免而得到永生。你若是真有想蒙恩典的心、饥渴的心，耶稣必定会寻见你的。

相信神的话语，藉着圣灵重生的基督徒，不论他们是在什么时代、在什么地 方生活；不论他们的血统、风俗、语言、性格、环境、知识、贫富、贵贱，都有同样的经历、同样的信心、同样的盼望、同样的见证，无一例外，都是以同 样的信心迎接耶稣，藉着罪得赦免而成义并接受圣灵的。

TIP: “……叫你们的罪得赦，就必领受所赐的圣灵。因为这应许是给你们和你们 的儿女，并一切在远方的人，就是主我们神所召来的。”(徒2：38～39)

不觉得这事很惊奇、很奥妙吗？所有的基督徒怎么能超越时代、地域和语 言、民族与风俗，靠着同样的方法遇见神，并有同样的属灵经历呢？能说明这一点的只有一个，那就是藉着圣灵的工作，才会有这般神奇又惊人的事情。

宗教改革的先驱者马丁·路得，原是天主教的修道士，又是神甫。他信神信 了很长时间，守过各种宗教仪式。虽然为了得救努力挣扎过，但是，因为心里的罪没有洗清而痛苦地生活着。1508年的一天，当他读罗马书1章17节的时 候，圣灵使他藉着话语领悟了福音的秘密，使他脱掉罪恶的担子重生为义人。从那时起，他的一生就被圣灵的意志所抓住。他所遇见的耶稣和我们今天所遇 见的耶稣是同样的。现在我们也经历着他的属灵经验。

读了他写的《基督徒的自由》、《罗马书释义》就能明白，他所拥有的信心我 们同样也有。显明在他身上的耶稣，也会以同样的方法与能力显明在我们身上的。
他是十六世纪的德国人，我们是二十世纪的韩国，却有着同样的信心、同样的盼望、同样的心灵世界。我们分明又时常地感觉到，耶稣也以引导路得的方法和话语、能力引导着我们。

不仅是他，监理教的创始人约翰·卫斯理；十九世纪美国的最初传道者D.L慕迪；在中国传过福音的戴德生；《天路历程》的作者约翰·本仁；赞美诗《救赎象我这样的罪人》(Amazing Grace！ How sweet the sound！)的作者约翰·牛顿，都是藉着圣灵的工作而罪得赦免，并成为伟大的传道者。他们都是听信了神的话语，把圣灵迎接在心里的人。他们都是过着同样的信心生活， 有着同样的盼望，走着同样的道路，怀有同样的心愿，那是因为他们接受了同一位圣灵的引导。

圣经和圣灵有能够改变人的心和生活的惊人能力。有很多人受了圣经话语的 感动，领悟悔改并远离罪恶，更换心志，活出崭新的生活。现在在重生教会里的基督徒，无论是谁都有那样的见证。

如果你心里的罪得到赦免迎接了圣灵，从那时起，你就会睁开可以看到属灵 世界的眼睛，灵耳开通，能够听到圣灵的声音，能够感觉到神的帮助，能够品尝到神的爱；从那时起，就可以经历神的能力，可以发现神的世界。

写出不朽名著《BENHER》的威利斯，原是极其反对基督教的人。他为了 证明圣经的虚构性和有害性，为了否认基督教而读了圣经。可是他读着读着就陷入在圣经话语中，终于藉着圣灵重生了。他得知真理之后成了神的人，并将 一生都献在传福音的事上。

未曾认识神的人、敌对神的人、否认神的人，最后把自己的一生专献给神的 例子不计其数；也有很多陷入在污秽、可恶、放荡生活当中的人，因着耶稣基督有了惊人改变的情况；陷在生活的挫折、悲伤与无意义当中的人，重新得到 盼望、得到能力、得到喜乐的见证也不可胜数。这世上任何一个人也不能在漫长的岁月里不断地这样改变着人们，世上任何一本书也不能象圣经那样，能根 本地改变任何一个人的心和生活。但神的话语是活泼的，是有能力的，能够改变任何一个人，现在也正在改变着。神就是愿你成为蒙这样的祝福与恩典的主 人公。

你若真愿意参与这样的恩典和祝福，请你马上和下面所介绍的教会联系，不论什么时候，愿意更详细地和你交谈。
