= 信仰的三阶段
张红军

.以弗所书 4:17-24 和合本
****
所以我说，且在主里确实地说，你们行事不要再像外邦人存虚妄的心行事。他们心地昏昧，与　神所赐的生命隔绝了，都因自己无知，心里刚硬；良心既然丧尽，就放纵私欲，贪行种种的污秽。你们学了基督，却不是这样。如果你们听过他的道，领了他的教，学了他的真理，就要脱去你们从前行为上的旧人，这旧人是因私欲的迷惑渐渐变坏的；又要将你们的心志改换一新，并且穿上新人；这新人是照着　神的形象造的，有真理的仁义和圣洁。
****

好，读到这里是24节，这圣经非常熟悉的经文，我们还是再讲一次了，我们这只是开始会合起来，现在998人上来，刚才1000人有两个下去了，可能掉线了！还有一些人没有上来，因为我们这个房间最多只能装1000人，全国执事干事已经1000多人是吧？这是非常感谢神了，福音94年进到中国来，一点点的发展过来。以前的话信徒也很少，现在执事干事有1000人了，这是非常有盼望，特别感谢神。我们说这执事干事很好的被神引导的话，很好地被引导被使用着，接着我们会生出很多果子来，圣经里说基督徒是特别的，一旦基督徒被神引导的话，神借着基督徒做很大的工作。

圣经里边例《利未记》有这样的话
[quote, 利未记 26:7-8 和合本]
____
你们要追赶仇敌，他们必倒在你们刀下。你们五个人要追赶一百人，一百人要追赶一万人；仇敌必倒在你们刀下。
____

我们1000人就是追赶10万人，有1000多个执事干事。非常感谢我们聚会几天了，今天有个特殊情况，所以都在家里聚会了。

我们从大年初二大年初三开始，初三开始就一直直播一直聚会，一直记到现在，没有哪一年像今年一样，上午、下午、晚上总是一直聚会了。因为特殊情况执事们聚一周，也非常感谢神。今天是周四，我们聚了几天一直听老师讲话语，老师有事情我来讲一次，我心里想讲什么样的话语呢？然后还是想讲一些很重要的，我感觉很基础的很重要的还是讲讲这样的话。

== 身份很重要

我们是基督徒，然后我们是执事干事，这个身份非常重要，身份重要。首先不是生活，首先是生命。

我讲的《生命生活50讲》就可以起了名字，**有什么生命过什么的生活**。先拥有生命，我们是蒙神特别恩典，是拥有神生命的人，我们不单是拥有神的生命，能够在教会被树立，能够成为执事干事，这些非常重要。**在心里面得常常纪念神给我们的这个职份**。我们生活怎么改变？如果你心里常常纪念这个职分的话，纪念这个名字的话，神就会引导我们的心。我们是执事的神给我们执事的心。

今年是2020年，去年是2019年，2019年的时候，我正好毕业20年了。毕业20年有返校的时间，本来同学互相联系的不多，就几个同学联系了一下，2020年需要返校，但不是说一定得去，如果能去尽量去要返校，所以全班的通讯录班长就召集召集，把全班同学的都集合到一个群里边，我们是952土木建筑系交通复建工程，952，95年2班的。然后把同学都聚在一起了，聚到一个群里边，一共30个同学，三个同学都拉到群里还都找到了，有的出国也找到了，全都找到了，在一个群里边。然后因为互相都不怎么联系了，所以需要先统计一下，填一些东西，然后叫什么名字、电话号码、住在哪、现在做什么工作、家庭住址等等，来填这些。来填这些的时候，然后这个我填这些，你现在做什么呢？说假话也不合适，但是有同学知道我传达，然后就填写我在传道，在深圳传道，然后现在我的职分是牧师，填了以后同学们也没有太说什么，有的也打打招呼，然后就过去了。

因为都是同学们，同学在一起的话，一搬有随便的说话的人，还互相取笑的，有互相开玩笑，一般男男女女的开玩笑说，你怎么样你怎么样。然后在班级的时候，有时候有捉弄的有被捉弄的人，总会有几个人被大家都取笑他，捉弄他，他们也不感觉怎么样，反正互相开玩笑。在群里面，然后互相还是这样的，还是叫小名或者叫外号，然后住互相捉弄一下你是不是怎么样了，是不是怎么样，我就看着他们互相这么说的时候，然后我也可想说一句，我可想到跟着说一句，你有感觉有意思吗，互相说有意思，我也很想说一句，但一想到我名录里面我报的我是牧师，一想到是牧师的时候，你怎么也不能说，你要说一句的话，别人会嘲笑你的，你笑话了别人，别人会反过来嘲笑你。

什么是保守我们的生活呢？保守的嘴呢？就是牧师的职份保守了。一想到我是牧师的话，就不能随便生活，就不能随便做了。**我是这个义人的身份，我是义人了，我是神的儿女，我是执事，我是天国的子民，这些常常纪念才可以。**当我们心里常常纪念这个身份的时候，在这个身份里边，我们心里就会有感谢的心。但如果忘记这个身份的时候，我们心有时候就会随波逐流，别人怎么样就会跟着怎么样？一定得纪念这个身份，我们是义人，是执事是干事，这个是重要的事情，好像这个有什么重要的呢？这个就是重要的。

我最初在山西大同传达了当时传道的时候，然后那时候有一个弟兄得救了，就得很明确，得救之前有点随便生活，然后之后都整理了都挺好，全都挺好。然后到了过春节的时间，他们有同学聚会，有同学聚会的时候，然后同学聚在一起，聚在一起的时候，他那时候差不多能三十六七岁，好像是那么个年龄。这个同学会不是太好的会，我感觉同学会不太好，同学会互相有的会乱的，这个同学会旧情会勾起来。然后他去看参加同学会的时候，然后他个子多少高一点，反正长得很膀，然后有一个女同学就好像上学的时候互相有了一点感觉，然后一个女同学就好像就有点旧情那样，然后就开始这么说话，然后怎么样？然后同学会结束以后，然后女同学她跟你女同学就互相那时候还没有微信，还不能视频聊天。这个挺好，那时候没有微信。挺好，如果微信可能会更出问题它了，有短信，然后就互相发短信，然后发短信这么发以后，然后心就流往下画，就感觉到对方的心，然后自己也感觉自己的心是往下往下滑的心。就这样了，这个方面很不好把握的。**知道不对，但是能感觉到自己的心往下滑**，自己心里有一点困惑起来！然后心里很难，所以就在神面前祷告。也不是很诚恳的祷告。主啊怎么办？就这么祷告，然后下午来聚会，来聚会的时候心里很乱的了，那天下午讲道的时候，将了《腓立比书 3:20》 

[quote, 腓立比书 3:20 和合本]
____
我们却是天上的国民，并且等候救主，就是主耶稣基督从天上降临。
____

那天讲话讲了，我们却是天上的国民，那天听那个话他里面一下醒过来，我们是天上的国民，天上的国民这样说不可以，一个身份让她心里一下就画了线了。结束的时候他找我，跟我作见证说老师我这两天我心里可乱了，乱七八糟，但是我听你讲道，我看圣经的时候，我是天上的国民，我一心一下整理了，一下子干净了，画了线了，这个就是心里面就分开了，本来没有出乱子，本来没有出什么事，但心里面有问题，但借着一个身份一下就整理了。就这个身份非常重要，我们是我们是义人，我们是天上的国民，我们是执事，我们是干事，一定纪念这个身份，纪念教会给的职份，我们心里纪念这个的时候，神就藉着圣灵引导着我们的心。

我们是怎样的？是如果是弟兄姊妹的话，神会给我们弟兄姊妹那样的心，神会给我们那样的感动；如果是执事的话，神给我们执事的心，你是长老的话神给你当长老的心，你是牧师神给你牧师的心。**神给什么职分，神就给什么样的心，心跟身份是相配合的。**所以纪念我们的身份，在纪念身份的同时，神的心就会在我们心里发动会引导我们的心。

我说我们每个人如果在神面前很好的被神使用，很好的被神带领的话，神借着我们一定做很多宝贵的工作。

TODO：13:30

我们晚上聚会时间不是很长，所以我就直接就进入正题上讲着，大家每个人如果很好的被神使用的话，神借着我们都能做很宝贵的工作。但是我们心里面没有很好的被神谁引导的话，我们就变得非常软弱，所以对我们一个人非常关键。这一个人如果被神引导被神使用的话，借着他结很多的果子，神通过它做很多工作。他如果这个人没有被水淹脑胀滑下去的话，生活就变得非常混乱又散漫，所以我们一定很好地背着引导，才可以心理的很好的被谁引导？被神带领。所以说我们听的是牧师的讲的话，讲的是尼希米记叫灵犀米系米，7米级第1张，大家这里也听了有小视频，有一分钟44秒有节选的小视频，大家不知道看没看那小视频，反正事物说一分钟话语就是听着牧师的讲道，牧师刚讲这这个是为什么记得尼希米见到城墙呢？


因为在你心里心别人你听说耶路撒冷城墙倒塌以后，别人心里没有什么感觉，都很麻木的那么过去了。但你心里不一样，你心里听见以后你心里很伤痛，你心里就紧驰尼西米哭泣。明细没？T百姓一起认罪，你心不在这边求着神，他很想重新穷建成讲神奇的你心能见成效的原因，是因为在你心里清楚，这样的心，就新时代能够重建成讲，这个心是宝贵的。就35里面保护的心是重要的，宝贵的心保护地区怎么得来宝贵的心，就是圣灵的引导。称了研讨了你心里圣灵引导你心里剩下的同样能够引导我们，就剩咱们心里带领着我们。
圣灵怎么才能带领我们呢？换句话说，能很好的被圣灵带领，我们需要走的路，是什么样的路呢？今天我们借着话语，我们来讲一讲这，顺便讲一讲我们心里的3点信的3点，有心理很好的被圣人带领的3点来讲一讲，那么看着身体来说一说，以弗所书，翻过来看衣服损书，你不走出第4章，我们来看一下。第4章，这圣经非常熟悉，17~24也非常熟悉，可能听过很多次。在这圣经里面可以说3点17姐说，所以我说切在主里确实的说，你们行事不要再像外包人存虚妄的心行事，一个不要我说不要。
这个可后边哪个是对应的22解说，就要突去你们同学行为上的旧人。这旧人是因私欲的迷惑渐渐变坏的。是一个我直接选了这两节读，中间有一些没有读了。这熟悉的圣经，我自己当选了，有时要想很好的被水引导，第一是什么呢？第一得先有个不要，也就是22节的脱去。22、23、24，这三姐是三个点，22出的事就要脱去你们同学行为上的旧人，这就人生因私欲的迷惑渐渐变坏的，又要将你们的心志改换一新，并且穿上新人，杀也是脱去。
23解释又要。24节是并且是个递进的关系，是一步一步的往前走。第1部是什么？对，第1步就是就要脱去你们从前行为上的旧人。那就人是怎么生活的呢？后边说这旧人是因私欲的迷惑渐渐变坏的。就人过的生活就是被私欲牵引的生活，就是顺着私欲的生活是就人的生活，就人的生活就是顺着私欲的生活，就是就人的生活，我们得绣了，我们只是也得干，是这个都一样。跟一样的，还有一个有这个蒙了是难点是这样。他跟这个一样，还有个什么？就是孙德就是一人，这个都没问题了。
但是都有肉体，我们都有肉体了，都有肉体，所以我们生活的时候一旦有什么环境的时候，有利益关系的时候，好。没得出来的是思域。有肉体在最。都有私欲。所以现在如果还是顺着私欲这么生活的话，就是过着跟救人一样的生活。已经是艺人了，已经是新的被造物了。从新说已经是艺人了，已经是新的被造物了。但如果我们心里还是顺着私欲生活的话，就过了就人的生活了。剩女的说要突去你们从前行为上的旧人，跟to去这个才可以，但如果没有拖鞋还顺着思域活的话，过着就着一样的生活，过着就人的生活，跟新人就不能叫新人彰显出来了。
所以想生活第一重要的是什么？可以说节制。不是顺着词语划下去了，节制肉体还是说铁器泄气了？从心里的一瞥气，姐击落几周，第2个才是站在神面前。第3个就是能被水引导。我们10篇有的一篇诗篇的第一篇不开身，你这么说一下，视频的第1篇大家都知道是不是？是跟第1篇，第1句话是什么？10遍，第1遍、第一句话是不从恶人的计谋，不站罪人的道路，不坐亵慢人的座位，后面说危险液化的律法，昼夜思想，这人便为有福。不是这些思想中的立法。
首先第一县是什么呢？不从不占。不错。首先一个不子，因为信仰从哪里开始的呢？从铺子开始，10片中铺子，开始没有撇弃的话就不能够跟随亲的。如果有人要跟从我就打折季蛇气以后才能跟随主。如果没有设计的话就不能跟随主了。就舍什么舍我里面的欲望，我理的想法，我们是蒙神特别恩典的人，神拯救我们，这是蒙神特别恩典的人，但是这个心一种清洁的新保守起来不是很容易，这就是得救了。而且蒙恩典被树立了，但是一直保持目视里边清洁的心，在神面前敬为神敬虔的心，就差得很多。
我们都保持新的话，能很好的背景带领的被他使用者，但是不知不觉我们心里会容纳一些东西，会容纳我们去容纳了以后，容纳他们次以后，最后的话就被捆绑起来了。艺人就是艺人了。一人跟最人就是不一样。这个罪是享受罪中之乐的醉人享受罪中之乐，但艺人的话是享受不了最终之乐的，现在我们可能还会犯罪，还会遵守得滑下去。但那个思路跟以前已经不一样了。吃醉人的时候，我们随便喝酒，随便玩，随便犯罪的时候心里高兴，因为是最的。
很高兴。担心的艺人乐意，如果还是那么生活的话，心里面玩了一阵可能是高兴的。但那时候过去以后你心里就是累的，会有责备的。然后心里后悔，心理黑暗，然后心里面反正很空虚，很软弱，很没力量。为什么这种感觉？因为你是一人了，所以一一人就不能享受罪中之乐。做苍蝇的时候，在厕所里飞是正常的，但从密封之后还去厕所飞，那就不合适了。摊在厕所飞变成木蜜蜂绣花李飞彩就合适了，北京花了一飞，就在心里面这种意识就要建立起来，我是一人了，一人不该过被私欲牵引的生活了，而且在心里面得I有这样一种智慧林什么智慧？我顺着私欲生活，一切全都败坏。
为什么这么软弱了？为什么这么没力量？因为我走了，顺着私欲走的路，我路走错了，所以到今天这个光景，思雨真害了我了，我被他骗了，在心里找到真正的仇敌，他真是我的敌人，他这是欺骗我的，他是害我的。让在心里画出线来画个线，然后心里转过来，加上所罗门最后转过来行为一样。所以我们最后形容这些事都已听见了，总意就是敬畏神，谨守他的诫命，这人所当尽的本分，到最后所能得到一个智慧，这智慧就是什么呢？敬畏的神跟随着神的引导，得这么生活，因为他都体会过了，体会过以后，他发现了其他时候都是错的，带给自己的露水虚功都是痛苦，就在心里面得到这样一个智慧，让他很好的站在神面前生活。
我不知道我们心头怎样，都是怎么生活的？我到现在为止传到再过几个月的话，再过两个月再过两一个多月，一个多月就正好20年了。正好20年。20年这样走过来也是风风雨雨，虽然也不能说太怎么样，反正也是很坎坷，蒙神恩典、神保守，过来蒙神恩典、神保守过来，担心的20年，这是蒙了神的恩典保守了。中介有黑暗的时候，有出问题的时候，有经过看守所等等，有很多坎坷神经的笑会保守。所以走到今天，在我心里面现在感受到牧师所说的话，陌生说那个话里边故事讲到了里面那个话，那个话里面的心里我心能感受到一点，然后不能说陌生心里面都能感受，但一点我能感受到，就木是心里面跟我们说讲坏的时候，讲到的时候，他顺着私欲生活太可怕的结果太可怕的。
生活上面全都掰坏了，全都败坏。每天我心里容纳了次以后，最后全都败完了，就说为什么没力量，没亮的原因就是我们跟随着斯羽走了，我们里面都有私欲，每人都有词语，我们里边有贪心，里面有树立自己的心，有污秽的心，这些思语都有，得他肉体还是在有私欲。思雨头一事情一来了以后，我们现在就起来那些心，你心里如果顺着内心走的话，最后就全都败完了，就是不行了。是一个模式对的，讲道长讲一分钟，发一里面常讲提了三个人物，提了谁？
给他走了门，所罗门顺着一条路走了。第2题，这个猜准，它就顺着路走了，扫路也顺着路走了，它们共同点都顺着思绪走了，所罗门顺着走了，他就顺着走了，然后都顺着走了。这就是你说画面看不到我。应该能看到我是不是？有两人打字说话没看不到，能看到你翻到第1页就能看到我了，一段田翻到第1页就能看到我了，应该能看到我。好吧，看不到你没事今生就可以能看到也能看到，好了，重新说！我说，所罗门参孙宝贵的人都是宝贵的人，谁出的宝贵的人？
但这我全都拜完了，全办的原因什么？都顺着岁走了，顺着肉体的私欲所容纳了词语。荣娜斯以后到最后就都软弱了，道路全都不行了，我们跟安徽的很像。跟很多单位都很像，所以有很多当官的刚开始没有讲的是没有讲到贪污犯罪，有很多单位从农村里出来的，也想着造福一方人民，造福一方百姓，也想做个父母官，又这样的想法！但来了以后当官以后，第1次人贿赂他了，没有要，他以后又怎么样？然后贿赂人要了。要了第1次要了第2次药了，第3次，压完三次以后，想当父母官，为百姓找你的心全都不见了，剩下来的全部都是贿赂，就想怎么能多得钱，心就全部麻木了，良心全部上劲了，生活就全部混乱。
基督徒是一样，我们是一样一样的，比什么都重要，就是我们自身的生活，我们自身的生活是比什么都重要的，我们虽然是得救了，但如果你顺着思维这么滑下去的，就顾着救人一样的生活，你顺着思绪这么生活的时候，你里面慢慢就都黑暗了，心里面慢慢都成为斯都被撕一捆绑起来，最后都成为私欲的奴隶了。又非常软弱了，你里面就没有想传福音的心，就没有爱灵魂的心了。而且读圣经还是读个表面，到时候心就会死掉了，清就会死掉。孙这厮一走生活的结果体贴肉则就是死，这个谁也改变不了的事实，你顺着丝与生活结果，你心就会死掉！
不是下地你是能唱，听我说没问题了，但你心里就不能被水淹到了，心里感动就没有了。然后就只能做这表面一些工作。事情上还能做，但新不行了。形式上过着，你心里没有力量了，感恩的心就没有了，木刚得救的时候，帮格就心里非常感谢，也感谢感动，我们心很好的时候就唱这歌也很感动，唱着喝，有时候听话也很感动。我说句会让心理很迫切的想去，然后花一些钱也得去。我们最初开这样会的时候，我听说在姜家店开享会的时候，在吉林家店开全会的时候，全国各地人都去加D开校会，自远从广州去最远的，从广州坐火车去江家店开校会，那时候97年98年的光火车是多么man的，所以做两两天多的时间坐火车，那时候还是自己带着被子说，自己带着被子坐两天多的火车去家店开小会，到那去住住在都是住在地下，地上上铺着草，铺上塑料布，然后就那样的。
就住在那，然后那时候气流火热的心像这话语心里活着的一些，如果你顺着私欲这么生活的话，后来心就没有了，人心没有的话就不行了，一旦没有新的话，就不成了做不成事了，心里面没有过什么心的话，铺就结不了果子了。在外面做一些外围的工作，但已经新的已经不能很好的被陈大已经被人食用，这个不行了，生活就不行。比如说行尸走肉差不多了。在神那里就是行尸走肉了。体贴肉体的就是死。所以信仰生活的话3点，第1点重要是铁及肉体步子10个字，第1点是没有这个的话就没有信仰，容纳了肉体以后就全都不行了。
我们教会里面教会你过生活，新处有这样几种，有的人心里面贴近肉体了，一直跟上来，这样很少。很少有这样几个人跟挺宝贵的。一般人是中建随大溜的，还有的人呢是非常固定的，肉体里边no，这是绝对不拆毁的，绝对不撇，弃的就知道没罪了。就知道没罪了，所以最没有了。最觉得没有了，就这没罪了，肉体绝对不撇弃。我这样说我就人在教会里面凑一个数字，但什么通过他什么也做不了，什么也不做。每天来了走了话，一听都是理论，也听到心里来就过得非常可怜，我们在前面我们教会的支持带动，在前面，我们可以说我们是领头的伸头痒算头羊，涉及到有这样一句话，我们看一句插一句，10世纪看一下试试句。
1010世纪第5章是实际D鼓掌，是第5章233页，233。5张1检2检，10世纪5章一节二讲意见。那时底部拉和雅比奴案的儿子做哥说，因为以色列中有军长率领，百姓也甘心牺牲自己，你们应当送带一盒话，因为第2点说，因为以色列中有军长率领，百姓也甘心牺牲自己。是。有因为百姓为什么该写新的自己！因为以色列中有军长率领勋章在前面这么领着，所以百姓也甘心牺牲自己。军长重要，我们在前面领着，后面跟着。首先亲站台边走正路后面摆这么跟着走正路。
怎么在前面第一重要就是在我们心里面需要有个舍得，不能顺着丝玉华，随着C活到头指定全都不行了，全部都不行，我心里面能感觉到，我现在感觉这个是最重要的点！第1点就是第一重要的点是在这！我盖过礼拜几个礼拜，谈上以前盖过。在每个礼拜堂的时候，一般都是先计算个你花多少钱，特别是大中的礼拜堂，还有在缅甸勐拉盖礼拜堂，盖这两个礼拜堂的时候，一般都是先计算的。花多少钱我算一算，花多少钱，然后第一是租这个，然后第2个就是看算一算丁姊妹能奉献多少钱？
谁当家不当家，不知材米贵，盖个房子这很不容易。盖个你说盖个房子少活三年，我感觉真这么回事，我要干一个真是不容易，这是过程真是不容易。然后第二就是算算金融资本能奉献多少钱，然后风电到一般的地方姊妹的话，一般风险500分，1000的差不多差不多，然后主要就算算看看那几个有钱的那种风险，多少钱，这些都是心理活动。这个都是实话实说，就是这样，那几个有钱的风险多少钱，然后自己心里面所有的都是匿名的，没有一个是酌定说必须风险多少，必须要求我。
从来没这么做过。都是甘心乐意的看看他们甘心乐意的奉献多少钱，然后就算算一算，我讲讲他的风险多少钱，然后这样想想，然后这么算算以后，一般到第4步就是不够，这肯定不够。因为看每个礼拜堂一般都花挺多钱吗？这不够。完成怎么整的，然后就煮就祷告主祷告主，然后接着打个主，再往前的话，神就带领我神经开始带领我带领带动哪个地位，就是你会奉献多少钱？就问我你奉献多少钱？所以到最后的点的话一定是落到这儿的，就是你奉贤多少钱落在我自己身上，这个礼拜堂能不能看一场，不是大家能奉献多少，就是你风险多少？
因为我是代理人，好像如果我遇过负担的奉献，后背跟着越过负担的风险，如果我尽力做的话，后面的跟着尽力去做。如果我借钱都奉献的话，别人能跟着借钱风险嗖地做成不做成就是在于我身上。我自己心里体会就是这样的，我怎么走后面怎么跟着，所以不能前跟着，按照一部分能跟上来，就是神就看着我，好像这个是一样的，我举个例子来说，所有的焦点在哪？我们自身的信仰，资深的信仰，我们只是看后面，我们带着小组，一个小组，D姊妹们他们怎么过？首先头一个是我们怎么过？
我们先怎么过？绝对性不是做事，绝对先不是做事，所以逃逸的绝对是我在身边怎么生活，我顺着私欲这么滑下去，这么生活的话就全部都软弱了，全都软弱了。就在我这里必须得整理新来整理新，所以第一步一定首先先是脱去，就要脱去你们从前行为上的旧梁。这就是怎么生活是随着私欲生活的，就顺着私欲生活，生活一定的结束得接触，不能顺着丝与生活，你顺着撕一冲就完全乱了。全部都乱了。这是第1个重要的点。第1个重要点就在这，我这样讲这时间不太多，我就讲到还有点直接有没有举太多的例子？
来请你对照一下，你是怎么生活现在？你怎么生活呢？主张话语的是以后的事。主张换一换这第3步，站在神面前生活的人才会主张话语！顺着私欲生活的人主张坏只是什么？只是自我安慰，那个一点意义都没有。你心里再顺着丝与生活这口上说着话语，都是自己骗自己了。那话也在心里绝对没利，一定！首先，第1步，先心里割舍词语，这第1步，割舍词语，有一些每个人不一样，有些人在这个方面软弱，有人在那个方面软弱，你如果容纳软弱，就是容纳那个词语，这么生活的话，司仪会把你心完全捆绑起来，在软弱的地方得靠着圣灵胜过去咖啡盛宴还是不行，一定靠着教会跟老师说，老师帮助，然后送过去，要是不要不然就不行了。
要不也不行。我们一起出去的时候，一起受训的时候，然后那时候有我们一起66个人一起受训，然后有一个弟兄他的他是朝鲜族，然后那时候抽烟，我抽烟这事不行，出现怎么心跳行怎么能抽烟弹，它是朝鲜驻当时传到对来得非常清。所以传统的一来day翻译他就跟着发一，所以老师也跟他说交通还是不行，抽烟事情好像不是太大。他这个是不是太大？然后他就一直抽烟，到后来的时候，他一年一半，我到两年派遣了，到一年半不到一年半，他就离开教会了，他就受训不了了。
一个小小的词语好像没多大是小的，他不是那样。你心里容纳了这个事以后，C把你心都捆绑起来。对。干净的必须画线，小的思忆不是容纳它划线画眼线，心理线画出来就有力量，心里不划线就没力量，所以大家看自己的心，自己的生活！我说，首先，千万不要先主张话语，第一不主张话，也是第3步的第1步，首先一定得是先划线，跟思宇画线画展现第1部是这个地儿是什么呢？我们翻过来衣服锁住看一下，翻过来第1步，先是根丝女化现，就是脱去，那天，那不是什么以弗所书这么说，顺序大一些。
以弗所书第4章一幅图是第4家，4:22点说，就要脱去你们从前行为上的旧人，这旧人是因私欲的迷惑渐渐变坏的。23件，又要将你们的心志改换一新，第1步是脱去，就是心里面得画线，不是顺着丝与生活的。第2步是什么？又要将你们的心志改换一新。人能成事是有志向，有志者事竟成。没有志向的人没有力量。一个公司能做成的条件什么？公司创始人有没有制假？有志向就可以是一个我们总理能够当总理，周恩来总理能够当总理的原因是什么？
为了中华之崛起而读书，就有资格做总理。市场也是这样的，信仰的影响之下，我们信仰里讲志讲，事项就在你心里一个目标得树立起来，一个中心给树立起来。那志向什么成为心里的志向呢？我们不是自己创造，我们就效法，什么是微信的志向？来可以哥林书这么说，哥林多后书，可临到后书第5章克林多后书第5章。文章5章第9节。克林顿后15章第9届5章、9节、10节这两节，哥、林多后书、5章、9节10节。九届师姐说，所以无论是住在身内离开身外，我们立了志下要得主的喜悦，因为我们众人必要在基督台前显露出来，叫个人按着本身所行的或善或恶受报。
好的，第9节有些大家也非常熟悉了，纠结说，所以无论是住在身内离开身外，我们立了志向，要得主的喜悦，有志向是什么？志向？要得主的喜悦，又要叫你们心志改换一新，我们最初的心智怎么信是什么样的心智？我们肉体本来的性质是什么样的性质？怎么样让自己得益处，怎么让我怎么让我高兴？这是这样的心智，是这样的志向。像圣经里说要让你们的心志改换一新，不是怎样让我不是怎样让我高兴。我好不好？我高兴关系。第2个伸头，一个是什么？
要得主的喜悦让主高兴。怎么样煮才高兴呢？比方没有问题，找老师一个事情，要一个事情决定，就去找老师跟老师，交通老师怎么好，就这么问的时候怎么好，这么问的时候，你心智是怎样一个心智呢？这个怎么好？第一就是第1个志向就是第1个是什么？怎么能让我更好，怎么决定让我更好呢？让我更得益处，另外一个性质就是怎么决定主台喜悦呢？想得到是引导的话一定得挪过来，最新的志向是什么呢？让主喜悦，要叫你们心志改换一新，这个事项不是我高兴不高兴，这主喜悦什么呢？
主体什么？祝愿我怎样煮愿意怎样，好。我两个女儿，一个老大，女儿今年高三了，今年高在。时间过得真快，今年高三。再有4个月，就4个月还不到4个月了，不到4个月了，三个多月就高考了，再三个多月高考，然后回来，不能在一起，然后说考哪个学校考哪个大学，好哪个大学，然后康哪个大学考哪个专业，康乃大学考哪个专业，然后以后做什么？然后这么说，说了一会以后考哪个大学考太好的，但是考不上。好还好的姜。清华、北大有什么负担的，这些单都考不上案，新的成绩考不上，学习是很好，但是太高了，他们觉得考不上。
后边如果北京师范大学或者是什么这些倒是能考上，然后考哪个学校，说考哪个学校，考专业说了半天以后，到最后他不管，不说了就祷告，到时候再说，最后就这样看，实际上考哪一个，这样看点专业，考哪个专业，开始那么引导。自己心里面想了半天感觉都挺累的，感觉都挺累，这个就不说了，就祷告。看到时候实际上考哪个了？这个就是一个事情做决定的时候，我们决定的时候，第一决定就是怎样让我好，怎么让我好。中期是我或者是中心，不是怎样让我好，怎样煮，怎样决定主喜悦，想得到是引导的。第2个重要就是新的中心得树立好，不是我好，是主席也好，我好不重要，我高兴不高兴不重要，主喜悦什么呢？
主喜欢什么呢？所以又要叫你们心志改换一新志向，得换，又换成哪让主高兴煮起。如果让传到我就传到了，如果让公司有工作了，不让我开公司就开公司了，主让我冬季就种地了。让主喜悦。好主的喜悦。如果你看我做什么好，交给主让主高兴，这是最重要的点，有时能够很好的被水引导第1步就是什么呢？被拖去得舍掉生活。第2个是心智得定下来，让主体志向在心里定下来之下，这个志向非常重要。在新闻定好，这个志向能很好的被他引导志向重要。
在具象的心理处理起来了以后，如果要听你的，从那天开始真能引到我们了。要不然是你一直等着谁一直等着，等着我们心里边事项处理起来。我们很好地被使用的条件是造新城愿意了。如果愿意我愿意跟随你，我愿意把我自己交给你，我愿意跟随你的职业。这个这很重要，这就说限制现。甚至等于说所以弟兄们为神的慈悲，劝你们将身体献上，当作活祭，就是这个字了限制。把我自己献给你了。我们做什么？我说我要做做都很虚华，出于人的必要败坏，不是我要做什么事，把我交给你主，你要借着我做什么呢？
你要怎么使用？我是我听你的？这样都先交给他，他能自由的支配我们了。这样一个志向在心理学上树立起来。我说我们信仰生活不是我们自己发明什么，我是效法，效法，我们效法牧师、牧师这么说，牧师得救的书目诗书的话，大家可能都记得漠视得，就在神面前都是这样子，做了这样的祷告，不是祷告说，神太感谢了，你拯救了这样的我。肾如果有钱的话一定奉献，但是现在太贫穷了，我什么都没有。所以如果你不嫌弃的话，我就把我自己都献给你了。
你看怎么使用好就怎么使用，如果在蒙你的恩典，把我们用在福音的事情上，就太感谢不尽了。这是得救，一个牧师在神面前作的祷告，是你等就了这样的，我太感谢了。如果有钱一定奉献，我现在什么都没有，我太贫穷了。如果你不嫌弃的话，你就把我自己都献给你了，你看怎么使用好就怎么使用，如果在蒙的恩典把我们用在福音的事情上就太感谢不信了。这可以说咱教会的根基，这是根基这根筋，陌生的很好的背身使用的原因是什么？把我自己都献给你了。
都献给你了。就这样一个志向在心里处理起来了。不是我喜欢什么，你看怎么使用好就怎么使用，你看好你喜悦，就这样的志向在心里稳稳的矗立起来，无论是住在身内离开之外，我们立了志下要得主的喜悦，是能很好的被试引导的第2点。第2点那都是一步一步的，来差一点都不行。差一点的会讲。差一点的话你就等着。首先浪子得先回来，从心里支持回来，才能带来生活的变化！父亲改变了他心没回来之前，父亲只能等着。等着心归回主，归向主，心属于主。
第2点第3点是什么？来翻过来衣服做出再翻过来，第3点是4张，第3点就是。我重新读一遍，22件。以弗所书第4章一副走出4张4张22件，就要扑去你们从前行为上的旧人，这旧人是因私欲的迷惑渐渐变坏的，又要将你们的心志改换一新，还是4件，并且穿上新人，这信是照着神的形象到的，有真理的仁义和圣洁。24解说，并且穿上新人，鞍山市脱去。23节是心志改换一新达24解释，并且穿上去又穿上。穿上新人新事，怎么生活呢？
一些搜狐的生活，可以说我们的模范他是怎么生活的，它是跟随神的旨意生活，比如跟随神的引导，那么我们说保罗说我活着就是基督，我死了就有益处。相机都那么火，鸡都那么活，怎么活不是跟随我的想法，是为圣灵带领的生活送起来说怎么是揣上呢？这样穿着一定得寻求神寻瘦身的阴道，心里跟随神的旨意。所以第3步一定得寻求神。被求神。秦说是等候他的旨意，我和他的旨意，在心里面等候他的旨意，然后他的旨意给我，或者是不是圣领导人神奇的教诲引导了我，所以我活在神面前把自己交给他，然后他引导的时候，神奇的圣灵神经教会引导了我，我接触那个人往前迈步，穿上了。
但心里面这点很重要。每天常常来到神面前把自己献给他，甚至于说祭坛上的火常常烧着，就把我里面的私欲常常撇弃了以后，把自己交在神面前，摆在神面前，然后等候着他的引导，等不了他的旨意纯洁，记得圣灵或者教诲一定引导我们的心，甚至引导一旦来了以后，我们心里就了新的新ui这么过新的生活。所以我偶尔会这么说，觉得他现在这么得就这么多年过，后来我感觉得救的时候，就新改变的时候，在单位里面心改变了以后，时间神推是做了很大的工作，我说新改变了以后，之前随别生活了。
咱99年4月今年4月4号得九以后2000年1月份我心里过得特别痛苦，然后住去参加像会他乡会心改变，那时候心里定义把自己都献给神了。所以每天在单位里面每天做的事情就是吃完晚饭以后一定做的事情就是在路边这么走着，走着抬着头跟神祷告。所以我今年27岁了，说你看我这一生怎么过好呢？生怕以后的余生都交给你了。你让我过什么生活，我就过什么生活。生我愿意借给你。你是我的主人了。然后就那样跟神祷告者，他一两天、三天、一个月两个月，然后一个多月快两个月的时候，一天发工资。
发工资的时候，然后那天我就没有去领对面他去领工资，我就说把公司替我领回来，那么公司领了给我。可以了，婚以后装起来。就这个过程里边，我抓起来以后，我就没问他还多少钱，也没问他开多少奖金，然后也没有在意我到底开多少钱，给我以后就揣到兜处理了，那1000多块钱就揣到兜里了。就看见她了，我就一点没有在一个地方开多少钱，对方多少奖金，就那一刻我心里一下子感觉到了，我现在真自由，我原来那么在一地方开多少工资，我开多少工资，地方都要奖金，我多少奖金？
经理发多少钱，我发多少钱很在意，现在我一点都不在意了。我心从前的捆绑你完全脱离出来，我现在过的太次也有了，就在那一刻，我心里面突然就领会了，就领会了，对人生该怎么过就得这么过。当人把自己都交给谁，以后，谁会带这么过自由的生活？任D里得救，但光阁就不行，必须得他指责就绝对不行。第2步一定是把自己献给神，神称我心的主人，他就会带着我脱离一切的捆绑，他能带领我我新的生活，我心里就特别的感谢了，我就感觉我所领悟的非常大，领悟的不是我伟大，领悟的真理非常伟大，就一定得这么生活，从那以后就不想工作了，就很想去传达了，我是每天坐在办公桌，后面的时候心就感觉好像要特别浪费时间，就感觉每天在干什么，这么宝贵的回不去船干什么，就很想去传道。
所以那个时候说协会我还有三个月就定值了，一定去以后公司就会翻倍，然后奖金会翻倍就能挣3000多了，2000年4月到7月就能挣3000多了，然后说以后结婚，我们是现有单位结婚给分住房，然后怎么给补贴，一定是以后再过一段时间就能当小官了，当一个小公司一个副经理或者一个总工等等，然后慢慢就能当官了，然后以后可能很会挣很多钱，想以后可能会很发展，但当时在我心里这一切好像不是好像保罗说我看万事如粪土，在我心里面真就是粪土一样，就那么不在意，全都撇弃了，一点都不在意。
怎么会有那么好的心，但当时就是那样。一点都不在意，什么都不在意，然后只清楚神的质疑求着，然后是引导了我的心，给了应许深刻的应许，然后去把一切都放下来，就传到有时说穿上把自己都献给谁，以后谁会借着圣灵引导型的神给我们新的所以新代理们过新的生活，所以重新来整理，所以来整理，我们时间到了，重新再整理，我们都是叫的，只是开始的。在前面比讲什么都重要的是我们生活更重要，生活更是重要的。言教不如身教胜于言教。
弟兄姊妹看着我的生活来跟着我们别过生活的，实际上我们说话有能力，而且生活说话的本身，那个话里面神就做工神经会使用我们。那么生活叫三点，第1点就是脱去舍掉私语。第2点就是心志改换一新。第3点就是穿上，有的人有脱去，过去没有跟这厮一过，好像很清洁，但没有穿上，里边没有得到圣灵的引导，然后拿着自己律法的心，感觉自己过得很好，然后拿着律法的心说别人，然后就是不行，脱去，站在神面前被圣灵引导。这三样我们心里面按照顺序走下去的时候，就能把因素能彰显出来。
别人看着我们的所能够树立，能够跟随，就很好，能讨主喜悦。总之今天晚上有一次讲话的时间跟大家讲了这样的部分，按照顺序上讲过来，真帮助我们在新的一年开始了。现在疫情很快过去了，郁庆一过去以后我们就能见面聚会了，我们现在网上也在传着道，很快就开始干活，开始做干的事情了。在比一切都重要的是在我们心里面这三个点，或去心志改换一新，关上之后将神彰显出来，那样话是能很好的适应我们。吧好了，就说这些就说到这里了，有一次讲话的时间有这样就很感谢了，好，李牧师交给你了。
说到这里，好吧？特别感谢。
