= 信仰的三个阶段
李光辅

.马太福音 26:31-35 和合本
****
那时，耶稣对他们说：「今夜，你们为我的缘故都要跌倒。因为经上记着说：
我要击打牧人，
羊就分散了。
但我复活以后，要在你们以先往加利利去。」彼得说：「众人虽然为你的缘故跌倒，我却永不跌倒。」耶稣说：「我实在告诉你，今夜鸡叫以先，你要三次不认我。」彼得说：「我就是必须和你同死，也总不能不认你。」众门徒都是这样说。
****

.马太福音 26:69-75 和合本
****
彼得在外面院子里坐着，有一个使女前来，说：「你素来也是同那加利利人耶稣一伙的。」彼得在众人面前却不承认，说：「我不知道你说的是什么！」既出去，到了门口，又有一个使女看见他，就对那里的人说：「这个人也是同拿撒勒人耶稣一伙的。」彼得又不承认，并且起誓说：「我不认得那个人。」过了不多的时候，旁边站着的人前来，对彼得说：「你真是他们一党的，你的口音把你露出来了。」彼得就发咒起誓地说：「我不认得那个人。」立时，鸡就叫了。彼得想起耶稣所说的话：「鸡叫以先，你要三次不认我。」他就出去痛哭。
****

神引领我们的方式，我们理解不了的很多。这次因为疫情的缘故，大家都在家，休息很多吧。

圣经里面说了安息，那么安息的反义词是什么？安息的相反的意思是什么意思呢？有的说是劳苦，有的说干活什么的，实际上不是这些。真正的安息是什么时候被破坏呢？亚当和夏娃堕落之前，也有干活的，现在也有干活的，干不干活不是安息的标准。

看不见神与我们同行，如果神与我们同行的话，再难的事情实际上不会给我们带来压力。神实际上没有让我们做什么事，我们以自己为中心，离开神以后，神一句一句全都是针对我说的，以为是让我们做什么，所以很累。

在《约翰福音 6章》里面耶稣对腓力说，他他给众人买饼，男人有五千，所有的人加起来有一万多。耶稣对腓力说“你们给他们吃的东西吧”，刚开始腓力研究很多，计算了很多，最后他的结论出来了：“二十两银子也不够”，很累。圣经说了耶稣原知道怎样行，耶稣有计划，向着腓力说的：“你们给他们东西吃”。

== 第一个阶段：认识自己
针对我们的信仰，今天我想说信心的三个阶段。

第一个阶段是**认识自己**，罪得赦免重生的秘密；第二个阶段是**信心生活的秘密**，我们得救了，下一步怎么过日子呢？在这里，腓力跟从耶稣，当然是已经得救了，但是遇到问题还是自己要解决的心，也就是说他还没有发现自己。

信心的第一个阶段，“啊，我不行啊，我做的不行啊”，发现我是不行的一个人，我做的话都不行的，发现这个的人，信仰成长很快，我做的不行。

我有一次我们的牧师对生活的发现已经很清楚了，有一天他和一位姊妹的丈夫沟通，回来以后对我们说
[%hardbreaks]
“那位很聪明，我从来没没有见过那么聪明的一个人”
“怎么了，牧师”
“如果是我给那位传福音的话，需要二十年才能得救。”
“这么厉害呀？”
他说二十年沟通也够呛，牧师是这么说的，但是第二天回来的时候，牧师说那位得救了。
“嗯？你说二十年不是吗？”
“啊”
牧师的意思是什么呢？我跟他沟通需要二十年，所以他“我已经不行了”，那么谁做可以呢？耶稣出现，跟他沟通，一天之内得救了。意思是这个**我沟通的话需要二十年**，仆人的生活里面特别清楚的是什么？**我做的和耶稣做的很清楚的划线**。

如果是我们，遇见环境的话怎么做？我们里面马上出来的是，自己要解决。腓力是什么样的人呢？还没有发现我做不行，这个阶段还没有过去。得赦免了，得救了，这个已经明白了，但是还不知道自己的肉体的力量是多么大的。

罗马书7章，保罗一直说“我是想行善的，但是行出来由不得我”，后来看，我里面有一个罪的律把我拽下来。

[quote, 罗马书 7:18 和合本]
____
我也知道，在我里头，就是我肉体之中，没有良善。因为，立志为善由得我，只是行出来由不得我。
____

7章一直说罪的问题，罪的担子也很多，后来感谢耶稣，耶稣把我从罪的里面拯救出来了。到了8章开始说圣灵和肉体的两个世界。生命圣灵的律，在我们里面圣灵也进来了，但是的肉体也存在，这两个世界征战的阶段。我们信仰生活的时候，首先需要知道我不行；我做不行的话，谁出来？圣灵做工。
[quote, 罗马书 8:2 和合本]
____
因为赐生命圣灵的律，在基督耶稣里释放了我，使我脱离罪和死的律了。
____

靠着圣灵治死身体的恶性，我们能靠着应许打破想法的世界。
[quote, 罗马书 8:13 和合本]
____
你们若顺从肉体活着，必要死；若靠着圣灵治死身体的恶行，必要活着。
____

=== 疫情

这次疫情，我们四位弟兄姊妹得了这个病，确诊住院。一个弟兄一发现的时候就确诊了，我每天和他通电话，还有和湖北地区一起开会聚会，真的听了不少的话语吧，每天都讲话语，这是什么意思呢？靠着圣灵治死身体的恶行。在我们里面不是因为疫情受伤，我们里面想法很多，这些想法就是折磨我们。没有病的人心里也是难，靠着圣灵治死身体的恶性，当话语一个一个的进来，这些想法全都飞走。所以看湖北地区的弟兄姊妹发展很多很多，虽然在家也是，聚会很堵，靠着圣灵治死身体的恶行，所以我们现在说：“我做的不行”，我们没有话语也不行，这次拿着花语都恢复过来，三位已经出院了，还有一位在医院里面，他也是恢复了很好，需要医生需要药，但是真正需要的话语，通过话语我们能战胜想法。

== 赶鬼

刚才说：“发现我做的不行”，我虽然是牧师也是，常常出来我的血气，还有我要做的。

我在海尔滨的时候，有一天接一个电话：“牧师呀，我妈现在鬼上身了，你来吧。”

TODO 16:30


== 第二个阶段：求神

发现我不行，第二个阶段是求神，我跪下祷告，“神啊这个怎么做呀？你来做吧”，祷告，求。大家，我们真发现自己不行的人，不能不祷告。

== 第三个阶段：

.马可福音 11:25 和合本
****
你们站着祷告的时候，若想起有人得罪你们，就当饶恕他，好叫你们在天上的父也饶恕你们的过犯。
****

已经祷告的话，相信神已经垂听，已经得到了；祷告的话，还在求的位置，这个是假的意思。我们这个阶段现在很难的。

自己不行也知道，求神也能知道，第三个阶段，你祷告的话，现在说什么话呢？
[%hardbreaks]
“你完全吗？”
“不完全”
“你是大能的勇士吗？”
“不是”

在我们里面呢，心常常停留在这个里面。
TODO 27:40
