= 苦难是基督徒得荣耀冠冕的前奏曲
李光辅牧师

有能力的，可以说摩西是以色列人的国父的存在。所以他们一直相信摩西，一直相信摩西传给他们的律法，他们是这样生活过来的。

有一天他们遇见耶稣的福音的时候，『啊，摩西不是神的儿子，他是听使唤的，在神的家是仆人的级别。那么来的耶稣是谁呀？不是奴仆的身份，他是堂堂的神的儿子。』

很多人以为摩西是最大的、最伟大的，亚伯拉罕也是最属灵的；但是，耶稣基督来到世上以后，他们看起来不是最大的，实际上他们是为了来到世上神的儿子而预备的。他们是预备工作的人，是（耶稣基督）模型的存在。所以希伯来书给他们写这样的部分，但是很多人心里面留下的是『难道你比摩西大吗？难道你比亚伯拉罕大吗？难道你比大祭司长大吗？』，所以他们有点模糊不清的也有，所以他们当然不接受福音，还有逼迫信耶稣的人。所以希伯来书给谁写的？本来新犹太教的，后来他们，也可以说改宗把，接受福音得救的基督徒，那么他们为什么需要这样的话语呢？虽然得救，他们挺高兴的，但是得救的基督徒里面进来了圣灵，撒旦能不能帮他们？不帮他们，一直逼迫，还有威胁，而且犹太教的人会问：『你们为什么离开？难道我们所相信的都是假的吗？那么你们所相信的是真理吗？』他们的心里面一直有这样的部分，所以他们的生活也是很难，有很多人有点摇晃：『我们干脆信犹太教得了，信耶稣天天受逼迫，做买卖也是，他们不想和我们交易。很多方面，孩子们上学和交往也被孤立』，所以他们心里面摇晃，保罗知道这些，所以给他们写信了。

所以罗马书里面说就是，你们为什么受逼迫的原因，我一个一个给你们说明吧。

== 没有负担会被淘汰

刚才我们也说了，没有冬天的国家，平安而且舒服，没有什么负担，但是问题是什么？适应环境的能力很差的缘故；还有，动物当中没有天敌的动物呢，慢慢慢慢淘汰。新西兰有一种鸟，名叫 kiwi 鸟，在新西兰那里没有蛇，也没有攻击他们的鸟，真的他们以为这是天国呀，特别好的环境，但是慢慢他们就是淘汰了，飞不起来了，因为不用飞了，地面有很多粮食，他们享受这个，慢慢的他们没有了飞的力量，所以一个一个都被淘汰了。

神给我们的恰当的苦难，恰当的难的事情，是真的帮助我们的，这是祝福我们的一个条件的意思。身体也是，太平安的话，我们的肌肉呀，我们的免疫力也是，会很快的下降的，但是有环境的缘故，我们敌对，逆着环境生活，我们的逆境指数会提高，然后我们里面，肌肉啊，很多部分也会健康起来。

== 倾听穷人家孩子的说话

所以犹太人有个智慧书里面有这样一句话

[quote, 犹太人智慧书]
____
你倾听穷人家孩子的说话
____

听懂了？倾听谁的说话，听『穷人家孩子的说话』，因为他的话里有智慧。他家里穷的缘故，比起富人家的孩子的话，思考的部分会很多，还有耐心也很多，越过很多难处过来的缘故，听他的话里面有很多智慧话。

前年吧，有**感谢贫穷**，网上很轰动的一句话。谁写的？有一个北京大学的学生，他考上北京大学以后，这是他写的一篇文章。因为他家里非常穷，所以爸爸到远处打工，他和妹妹和妈妈一起在家，妈妈一直干活，爸爸虽然打工，也是挣不了多少钱，所以他们穿的衣服都是旧的，妈妈到叔叔那里得到的，洗完以后留给他们穿上。孩子们喜不喜欢呢？当然不喜欢。我小的时候，也是穿哥哥长大了，小了的衣服，我上边有两个哥哥，一直穿不到新的衣服。他是这样，但是妈妈对他们的教育不一般，妈妈说
[quote, 为什么穿衣服]
____
衣服不是为了漂亮的缘故穿，那么为了什么穿呢？为了遮盖太阳，也遮盖外面的温度，所以为了保温的缘故穿。这个不好看也可以，不是为了给别人看的，所以安静，合适的话就可以了。
____

真的和刚才说的差不多吧。听谁家孩子的话？穷人家孩子的话，他里面有智慧的话，所以他说，他这样努力学习，他常常没有什么可吃的，出去外边，山上野地摘水果吃，所以他真的享受自然。还有妈妈接送的时候，妈妈骑自行车，他们一起来回的时候，和妈妈沟通的很多，所以他成绩也好，上北京大学了，然后他写一篇文章，感谢谁？**感谢贫穷**，真正的有一句话出来。

在我们基督徒也是一样的，我们生活当中遇见很多环境，这里也说，耶稣
[quote, 希伯来书 2:7 和合本]
____
你叫他比天使微小一点（或译：你叫他暂时比天使小），
赐他荣耀尊贵为冠冕，
并将你手所造的都派他管理，
____

耶稣基督也是，他暂时在哪里的位置啊？比天使还低的位置。天使还高，耶稣基督下到最卑贱的位置。然后他受苦，一直受逼迫，终于呢，犹太人把他钉在十字架上。**为什么他作为神的儿子，受到这么大的苦难呢？** 所以《希伯来书》告诉我们，为什么受到那么大的苦难呢？

== 天劫余生

有一个电影《天劫余生》，1972年一个乌拉圭的橄榄球队45个人，坐飞机去参加比赛的时候，飞机故障掉在安第斯山脉，45个人都是运动员和乘务员，掉在山上，零下40度，大家带过没有零下40度的天气？他们真的特别特别冷，没有房子，没有食物，呆了72天。他们很痛苦吧，能吃的东西都吃掉了，后来他们就吃什么？吃人肉，因为没有别的可以吃的了。

有一次我们在美国开 IYF 世界大会的时候，邀请其中一位幸存者，他给我们演讲。他把当时的情况都说了，在后面的问答时间的时候，有人提问：“45个人当中，存活下来的是16个人，这16个人现在都在干什么？”，答：“他们已经是各个领域的领袖了。有的人是总统候选人，有的是国会议员，大夫，记者，反正在自己的领域里面都是成功的人。”

他说的意思是什么？经过这个事情以后，他的生活当中，再也没有难的事情，都是很简单的事情。因为什么？因为他们已经下到人的极限的位置，吃人肉的程度的话，他们真的已经达到极限了。回来以后，当然他们也会遇见很多环境，但是在他们的眼里看，都是很简单很简单的，所以他们能把所有的环境都越过去，成为各个领域最领袖的位置，都是成功。

== 神给我们的苦难，不是咒诅的意思，祝福的意思

神给我们的苦难，不是咒诅的意思，祝福的意思。所以通过这个苦难我们接受

[quote, 提摩太前书 4:4 和合本)]
____
凡　神所造的物都是好的，若感谢着领受，就没有一样可弃的
____

神所造的都是好的，所以我们心里面不要以苦难接受神的话语，根本不是苦难，以感谢的心领受的话，没有一样可弃的。所以我们学的是什么呀？基督给我们的都是正能量的，她给我们的是感谢，所以常常喜乐，不住的祷告，凡事谢恩。遇见环境面前，我们拿着谁的心对待环境。所以我们查看的话，神把耶稣也是掉到**比天使微小一点**，不如天使的位置，还有受到很多人的欺负、藐视，终于他被钉在十字架上。

为什么？神这里已经准备好了，赐他荣耀尊贵为冠冕。向着西伯来人，得救的基督徒，当时还没有形成真正的教会。有教会的话，一起交通，一起交流祷告，他们得到力量，但是连这样的条件都没有，所以很着急给他们写一封信，就是《希伯来书》了。

因为我们里面有圣灵不是吗？但是希伯来圣徒不太清楚，所以遇见环境的话就是：“我们为什么遇见遮掩过得环境？神撇弃我了呀”还有神为什么不祝福我？

以为我们得救以后，好好过，灵魂也祝福，物资也祝福，身体也祝福，很多人追求的是三拍子祝福，都好，灵魂也好，物资也丰富，身体也健康，要的是这样的。

但是在神的世界里面不是这样的。因为我们里面临到圣灵，圣灵来到我们里面，空中掌权者的是撒旦，他看耶稣基督的圣灵，还是基督徒起来，不听他的话，只听耶稣基督的话，撒旦不能不攻击我们。很多人以为得救了，苦难、环境都没有了，好好休息吧，这是错觉的。世上的没得救的人常常这样说，“信耶稣吧，都好，一帆风顺”，骗人的话是这样说的，实际我们得救，耶稣也是到比天使微小一点的位置。还有他也是受了很多苦，目的是已经为他准备好的荣饶与冠冕。

== 大卫与所罗门

我们看旧约圣经，大卫和所罗门有什么区别呢？大卫先通过苦难锻炼，然后再当王；所罗门，借父亲的光，什么也没做，父亲都做好了，金、银、铁、铜，用这个建造圣殿，所以他的国度只有一代就堕落了。如果所罗门也是经历过苦难的话，不可能他娶一千个妻子，跟着外邦女子的风俗习惯走。而大卫王是跟着神过。

就像前面所说的，**你倾听穷人家孩子的说话**，因为他那里有智慧。大卫真的受了不少苦，真的很难的生活。我们看大卫一天一天也是想脱离，“神好像咒诅我呀，神为什么给我这样的环境？”到处有敌军，到处有追赶他的。后面我们知道大卫的人生，五十来年一直当王，国家也是很稳定，大卫一直拿着神的心管理着国度。

真的神为大为准备的是什么呢？在夜色列百姓的心里面留下的是什么呀？大卫王。我们读圣经的时候，很讨厌不是押撒龙，示美呀，这么好的环境他只能享受肉体。没有经过苦难，没有苦难给他准备冠冕，准备荣耀。神通过耶稣给我们看的路，神向着我们也是一样，在地上我们不要享受所罗门的荣华富贵，我们羡慕大卫的，瞬间瞬间不靠着神不行，瞬间瞬间求神，靠着神迈步。神领着他，通过他彰显神的荣耀，他自己蒙了多大的恩典。以色列百姓，周围国家也是都惧怕大卫，因为大卫不靠自己，靠着神生活。

== 约瑟

还有一位通过苦难得荣耀的，
25:24