= 两个儿子的未来

TIP: 有一个先知门徒的妻哀求以利沙说：「你仆人－我丈夫死了，他敬畏耶和华是你所知道的。现在有债主来，要取我两个儿子作奴仆。」以利沙问她说：「我可以为你做什么呢？你告诉我，你家里有什么？」她说：「婢女家中除了一瓶油之外，没有什么。」以利沙说：「你去，向你众邻舍借空器皿，不要少借；回到家里，关上门，你和你儿子在里面将油倒在所有的器皿里，倒满了的放在一边。」于是，妇人离开以利沙去了，关上门，自己和儿子在里面；儿子把器皿拿来，她就倒油。器皿都满了，她对儿子说：「再给我拿器皿来。」儿子说：「再没有器皿了。」油就止住了。妇人去告诉神人，神人说：「你去卖油还债，所剩的你和你儿子可以靠着度日。」
(列王纪下 4:1-7 和合本)

因着新冠病毒，国家面临着危机，尤其是被传染的人的心里面特别的困难。还有，这个病要赶紧好，担心着，如果不好该怎么办；也担心，万一死了怎么办。

当然除了新冠病毒以外，在我们人生当中往往会有突如其来的问题，我们信神的原因是什么呢？去买汽车保险的人，不是因为出了事故去投保，而是因为有出事情的可能性的缘故去投保，想要得到资金上的资助，当然信仰与福音与这个不一样。

但是我们不能因为平安就代表没有问题。还有遇到问题时，为了我生活的人，和为了神生活的人不一样。在我得救之后，在我的朋友当中，去看我的同学的话，有很多的人当然生活比我更好，但是当他们遇到问题的时候，看到他们完全没有路，没有方法。但是我与他们不一样的是什么呢？主与我在一起。不是没有问题，而是即使遇到了问题，看到神帮助我的手特别的奇妙。

我在今天早晨看着《列王纪下》话语思考的时候，我想到这门徒的妻子，他的丈夫死了之后，和两个儿子一起生活。如果是对现在的人来说的话，可能是做生意借了债不知道怎么样，她面临着必须卖掉两个儿子才能还债。在圣经里面，无论是什么原因，这个妇人有债。**在这面前，有神和没有神，完全是田地之差**。

我生活过来，遇到过很多问题，但是神帮助我的事实是无法忘记的。

我在大邱波洞，第一次去那里的时候，我的一家人全吸了煤炭的烟，那个时候那个地方所有的人家都烧煤炭。那个时候，我家的煤炭的烟泄露，没有人知道，我也是不断的搬家的缘故，所有很劳累，吃完晚饭我睡着了。我的女二，在那个时候大概两岁差不多吧；我已经睡着了，但是我的女儿在那个时候突然放声大哭，我那时实在是太困的缘故，被她惊醒，我很嫌烦，就问妻子：“为什么让孩子哭呢？”，我的妻子说她毫无理由就哭了。重新拍她，她就睡着，但是睡到夜晚，这孩子又是嚎啕大哭起来，我就开始真的烦了，对妻子说：“她为什么哭呢？”妻子说：“没有理由她就哭了”。开灯也是，什么问题也没有，我的妻子站起来想要去一趟卫生间，她打开房门，有凉风进来，她就直接摔到了，吸了煤气的话，呼吸新鲜空气就会晕倒。那个时候我心想“原来我们在洗着烟那”，怕她再摔倒，我就把她推到一边，我就喊叫寻求帮助。在我的隔壁有个租户，他马上跑不过来，他是我不认识的一个邻居，我跟他说，她还想是吸了煤气，他就把我妻子赶紧带到他的房间，铺了被子让我们在那里睡觉。第二天早上，他知道了我是牧师，我给他传福音，他得救了。我特别特别的感谢。

我偶尔回过头来思考，为什么当时恩姝哭呢？如果当时不哭的话，我们一家三个人在第二天肯定会成为尸体。我想是神帮助了我，保守了我，特别的感谢。在当时看新闻，总会有那么两家死于煤炭，在那天晚上，我听着恩姝的哭声特别嫌烦，但是看到神帮助我的时候，特别特别感谢。如果让我做这样的见证的话，真的是没完没了。真的是熬着夜讲也讲不完。

在苦难的时候，在我困苦的时候，在我伤心的时候，在我心里给我力量的，指引方向的神，引领我。

在1976年我开始宣教学校，每次祷告的时候，神赐给我想要开宣教学校的心，这样祷告。以前我最讨厌的就是开宣教学校，我心想像我这样的人办什么学校呢？我真的做不好，以为神已经忘记了，但是神又给我开宣教学校的心。我有一个我妻子的舅舅，他因为没有钱去了英国，到了英国见了英国的女王，他说他是第一个被女王亲吻额头的东方人，然后回到韩国，他开办了韩英圣书公会。就这样，他还活着的时候，我就去找上了他，我说舅舅你好，就这样打了招呼。因为我找上他，所以有点意外，我就这么说：“我想开一个宣教学校”，我就跟他详细讲了开办宣教学校的打算，他就安静的听了下去，最后我就说：“要不要和我们一起做呢？”，他是我妻子的舅舅，他看了我之后说：“哇，你怎么能想到做这样的事情呢？你的想法真是太好了，不知道你怎么能想到做这样的事情呢，真是太好了。”“我会帮助你，但是你也知道我的年纪已经老迈，哪怕我再年轻十岁，我也想跟你在一起，但是我只能帮助你，如果我融入到你那里的话，我怕耽误你，那你就努力做吧”，他就把他读过的书给了我一箱，都是我没有读过的书。

就这样开始宣教学校的事情是难以想象的。那个时候大概有20几名圣徒，向着他们说我想开办宣教学校，他们就大吃一惊。
[%hardbreaks]
“宣教学校是什么样？”
我就向他们说：“是培养宣教士的”
“在哪里呢？”
“就在礼拜堂。”
“那吃什么呢？牧师，你自己都挨着饿”

但是 1976 年就这样开办了宣教学校，现在在全世界有力传福音的都是我们宣教学校出身的人，在当时谁看也是简陋朴素的。金东成弟兄在高三来到了宣教学校，他的母亲离世，后来继母进了家门，他的父亲也离世。金东成的母亲让他上了商业高中，一般那所学校毕业的话都会去银行，他在这如此困难的家庭里，毕业以后没有去上班而是来到了宣教学校。他的母亲特别伤心就来到宣教学校里，打开了一楼的门，这些学生们都紧张起来，就那么几个学生，我看见那位奶奶特别的气愤，说：“我的儿子学习好，特别困难的学习毕业，我就等着他能够在银行上班”，总而言之，就是这样我们开始宣教学校。

在全世界宣教会里引领全世界宣教的re都是我们好消息宣教会毕业的人，无论是哪个国家，我们都掌控着全世界的基督教，真是难以想象的事情。我开这个宣教特别让我喜欢的是什么呢？无论是下雨还是下雪，只要吃完早饭的话，就有宣教学生在等着我。打开圣经，在讲道的时候，我的心里面开始与话语亲近，我的心浸透在话语里。在我传福音，也有得救的圣徒，明明因着同样的话语得救，有的人感激，不知道怎样是好，但有些人“哦，得救了吗？”就这样很平淡，这样的人不一样。明明都是靠耶稣的宝血得救，有的人走向肉体，有的人跟随自己的欲望。在宣教学生们当中也是，有些人有真正爱主耶稣的人，甚至我看的时候都有些惭愧，因为比他们我更不如。有些人真的让我难以抬头，有很多这样的宣教学生。

今天南都迅弟兄做了见证，他是一般普通公司的员工，他说他毕业了玛哈念神学院，我在毕业典礼的时候听了他的见证。我就心里想：“这个人怎么能拥有这样的心呢？这个人怎么能有这样的心在他心里产生呢？”他在上着班，每天晚上熬着夜去听话语、学习、写论文，真的是很不容易啊。当然从神学院毕业的人，并不都和南都迅弟兄一样，人都会改变，无论是谁人都会改变，跟着时间过去、环境改变、生活改变，就会变化。我们也无法责怪人们改变，因为神创造了就是让人变化。当然有的人从坏往好处变化，也有的人从好处往坏处变化，能够看到神的恩典，神的路在他里面。

在 1962 年，我特别特别的困难，但是在那个时候我向着神不知道多么的恳切，我得到了罪得赦免。在我们家里有一只鸡，我们无法吃它，因为还有靠着它下蛋。每二十个鸡蛋报过去来，就到了菜市场，放在路边上卖。当时就是靠卖鸡蛋的钱，买火柴，买肥皂，很不容易买一些粮食；因为卖了鸡蛋，所以只能喝粥，生活真的很不容易，也常常挨饿，但是在那个时代，那个时候，我真的想好好的生活看看。我想了很多的想法，但是再怎么想也是没有方法能够脱离贫穷。我也试了很多的方法，但是最重要的是没有希望。在 1962 年的时候，最满怀希望的去考技术学士的事情，但是在落榜的时候，我开始失望。我就开始拜托军医官，能不能通融一下呢，他说为什么总是这样呢你？等国家义务招你的时候再去吧，我就说：“求求你帮助我吧”，他就说“我想帮你也帮不了你，你碎的是门牙，又不是臼齿”。不知道我是多么的期待这件事情，那时候我的门牙也不是碎了很多，只是一点点，真的没有想到我会因着这个事情我会失败。为什么我就不行呢？别人都行，为什么就我不行呢？我的前生到底是犯了多么多的罪？我就这样想。

在 1962 年 10 月 7 日就这样得救。哪怕是现在重新回顾起来，非常的感激，我的罪得到赦免，我想为了主做点什么，我也想奉献。但是过了一个月，过了两个月也是，哪怕十元钱我也没有捡到。那个时候哪怕去偷钱我也想去奉献，有这样恳切的心。但怎么能去投钱呢？不是吗。那时候我常常唱的歌就是：“哪怕用眼泪也无法还清的主的恩典，只能献上这身体” 当时经常唱这首赞美，那我就想了，我要把我的身体献给神。我的身体连这下士军官也不要的身体，哪里有什么用呢？那时候我发现我的身体也是一无是处的人。因为那时候是625事变之后，没有地方能够找到男人，我们村子也是很多家庭是没有男人的，有的人家因为地炕裂了，只要烧火的话整个房子里都是烟，但是我就想到了这个点子来，我虽然别的做不了，但是可以修别人家的地板还有天花板。我就想象了，我先去一个奶奶的家，我看见她的家在漏雨，把稻草重新捆起来给他换一个屋檐，我就跟奶奶说：“奶奶，我修好了，你就住吧，能给我喝一杯水吗？” 就这样喝完一杯水出来了，想象了这样的我，特别的高兴。“阿姨，已经把地板修好了，你就尽情的烧火吧，房子会很暖和的” 就这样喝完一杯水出来，非常的幸福，光是想象也是。我心想这件事情我应该能够做到。我老了之后，也是能够给别人修房子，能够喝杯水喝，我感觉就是这样生活也是很幸福。什么当牧师，从来没有想象过，什么福音传道者也是从来没有想象过。

因为我舌头短的缘故，我的发音不好，我的妻子经常嘲笑我说不来四十三年这个发音，只能说四四三，我从来没有想到我会成为牧师，但是因为神打造我，像我这种人也成为了牧师。在我牧会的时候，我什么都不知道，有的时候现在我重新回顾以前，我想我怎么成为牧师了呢？我居然成为了牧师。有的时候我也会自问：“你算是牧师吗？” 有的时候我和圣徒聊一聊的时候，有的圣徒呢，居然爱耶稣比牧师更爱。在这样的人面前，我完全是无地自容，这位弟兄为什么能够如此爱耶稣呢？这位姊妹怎能如此爱耶稣呢？怎么能拿着这样的心生活呢？有的时候让我感受这样的部分的话，如果这样的弟兄姊妹对我说：“牧师啊” 这样的话，我就自问：“你还算牧师吗？就你这样怎么还能算牧师呢？” 真的有这样的弟兄还要姊妹，让我特别的幸福，也是特别感谢。

我们培养了很多传道士，虽然都是传道士，但是他们都是各从其类的。也有在背后撒谎诽谤的，如果都是那样的当然不应该继续办宣教学校了，但是我们没得聚会的时候都有同样的过程，开始的时候都很困难，心里面也有想法，还有继续办这样困难的事情吗？是不是不办呢？怎么这么难呢？

开世界大会不知道多么的难。财政也困难，真的是处处困难，但是到结束的时候不知道多么的好。话就变了，“为什么不办这样的活动” 所以每年都继续办。每次开始都是太困难，虽然是笑着，但是神在目前所做的事情当中，从来没有哪件是失败的。

我输了要办 CLF，弟兄们不管说什么都说不行。我们刚开始举办 IYF，然后办短期，因为我们教会大学生没有几个，在招募短期的时候，延续了一年两年短期的时候，我们教会的大学生都去完了，所以我们说招募一些教会以外的人去短期吧。有的人说：“谁回来呢？” 就这样我们第一次招募了宣教会以外的大学生，在截止日期的时候，我在 KaCall 大概中午 12 点的时候，有 100 个 200 个人报名，但是到了那一天晚上的时候，有很多的报名，能够听到那个声音，到了晚上 12 点报了多少人呢？已经超过了 1000 个人，1300 个人，1400 个人，我记得不清楚了，我心想是不是出故障了，怎么会发生这样的事情呢？到目前为止，每一年好几百个人都派遣到国外。

我们这次归国发表会，在弟兄姊妹面前做了表演，我哭了很多。我想，到了这个时代怎么还能有这样的孩子们呢？我呢，听到泰勒说他在印第安村子里长大，尝试了很多次的自杀。但是宣教士们呆了这些印第安的孩子们参加了纽约的世界大会，他们参加了世界大会之后，本来完全不知道对话的人，刚开始完全是只顾吃饭生活的人。但是泰勒这次来到韩国，完全改变，让我怀疑他是不是印第安的村子里的人，他面孔充满了喜乐，他本来是每天打架的黑暗的人，他个子也高，长得也帅，他现在成为特别可贵的人。他本来是无法融入我们当中的人，现在完全的融入，是有在我们以上的力量在我们里面。

**朴玉珠牧师是朴玉珠牧师，但是在朴玉珠牧师里面有一个除了朴玉珠牧师以外，有一个力量活着。** 在得救的弟兄姊妹心里，无论是怎样的弟兄姊妹，无论故去他是怎样的一个人，但是现在有一股力量在他们里面活着。这个力量和诱惑我们的魔鬼（征战），在《使徒行传》五章里有亚拿尼亚和萨菲拉，他们藏了钱，彼得说：“亚拿尼亚呀，撒旦充满你的心，你卖了的钱，你需要就向着神说嘛。你不是向着人撒谎，是向着神撒谎。”当场亚拿尼亚和萨菲拉就死了，看了这样的圣经我无法理解。如果朴玉珠牧师向着一个没有奉献的人这样说的话，如果一个人死了，我想没有一个人会来教会。那么为什么彼得只能杀了亚拿尼亚和萨菲拉呢？必须让他死呢？真的理解不了，但是有很多弟兄姊妹们卖了全部家产奉献，但是亚拿尼亚和萨菲拉隐藏了卖地的钱，我反复思考了很多。

如果亚拿尼亚遇到了困难的时候，他肯定会用上这次隐藏的钱，或者是儿子生病了，如果他们因为都奉献了，所以没有钱，他如果找到了隐藏的钱之后，会觉得我真有聪明，真智慧呀，我感觉会产生很奇怪的气流在教会里面，向着黑暗，撒旦的力量会强烈的作用着。在我们每一个人的心里，让各位陷入黑暗、罪恶，无法凭着信心迈步，在基督教的历史当中敌对教会的人在教会当中一点也不奇怪。在基督教的历史里，基督教的引领者是怎么死的呢？都是教会里面的人告发，很多人被撒旦欺骗，认为自己聪明，敌对教会。我不知道他们被什么欺骗，撒旦如此狡猾，即使得救的人也是，刚开始虽然被神引领，但是又会陷入撒旦的声音里，这样的人会变得特别可拍的人，出卖耶稣不是别人，而是十二个门徒当中。撒旦不断的做工在十二个门徒当中，改变了加略犹大。

亚拿尼亚完全没有想到过，这是那么大的罪。但是这教会里面，如果我们拿着分明的信仰生活的话，教会所走的神的路，我们会跟随这个路，所以和神走一样的路的话，无论年纪大还是小，无论有钱没钱，有没有教育，有没有学历，能够过神的引领之下的生活。

那么我呢？神是如何引领了我？如何让我脱离困难，这么困难的时候，让我如何依靠神，让我如何明白圣经，神所教会我的这一切，分明的知道这一点。

我最近也会思考，我们教会有高中生，18、19岁的孩子们，如果想到这些孩子们，“我想为了主奉献我的人生”，我想着明年要去短期的人四月份就会开始招募，招募之后，在他们短期之前，先让他们选择去哪个国家。不是只是说什么德国、巴黎、加纳，什么法国、西班牙，不是这样，而是让他们在六个月左右在本土韩国先学习当地的语言，之后再派遣。学六个月左右当地国家的语言，不是完全零基础，而是稍微知道一些基础，之后再去的话，当地一年的话，他们肯定可以流畅的说当地的语言。

在俄罗斯，有很多说俄语的韩国学生的话，是很了不起的。在巴拉圭，或者在阿根廷，能够说流畅的西班牙语的大学生，这是了不起的。我呢，在过人生的时候，不是在世上上班的生活，的确这样的话会很好的生活，但是如果一个十八十九岁的一个学生，如果心里想：“我想为了耶稣，我想奉献我的人生。我想为了耶稣忍住我想吃的，学习节制自己的生活。我想为了耶稣度过我的余生。我想读一读圣经，我想学一学传道”，就这样开始哪些学习的心，到了 20 岁，到了 70 岁为止这样生活的时候，这是 50 年。一个 20 岁的人明确的得救听福音，然后为了福音过 50 年的话，就会发生奇妙的事情。比起别的，神会帮助他。

我第一次见过的那个鲁哥总统，这次去巴拉圭也见到了他，鲁哥总统对现在的巴拉圭总统说，介绍了我，见到了，现在特别感谢他。鲁哥总统是我传福音得救的第一个总统，他说最近他的腿有些不好，医院说他的血液不是很清澈，为了血液的话别的药也好，但是蔬菜特别好。

如果我们国家一个 18、19岁的一个学生让他成为部长也是，他说：“我不想成为部长，我想为了福音生活”的话，如果他往这个方向发展的话。如果看在我的人生中，神帮助我的事情的话，我感觉他会做出很惊奇的事情。但是大部分的学生会摇摇晃晃，大概的大概的传福音，是因为这样的缘故才这样。如果心里想，我今天就死了，现在我想我就是耶稣的仆人，接下来的人生就为耶稣生活的话，就这样生活到 70 岁的话，就是 50 年了，真的是太可怕了，因为会改变这世界。我是没有想到我要这样做。

我跟牧会者们常常说要办 CLF，2017年开始办了 CLF，在美国大概有 700 个牧会者来参加，就这样传了一个星期的福音，美国和周围有 700 个人来参加，还有我们国家 50 个人，一共 750 个人听了福音，这 700 名牧会者们大吃一惊，他们常常问我：“你怎么解释圣经解释的这么容易呢？”，我回答他们说：“圣经本来就是容易的”，他们更是吓一大跳，他们觉得说圣经是容易的，简直不像话。

在圣经里面耶稣说，在迦拿婚宴指着水说这个葡萄酒，相信这一点一点也不难，耶稣说是葡萄酒就是葡萄酒，相信就不难。不相信的人的话，怎么在考虑再思考也是，“怎么能让水变成葡萄酒呢？水和葡萄酒有什么区别，葡萄酒到底是怎么做出来的？”，如果研究的话，再怎么研究也研究不出答案来，太困难。**不去做研究而是相信耶稣，实在是容易，就在那一时刻就能进入灵里的状态。**一点也不困难。

有很多神学院说，一个童女怎么可能生孩子？一点也不像话，的确是那样。在美国有一个人，他的妻子努力热心的去聚会，这个人是生物学家，生物学博士，他想打败牧师的缘故跟妻子说：“你邀请牧师来我们家吃饭吧”，在吃饭的时候这位博士就问：“牧师，你相信一个童女生孩子吗？”，牧师就说：“我相信，如果神做的话有什么不可以的呢”，他说：“牧师，我实在是太失望。我是科学家，在科学的道理上无法说明一个童女生孩子。我妻子去的教会的牧师竟然如此无知。”就这样吃完了饭。总而言之，之后这个人遇到了问题，他发表的论文研究都失败，最后他开始相信了耶稣。有一天跟妻子说：“妻子，我们再邀请一次牧师来吃晚饭吧”，就这样邀请了牧师来吃饭，已经过了五年，说：“牧师，现在您还相信童女生孩子吗？”，牧师说：“是，我相信”，他说：“现在我也相信了”。他说科学也能够证明，因为母鸡没有受精也是能够生蛋。“我当时说不信，那是站在不信的立场上，所以全都是不信了”，但是我现在能够找到能够成立的科学。

撒旦给了我们很多的想法，有些想法让我们对信仰生活远离的，开始不信信仰。魔鬼给我们这样的想法让我们的心远离话语，过上堕落的生活，敌对话语，魔鬼这样做。如果智商低的话，魔鬼不费劲就牵着我们走。不是我们太笨，而是撒旦太有智慧。

但问题是什么呢？在我们的人生当中，有神的旨意，神的安排。如果就这样看的话，感觉不一样；**只看撒旦做工的话，只能看到消极的、否定的想法，但是稍微读圣经的话，相信神话语的话，就会发现在我的人生里有神的安排。**

在那一天晚上，我和我的妻子，还有恩姝，应该吸了煤气死了才对。明明那一天晚上，我妻子，我的女儿都会死去的。我的女儿在第二次嚎啕大哭，神呼叫了我们，要不然在第二天早晨我们都会成为尸体。**即使我吸了煤气，也是神保守我呀。我把我的人生交托给这位神，和交托给我自己，是无法比较。我思考的时候能发现。** 

我不知道多么感谢我的女儿，如果她不哭的是吧？我也是一般睡觉睡不醒的人，但是那一天因为恩姝哭，被叫醒，我也是很嫌烦。**那个时代有很多人因为吸煤气而死，我应该死的人，但是神为了让我传福音，神让我活过来，神为了让我传道，神救了我，我活过来。那我的身体还算什么？我的身体是神的身体。不仅我是这样，我们都是一样，我们都会死，都会失败，但是蒙着神的恩典才能生活着。**如果这道这一点的话，就不会不思考的，只是以为自己最聪明的生活，宝贵的神的手记能够看到这样的部分。

门徒的妻子在结婚之后生活着，之后他的丈夫得救成了门徒。我们教会现在也是有很多师母是这样的，不是喜欢传道，而是因为丈夫，被逼着成为师母，也有这样的。然后会跟着肉体生活，当然，向着肉体生活不是就这样，而是因为就是缺一个想法的缘故那样。

在圣经里面，七是完美的数字，但是少一个一的话就是六，六就是肉体的想法。但是比肉体的想法缺一个一成为五的话，就是恩典的数字。这些数字特别有意思，肉体的数字是六，但是如果真的发现自己的缺乏的话，就会蒙到恩典，会成为五。

这位门徒的妻子，看到她的丈夫祷告、宣教。有一个全莹苏师母，她跟随自己的丈夫去了加纳，特别的难受，有虫子，还有厕所又热，真的是快要发疯了。但有一天在宣教会的本部，说让他们去这个密林里。他们到了密林里，抬头看见了蛇，吓一大跳。在那里这是常见的，在那里生活第一次发现了神的爱，怎么发现的呢？邀请他们的人说：“牧师特别抱歉，我们家里有这个香蕉树，但是是妻子的不是我的。我的妻子是财主，但是我是贫穷的”。他们明明是夫妻，这位师母心里想：“他们是疯了吗？他们是一家子，为什么还分你的我的呢？为什么丈夫挨着饿也吃不上饭，但是妻子又那么富裕，这算什么夫妻呢？”。那个时候全莹苏师母吓一大跳的是，在生活里虽然不是分香蕉你的我的，但是在别的部分一直分着你的我的。她发现了这样的自己，就这样之后他们到了贝宁，加纳是说英语的，贝宁是说法语的。这个师母跟我说，从那天晚上开始在英语词典、英语圣经，还有法语词典、法语圣经，去每一个家里面，恳切的传道。就这样得了疟疾，最后她离开了这世界。

这位师母得救之后，为了福音生活的这过程，实在是美丽，特别可贵的人生，在困难的环境里哪怕不会说法语，但是拿着法语的圣经和词典，让听福音的人自己读读看，特别特别的宝贵。

这个门徒的妻子和丈夫一起生活的时候，常常拿着肉体的想法去看的时候，你为什么去传福音呢？为什么去宣教呢？你能不能不去宣教，只是当长老？为什么你偏要去宣教学校？但有一天，他的丈夫就这样死了，死了算了，死了才好，从你死了我才能离开这个宣教学校。我想把两个儿子养好，然后想过得好，出去之后我自己赚钱就是了。开始可能在银行借了钱，做了生意，生意好的时候就是放在那生意也能好，但是生意不好的时候再怎么动脑子也不行。景气的时候随便的卖也能卖得好，不景气的时候再怎么卖也是卖不好。**那些失败的人不是说做的不好，而是做的再好也是失败。**所以失败的条件就是一个。就这样这个门徒的妻子的儿子只能被卖为奴隶。

我想了，如果我是这个女人的话，我去找神人，现在不是得到解决，也没有债务了吗。我感觉我会让我的两个儿子去宣教学校的，各位可能不会那样，但是我会那样的。所以这个人她的丈夫去世之后，自己生活的时候，遇到很多问题。那现在对我来说希望只有神一位，之前我不知道，因为我之前不知道这一点的缘故，因为之前我不知道这一点的缘故，我把心都放在这世上；因为我不知道的缘故，我一直走向肉体；因为不知道这一点，我才撇弃了神；因为不知道这一点的缘故，我小看信仰，除此之外再没有话可说。

如果知道耶稣的爱的话，就能知道这个世界什么都不是。耶稣说什么呢？“天国就像藏在田地里的宝贝一样”。有一个人耕种着别人的地，但是锄头卡在石头里，反过来一看原来是金子，然后他把金子重新埋到了里面。在别人眼里看这个田，只是石头地，但是这个人的心里面呢？那个地就是一块宝，是吧？也可以卖了所有的财产去买这块地。但是不知道这一点的人呢？他会心里想，这个人是疯子吗？为什么他会花这么多的钱买这一块地呢？可能会这么想，那我们呢，发现了藏在地里的宝贝之后，想让这块心离开这块地也是无法做到。

各位是因为看到了福音的表面的缘故才那样，如果发现这块宝的话，无法离开这块地，只有卖了所有的财产也想买这块地。如果看见耶稣里面这宝贝的话，神救了我，只能在煤气里死的我，不是一次两次这样的事情，有数不清的问题、数不清的反对、敌对，但是直到今天，我能够站在讲台上讲道，这就是神的恩典，这是神的爱。

在我不知道这一点的时候，我看地就毫无价值，但是在发现了埋在地里的宝贝的时候，就算卖掉自己所有的财产也不觉得可惜。在不认识耶稣的时候看耶稣，才会觉得什么都不是，才会跟着肉体生活。如果知道了耶稣的可贵，耶稣的爱，耶稣的恩典，为了钉在十字架上的死亡，洗净了我的罪的这位。行淫时被拿的女人回家之后会干什么呢？只能感谢，“我居然能回到家里面来”，睡觉醒过来，心想：“我竟然还能睡觉再醒来”，吃饭也是心里想：“我竟然能吃饭”向着耶稣的感谢简直忘不了。把我从永远的撒旦的罪恶当中洗净脱离出来之后让我成为神的儿女。

稍微贫穷一点又怎样？挨饿又怎样？被挨骂又怎样？困难又怎样？耶稣与我同在。撒旦就是这样不断把想法放到我们心里，让我们离开耶稣，让我跟随肉体，跟随堕落；用绳子每天都牵着，每天都拽着。各位在发现耶稣真理之前呢，就感觉什么都不是。

在今天早晨，我和门徒的妻子做了很多的对话，最后我问了这个门徒的妻子：“你的两个儿子，你打算怎么办？” "还有什么好说的，当然让他们去宣教学校，是吧？这还有什么可问的，让他们成为一个了不起的牧师，一个去美国，一个去德国，两个儿子就这样生活好的很"，我感觉她大概是会这样的。

各位，撒旦呢，让我们看耶稣什么都不是，让我嘲笑着耶稣。如果知道耶稣的爱的话，心里就会想：“我是得救了啊”。我的父亲得救之后去世了。我的哥哥在父亲去世之后说自己是不孝子，但是我说我是孝子。是吗？因为我是让我的父亲去了天国，这样不就行了吗？这世上哪有这样的孝子？去了天国还会再见面。我的哥哥那么说自己是不孝子，我说我是孝子。在我父亲葬礼的时候有猪肉，是蒸着的猪肉特别好吃，我吃完一盘再吃一盘，我的哥哥就这样看着我。他虽然没有说什么，但是我猜他的心里肯定说：“我的弟弟身为牧师，现在爸爸死了，吃猪肉吃的这么馋”，因为我和哥哥住在不同的世界。我的哥哥说想要做一个坟墓，我说不要做这样的事情，哥哥说：“我知道这是毫无用处的，但是我是不孝子，如果连这个也不做的话，我实在是对不起我父亲了”。我看见我的哥哥在父亲的坟墓面前哭，我的父亲和我的哥哥之前常常吵架。其实和哥哥不起来，我连哥哥也不如，但是我身为牧师做的只有一件事，就是让父亲去了天国。特别的感激，我绝对不是因为牧师是我的职业的缘故我吃法、生活，而是从中，我得到喜乐，得到希望，得到明天，得到感谢，得到幸福。但是很多人虽然信着耶稣确实没有因为耶稣喜乐，有很多人虽然信着耶稣却不能因着耶稣而感谢，那是因为被撒旦欺骗的缘故。

各位，如果耶稣与我们成为一体的话，那么除了耶稣以外什么都不需要。儿子只能被卖为努力的这女人，有神人在一起的时候，被毫无问题的解决，她两个儿子肯定去了宣教学校是吗？各位我们需要朝向耶稣，仰望耶稣去看一看，去思考耶稣赐给我们的恩典，把我们这样丑陋的人钉在了十字架上的宝血洗净了，就是为了洗净我们的罪。

在彼得离开了耶稣去钓鱼的时候，耶稣重新把彼得引领回来的这声音，各位需要听一听看一看，如果思考，心里只能够充满耶稣。希望每一个人都能够与耶稣在一起，


