= 两个儿子的未来

TIP: 有一个先知门徒的妻哀求以利沙说：「你仆人－我丈夫死了，他敬畏耶和华是你所知道的。现在有债主来，要取我两个儿子作奴仆。」以利沙问她说：「我可以为你做什么呢？你告诉我，你家里有什么？」她说：「婢女家中除了一瓶油之外，没有什么。」以利沙说：「你去，向你众邻舍借空器皿，不要少借；回到家里，关上门，你和你儿子在里面将油倒在所有的器皿里，倒满了的放在一边。」于是，妇人离开以利沙去了，关上门，自己和儿子在里面；儿子把器皿拿来，她就倒油。器皿都满了，她对儿子说：「再给我拿器皿来。」儿子说：「再没有器皿了。」油就止住了。妇人去告诉神人，神人说：「你去卖油还债，所剩的你和你儿子可以靠着度日。」
(列王纪下 4:1-7 和合本)

因着新冠病毒，国家面临着危机，尤其是被传染的人的心里面特别的困难。还有，这个病要赶紧好，担心着，如果不好该怎么办；也担心，万一死了怎么办。

当然除了新冠病毒以外，在我们人生当中往往会有突如其来的问题，我们信神的原因是什么呢？去买汽车保险的人，不是因为出了事故去投保，而是因为有出事情的可能性的缘故去投保，想要得到资金上的资助，当然信仰与福音与这个不一样。

但是我们不能因为平安就代表没有问题。还有遇到问题时，为了我生活的人，和为了神生活的人不一样。在我得救之后，在我的朋友当中，去看我的同学的话，有很多的人当然生活比我更好，但是当他们遇到问题的时候，看到他们完全没有路，没有方法。但是我与他们不一样的是什么呢？主与我在一起。不是没有问题，而是即使遇到了问题，看到神帮助我的手特别的奇妙。

我在今天早晨看着《列王纪下》话语思考的时候，我想到这门徒的妻子，他的丈夫死了之后，和两个儿子一起生活。如果是对现在的人来说的话，可能是做生意借了债不知道怎么样，她面临着必须卖掉两个儿子才能还债。在圣经里面，无论是什么原因，这个妇人有债。**在这面前，有神和没有神，完全是田地之差**。

我生活过来，遇到过很多问题，但是神帮助我的事实是无法忘记的。

我在大邱波洞，第一次去那里的时候，我的一家人全吸了煤炭的烟，那个时候那个地方所有的人家都烧煤炭。那个时候，我家的煤炭的烟泄露，没有人知道，我也是不断的搬家的缘故，所有很劳累，吃完晚饭我睡着了。我的女二，在那个时候大概两岁差不多吧；我已经睡着了，但是我的女儿在那个时候突然放声大哭，我那时实在是太困的缘故，被她惊醒，我很嫌烦，就问妻子：“为什么让孩子哭呢？”，我的妻子说她毫无理由就哭了。重新拍她，她就睡着，但是睡到夜晚，这孩子又是嚎啕大哭起来，我就开始真的烦了，对妻子说：“她为什么哭呢？”妻子说：“没有理由她就哭了”。开灯也是，什么问题也没有，我的妻子站起来想要去一趟卫生间，她打开房门，有凉风进来，她就直接摔到了，吸了煤气的话，呼吸新鲜空气就会晕倒。那个时候我心想“原来我们在洗着烟那”，怕她再摔倒，我就把她推到一边，我就喊叫寻求帮助。在我的隔壁有个租户，他马上跑不过来，他是我不认识的一个邻居，我跟他说，她还想是吸了煤气，他就把我妻子赶紧带到他的房间，铺了被子让我们在那里睡觉。第二天早上，他知道了我是牧师，我给他传福音，他得救了。我特别特别的感谢。

我偶尔回过头来思考，为什么当时恩姝哭呢？如果当时不哭的话，我们一家三个人在第二天肯定会成为尸体。我想是神帮助了我，保守了我，特别的感谢。在当时看新闻，总会有那么两家死于煤炭，在那天晚上，我听着恩姝的哭声特别嫌烦，但是看到神帮助我的时候，特别特别感谢。如果让我做这样的见证的话，真的是没完没了。真的是熬着夜讲也讲不完。

在苦难的时候，在我困苦的时候，在我伤心的时候，在我心里给我力量的，指引方向的神，引领我。

在1976年我开始宣教学校，每次祷告的时候，神赐给我想要开宣教学校的心，这样祷告。以前我最讨厌的就是开宣教学校，我心想像我这样的人办什么学校呢？我真的做不好，以为神已经忘记了，但是神又给我开宣教学校的心。我有一个我妻子的舅舅，他因为没有钱去了英国，到了英国见了英国的女王，他说他是第一个被女王亲吻额头的东方人，然后回到韩国，他开办了韩英圣书公会。就这样，他还活着的时候，我就去找上了他，我说舅舅你好，就这样打了招呼。因为我找上他，所以有点意外，我就这么说：“我想开一个宣教学校”，我就跟他详细讲了开办宣教学校的打算，他就安静的听了下去，最后我就说：“要不要和我们一起做呢？”，他是我妻子的舅舅，他看了我之后说：“哇，你怎么能想到做这样的事情呢？你的想法真是太好了，不知道你怎么能想到做这样的事情呢，真是太好了。”“我会帮助你，但是你也知道我的年纪已经老迈，哪怕我再年轻十岁，我也想跟你在一起，但是我只能帮助你，如果我融入到你那里的话，我怕耽误你，那你就努力做吧”，他就把他读过的书给了我一箱，都是我没有读过的书。

就这样开始宣教学校的事情是难以想象的。那个时候大概有20几名圣徒，向着他们说我想开办宣教学校，他们就大吃一惊。
[%hardbreaks]
“宣教学校是什么样？”
我就向他们说：“是培养宣教士的”
“在哪里呢？”
“就在礼拜堂。”
“那吃什么呢？牧师，你自己都挨着饿”

但是 1976 年就这样开办了宣教学校，现在在全世界有力传福音的都是我们宣教学校出身的人，在当时谁看也是简陋朴素的。金东成弟兄在高三来到了宣教学校，他的母亲离世，后来继母进了家门，他的父亲也离世。金东成的母亲让他上了商业高中，一般那所学校毕业的话都会去银行，他在这如此困难的家庭里，毕业以后没有去上班而是来到了宣教学校。他的母亲特别伤心就来到宣教学校里，打开了一楼的门，这些学生们都紧张起来，就那么几个学生，我看见那位奶奶特别的气愤，说：“我的儿子学习好，特别困难的学习毕业，我就等着他能够在银行上班”，总而言之，就是这样我们开始宣教学校。

在全世界宣教会里引领全世界宣教的re都是我们好消息宣教会毕业的人，无论是哪个国家，我们都掌控着全世界的基督教，真是难以想象的事情。我开这个宣教特别让我喜欢的是什么呢？无论是下雨还是下雪，只要吃完早饭的话，就有宣教学生在等着我。打开圣经，在讲道的时候，我的心里面开始与话语亲近，我的心浸透在话语里。在我传福音，也有得救的圣徒，明明因着同样的话语得救，有的人感激，不知道怎样是好，但有些人“哦，得救了吗？”就这样很平淡，这样的人不一样。明明都是靠耶稣的宝血得救，有的人走向肉体，有的人跟随自己的欲望。在宣教学生们当中也是，有些人有真正爱主耶稣的人，甚至我看的时候都有些惭愧，因为比他们我更不如。有些人真的让我难以抬头，有很多这样的宣教学生。

今天南都迅弟兄做了见证，他是一般普通公司的员工，他说他毕业了玛哈念神学院，我在毕业典礼的时候听了他的见证。我就心里想：“这个人怎么能拥有这样的心呢？这个人怎么能有这样的心在他心里产生呢？”他在上着班，每天晚上熬着夜去听话语、学习、写论文，真的是很不容易啊。当然从神学院毕业的人，并不都和南都迅弟兄一样，人都会改变，无论是谁人都会改变，跟着时间过去、环境改变、生活改变，就会变化。我们也无法责怪人们改变，因为神创造了就是让人变化。当然有的人从坏往好处变化，也有的人从好处往坏处变化，能够看到神的恩典，神的路在他里面。

在 1962 年，我特别特别的困难，但是在那个时候我向着神不知道多么的恳切，我得到了罪得赦免。在我们家里有一只鸡，我们无法吃它，因为还有靠着它下蛋。每二十个鸡蛋报过去来，就到了菜市场，放在路边上卖。当时就是靠卖鸡蛋的钱，买火柴，买肥皂，很不容易买一些粮食；因为卖了鸡蛋，所以只能喝粥，生活真的很不容易，也常常挨饿，但是在那个时代，那个时候，我真的想好好的生活看看。我想了很多的想法，但是再怎么想也是没有方法能够脱离贫穷。我也试了很多的方法，但是最重要的是没有希望。在 1962 年的时候，最满怀希望的去考技术学士的事情，但是在落榜的时候，我开始失望。我就开始拜托军医官，能不能通融一下呢，他说为什么总是这样呢你？等国家义务招你的时候再去吧，我就说：“求求你帮助我吧”，他就说“我想帮你也帮不了你，你碎的是门牙，又不是臼齿”。不知道我是多么的期待这件事情，那时候我的门牙也不是碎了很多，只是一点点，真的没有想到我会因着这个事情我会失败。为什么我就不行呢？别人都行，为什么就我不行呢？我的前生到底是犯了多么多的罪？我就这样想。

在 1962 年 10 月 7 日就这样得救。哪怕是现在重新回顾起来，非常的感激，我的罪得到赦免，我想为了主做点什么，我也想奉献。但是过了一个月，过了两个月也是，哪怕十元钱我也没有捡到。那个时候哪怕去偷钱我也想去奉献，有这样恳切的心。但怎么能去投钱呢？不是吗。那时候我常常唱的歌就是：“哪怕用眼泪也无法还清的主的恩典，只能献上这身体” 当时经常唱这首赞美，那我就想了，我要把我的身体献给神。我的身体连这下士军官也不要的身体，哪里有什么用呢？那时候我发现我的身体也是一无是处的人。因为那时候是625事变之后，没有地方能够找到男人，我们村子也是很多家庭是没有男人的，有的人家因为地炕裂了，只要烧火的话整个房子里都是烟，但是我就想到了这个点子来，我虽然别的做不了，但是可以修别人家的地板还有天花板。我就想象了，我先去一个奶奶的家，我看见她的家在漏雨，把稻草重新捆起来给他换一个屋檐，我就跟奶奶说：“奶奶，我修好了，你就住吧，能给我喝一杯水吗？” 就这样喝完一杯水出来了，想象了这样的我，特别的高兴。“阿姨，已经把地板修好了，你就尽情的烧火吧，房子会很暖和的” 就这样喝完一杯水出来，非常的幸福，光是想象也是。我心想这件事情我应该能够做到。我老了之后，也是能够给别人修房子，能够喝杯水喝，我感觉就是这样生活也是很幸福。什么当牧师，从来没有想象过，什么福音传道者也是从来没有想象过。

因为我舌头短的缘故，我的发音不好，我的妻子经常嘲笑我说不来四十三年这个发音，只能说四四三，我从来没有想到我会成为牧师，但是因为神打造我，像我这种人也成为了牧师。在我牧会的时候，我什么都不知道，有的时候现在我重新回顾以前，我想我怎么成为牧师了呢？我居然成为了牧师。有的时候我也会自问：“你算是牧师吗？” 有的时候我和圣徒聊一聊的时候，有的圣徒呢，居然爱耶稣比牧师更爱。在这样的人面前，我完全是无地自容，这位弟兄为什么能够如此爱耶稣呢？这位姊妹怎能如此爱耶稣呢？怎么能拿着这样的心生活呢？有的时候让我感受这样的部分的话，如果这样的弟兄姊妹对我说：“牧师啊” 这样的话，我就自问：“你还算牧师吗？就你这样怎么还能算牧师呢？” 真的有这样的弟兄还要姊妹，让我特别的幸福，也是特别感谢。

有传道士，我们培养了很多传道士，虽然都是传道士，但是他们都是各从其类的。
34:32




