= 仰望耶和华的必从新得力
朴玉珠牧师 2020.03.08

.路加福音15章11-24
****
耶稣又说：“一个人有两个儿子。小儿子对父亲说：‘父亲，请你把我应得的家业分给我。’他父亲就把产业分给他们。过了不多几日，小儿子就把他一切所有的都收拾起来，往远方去了。在那里任意放荡，浪费资财。既耗尽了一切所有的，又遇着那地方大遭饥荒，就穷苦起来。于是去投靠那地方的一个人；那人打发他到田里去放猪。他恨不得拿猪所吃的豆荚充饥，也没有人给他。他醒悟过来，就说：‘我父亲有多少的雇工，口粮有余，我倒在这里饿死吗？我要起来，到我父亲那里去，向他说：父亲！我得罪了天，又得罪了你；从今以后，我不配称为你的儿子，把我当作一个雇工吧！’于是起来，往他父亲那里去。相离还远，他父亲看见，就动了慈心，跑去抱着他的颈项，连连与他亲嘴。儿子说：‘父亲！我得罪了天，又得罪了你；从今以后，我不配称为你的儿子。’父亲却吩咐仆人说：‘把那上好的袍子快拿出来给他穿；把戒指戴在他指头上；把鞋穿在他脚上；把那肥牛犊牵来宰了，我们可以吃喝快乐；因为我这个儿子是死而复活，失而又得的。’他们就快乐起来。
****

关于浪子的话语，我们也常常讲，但他不只是一个故事。当二儿子回到父家所感受到的喜乐，不知道各位是怎么认为的。我感觉这事儿和我的故事一样，神把在这里的所有一切都赐给了我们。有一次，当崔约翰弟兄因为被蝎子蛰了快要死去的时候。在这个弟兄的身体里有蝎子的毒进来之后，这个毒已经接近于心脏了，这时候心跳数也下降了很多。然后崔弟兄跟我说，当时他的体温只有17度，心跳只达到20。蝎子的毒已经达到了心脏，心脏无法自由跳动，他正在死去。真的是，无论是谁看了也是，医生说他无法再熬一两个小时了。那里的I.Y.F支部长牧师给我打电话。牧师！这里的崔约翰弟兄正在死去。我们没有能力去改变这样的事情，从这里坐最快的飞机到利比利亚需要18个小时。那时候也没有直达的航班，必须要转机才行。医生说他很难熬一两个小时，对于我来说一点都没有希望。那时候对我来说没有一个事情能为崔约翰弟兄去做的。

我想给崔约翰弟兄传话语，我就问宣.教师：“我能和崔约翰通话吗？”

“是，牧师。”

“约翰，是牧师，你赶紧接一下电话。”

我就这样和崔约翰弟兄进行通话，“约翰你能听到我的声音吗？”

“是......，牧师。”

他真的是正在死去,我就跟他说:“我听说你被蝎子蛰到，正在死去，你仔细听一下我的话。今天早上我读了以赛亚书40章31节的话语。在圣经里面怎么说的，【**但那等候耶和华的必从新得力。**】所以约翰！无论谁说也是，这圣经66卷都是神的话语。”相信圣经是神的话语和不相信的人的差距在哪里。当陷进绝望的时候，心里面能够见到神，能够见到神的应许。所以我就继续跟他说，“这圣经里是怎么说的呢？说等候耶和华的必从新得力。约翰，我听说你正在死去，那如果你仰望耶和华看看。神向着你的应许就是向着我们的应许。你凭着信心相信这个话语，神就会在你的心里做工。如果你一定仰望耶和华，那神一定会赐予你新的力量。神绝对不会撒谎，神哪怕一次也没有撒谎过，约翰无论是什么，神一定会成就的，我相信神。如果你仰望耶和华的话，神一定会赐给你新的力量，如果神赐给你新的力量，那个蝎子的毒真的什么都不是。”

就这样大概有15分钟的时间，和约翰通话。跟他通话的时候，我心里面想，只要约翰相信话语，我心里面没有怀疑神会赐给约翰新的力量。约翰处于快要死去的状态下，只是把这个圣经话语相信了，神啊，我在死去，现在我仰望耶和华，主不是向我应许了吗？主不是向我应许赐给我新的力量吗？我相信主会赐给我新的力量，希望主赐给我新的力量。如果主赐给我新的力量，我会战胜蝎子的毒。在约翰的心里只接受了这一个变化。我们基督徒就是天上的那位神的子女，神赐给了我们许多的应许。无论各位是谁，遇到怎样的环境，只要相信神的话语、应许，如果拿着和神的心一样的心，无论是神与各位再遥远，无论是各位陷进任何一个罪恶里，无论是在任何困难当中，只要神在各位心里做工，那什么都不成为问题。

在《创世记》一章里，说【起初，神创造天地。地是空虚混沌，渊面黑暗；神的灵运行在水面上。】各位，虽然地是空虚混沌，渊面黑暗，但是重要的是有神的灵在那里。当各位遇到任何一个困难和绝望当中的时候，即使那个痛苦比神在各位心里更大，如果拿着仰望耶和华的心，先从那个困难转移到仰望神的那里。这不是理论，实际意义上，神的恩典会临到各位的心里。在各位心里不是为别的，占最大的比重的是什么，虽然当时空虚混沌，渊面黑暗，向着这个地，神的话语也临到了，说要有光，不是这个地能够战胜黑暗，不是这个地能战胜空虚，而是因为有神的灵与它同在，是神驱赶了黑暗。

罪不是由我来洗净，如果在各位心里边有主耶稣的话语，神的话语来洗净各位的罪。如果在心里有话语，话语能够驱赶各位的痛苦，黑暗，问题。最为有力量的人就是有神的话语在他心里的人，崔约翰临近死亡的时候，信心产生起来。

我现在看到崔约翰时特别的感谢，我看到他的图片，他的脚完全的朽烂，他的心脏也是遭到了蝎子毒的攻击，无法正常工作，那问题是什么呢？当各位不信神的时候，当各位不依靠神的话语的时候，当各位不仰望耶和华的时候，各位的心只能处于黑暗当中，失望当中，绝望当中。虽然地明明是处在空虚混沌，渊面黑暗里。这渊面黑暗到底是靠什么能够驱赶呢？这黑暗这空虚怎么能够驱赶呢？不是我们能够驱赶，而是因为神讨厌黑暗，之所以说：要有光，就有了光。那个光，神看为是好的。如果各位行走在光里，如果拿着这个光去吃去喝，当我的心里面充满担心，忧虑，黑暗的时候，在我心里面持续仰望耶和华，持续仰望神的应许，只相信神的能力。当这个能力进到我的心里，作为我的心的时候，在我们相信神的时候，当话语住在各位心里的话。

特别神奇的是，在约翰福音一章里面说：【太初有道，道与神同在，道就是神。这道太初与神同在。万物是藉着他造的；凡被造的，没有一样不是藉着他造的。生命在他里头，这生命就是人的光。光照在黑暗里，黑暗却不接受光。】这里说话语里面有光，有生命，有神。所以在我们读了圣经话语，当我们接受的时候，神就会开始在各位心里做工。如果让我讲关于这样的话语，真是熬着夜也讲不完。在我们传福音的时候，当然我们也会遇到难以言尽的问题，困难，无论是在我们举办休养会或者圣.诞主题音乐会或者活动。这样的时候，让我们特别特别感谢的是，这样的事情在举办之前，没有一次是人看的时候是可能的。在我们举办数多次大型传道布道会，这样的时候，有很多的问题，担心、疑惑，有的时候会有怎样的心呢？我不这样做的话，难道就吃不起饭吗？非要做这样困难的事情才能活吗？真的下次不想再做了，这样的心也会在我的心里产生，但不是一开始就得做下去吗？在做这样的事情的时候，我们只能向着神祷告，因为困难向神祷告。在这样的时候，神的话语进到我们心里，有神在我们心里，那个时候开始，神非常奇妙的、奇迹般的在我们里面做工。

我刚开始见到巴.拉.圭.总.统费尔南多·卢戈的时候，在前段时间也见了总.统之后，一下午和他一起吃饭、聊天。当时我们在很多国家进行I.Y.F活动的时候，有巴.拉.圭的大.使来见我，然后他跟我说:“我想让牧师成为我的大哥。”然后他说什么呢？他给自己起了一个韩语名字叫朴大洙。我就说:“你都是弟弟了，为什么你还是大洙？”不管怎么样，我就这样有了一个大.使弟弟，相处得很好。过了一年之后，他又来找到我，他说：“大哥我遇到了困难，我想找你讨论。”

我就说：“什么事情？”

巴拉圭的总.统想要访问韩.国，他会在韩.国待三天，他是韩.国的大.使，他要负责总.统在韩.国的所有的日程。人们在自己做大.使的期间里，如果有自己国家的总.统来到这个国家，他说:这是在一生当中能有一次也很难得的幸运。他来到这里会有很多事情跟总.统说，所以他需要很好的去招待总.统，但是因为大.使馆的预算不够，感觉无法很好的招待总.统，所以他很苦恼，他跟我说:“我们的总.统喜欢音乐，我想为了总.统准备音乐会。能派格拉西阿斯合唱团过来吗？”我就说:“是吗？我和团长商量。”我就跟团长这么说，因为格拉西阿斯合唱团那个时候也有别的安排，但是她会准备一些人会去的，就给他准备了音乐会。他说:正好在蚕室体育馆有聚会，然后让我也过去。我大概在上讲台的时候是时间是8:22左右，从开音乐会的地方到蚕室体育馆，开车需要33分钟左右，我就说:我只能在那里呆到7:30。

“虽然牧师特别忙，但是这样也行。” 

我觉得要在6:30的时候到那，然后从7点和他见面，我到了那里，他给我打电话。“牧师你能来区政.府吗？”我就去了，他说：能到这个酒楼大厅吗？我就去了。我见到那里的市长，还有巴.拉圭总.统，还有两位部长，有大.使，有5位坐在那里，我就开始问候总.统，因为我实在太愚昧，见到总.统之后无话可说，没有话说，只要就这样传福音就行了。但那是我有生以来第一次见到总.统，所以我觉得大.使看我很是郁闷。然后他就跟我说:您讲讲I.Y.F的部分，我就这样讲了一分钟的I.Y.F的介绍。我讲了什么？讲了文慧珍的故事，然后文慧珍的故事讲了三分钟，就这样讲完了之后，不知道该说什么，然后我就把西班牙语的《罪得.赦免.重生的秘密》这本书送给了总.统，就这样过了30分钟，然后就开始了音乐会。过了几天之后从大.使那里给我打电话。他说:总.统在飞机里跟我说把那个书拿过来，但因为他的市长把那个书放到韩.国没有拿走，然后第二天这大.使的夫人拿着这本书回到了巴拉圭。总.统说:拿到这本书之后，把这本书都读完了。然后他说:读完之后想要再见我，就这样让我再给他写一封信，然后我把这个信给了大.使，他就直达给总.统。 

这次我想去见总.统，但是很困难，没有时间。我明年2月份去，因为在2月份巴拉圭有世界大会，我就一起去了。因为他们知道了我去巴拉圭的航班，等到我一下飞机，就有接机的人把我接走，当时我就开始受到一个同等于总.统所邀请人的待遇，也有保镖24小时保卫，我每次移动的时候也有摩托车在旁边护卫，见总.统之前我见了秘书室长，我问了他与总.统的会谈时间有多少？他说有40分钟，如果是总.统愿意的话，可以谈的时间再长，但如果总.统不愿意的话，就需要谈40分钟之后就结束。那天晚上我就一直做了时间表，做到很晚，40分钟里，我们合唱团歌唱的最少唱三首，唱三首大概需要花10分钟，然后打招呼、问好，会需要15分钟，这样都去掉之后只剩下25分钟。在这25分钟时间里我需要传福音，我就一晚上写了稿子，多次修正以后，终于整理出来了。

然后和合唱团的人说，我要给总.统传福音，他只给了我们40分钟的时间，10分钟的时间里，你们合唱要结束，然后打招呼、问好再花5分钟，绝对千万不要耽误我的时间。如果你们耽误我的时间，下次见总.统的时候就不带你们去了。所以有总.统问你们什么，你们只回答说:是、不是。然后我们就去了。很准确地打招呼、问好，然后就这样花了15分钟唱完歌，25分钟要把福音讲完。各位，特别感谢神的是，虽然也有很多问题，我还能够强烈地感受到，每当遇到问题的时候神都会帮助我。我跟总.统说:我找了使徒行传13章22节的话语，里边说:【我寻得耶西的儿子大卫，他是合我心意的人，】那神树立大卫为国王的理由是什么呢？那是因为大卫的心与神的心是相通的。大卫知道神的心，然后把他的心和神的心合二为一。如果阁下的心与神的心拿着一样的心，如果神这样的时候引领阁下所做的所有事情，帮助阁下，我相信神会赐恩典给你。那个时候总.统特别高兴地听我讲道。

那怎样能拿着与神的心一样的心，神跟亚伯拉罕说要赐给他一个儿子，但亚伯拉罕认为自己生不了儿子，这是与神不一样的心。实际上就是原本的接受神的心，无论我的想法如何。就这样我接着讲了靠着耶稣的宝血洗净了我们的罪。所有的人亏欠了神的荣耀，但靠着基督耶稣的恩典，得到基督耶稣的救赎，就白白地称义。 阁下这个话语是什么意思呢？阁下你也犯了罪，我也犯了罪，但主向着阁下说:你是义人，不是因为你没有犯罪，也不是因为你很善良，而是因为基督的宝血洗净了阁下的罪。在圣经里记录着说阁下是义人，接下来阁下的心如何与神的心一样，既然神说阁下是义人，就说我是义人就可以了。

那怎样能拿着与神的心一样的心，神跟亚伯拉罕说要赐给他一个儿子，但亚伯拉罕认为自己生不了儿子，这是与神不一样的心。实际上就是原本的接受神的心，无论我的想法如何。就这样我接着讲了靠着耶稣的宝血洗净了我们的罪。所有的人亏欠了神的荣耀，但靠着基督耶稣的恩典，得到基督耶稣的救赎，就白白地称义。 阁下这个话语是什么意思呢？阁下你也犯了罪，我也犯了罪，但主向着阁下说:你是义人，不是因为你没有犯罪，也不是因为你很善良，而是因为基督的宝血洗净了阁下的罪。在圣经里记录着说阁下是义人，接下来阁下的心如何与神的心一样，既然神说阁下是义人，就说我是义人就可以了。

这位总.统在心里特别感激，接着与总.统府里的记者们见面会，他说我也有罪，但我相信耶稣基督洗净了我所有的罪，请各位能够饶恕我的罪。这位总.统很长时间握着我的手，表达了他的感谢、感激。就这样每年2月份的时候都在巴拉圭有活动，我都会去。去的时候，总.统跟我做见证，在圣经里面说，即使我走在死荫幽谷里我也不惧怕，因为神与我同在。他得了癌症，去巴西治疗，这位总.统的病特别严重，已经无法说话，正在死去。那时候有的人在宫里争执接下来谁当总.统？有一个女医生说:这次巴拉.圭总.统来医治治疗，但是我们失败了。总.统来的时候走着过来的，但现在他已经成为无法说话的地步。我们治疗总.统失败了。这个女医生说:我们明明失败了，但一直固执这个方法，我们需要改变这个方法，不然的话，总.统会真的去世的。所有的医生都同意这位女医生，他们的意思就是通过现在这个方法无法救活总.统，到底应该怎么改变？就像今天他第1次来到医院就重新进行精密的检查，特别有效果。他们那个时候发现了在心脏旁边有一个别的病，立刻进行了手术。总.统把衬衫的扣子打开给我看了那个伤痕，然后他说医生给了药，他很快退烧并出院。有一个上议会议员和他一起去，我能够活着回来，那位上议会议员却死了。我想了总.统怎么说的，“我虽然在死荫幽谷，但我不害怕，因为主与我同在。”他跟我说了这个话语，之后每当我去巴拉圭都会见到他。这在我第一次见了总.统，过了40分钟站起来，特别感谢的是他得救了。然后在开车走了10分钟的时候，秘书室长给我打电话，今天晚上总.统想要参加大学生的活动，然后我们所有的人都鼓起了掌特别高兴。过了一会他又给我打电话，让26个部门的部长都来，已经吩咐他们也来参加。然后我就坐在总.统旁边，迄今为止能够和他过得像家人一样，特别的感谢。

如果各位相信耶稣，如果各位靠着耶稣宝血罪得洗净，在各位的心里面有圣灵与各位同在。在耶稣时代，神通过拿撒勒人耶稣显现了他的能力。但是现在神做什么事情呢？神正在藉着各位和我成就着他的旨意。各位无论遇到怎样的问题，希望不要拿着自己的想法去看，如果拿着神的心去看，如果各位的心和神的心变为一样的心，那时候神就开始成就奇妙的工。二儿子拿着父亲给的家产去了远方，他把所有的财产浪费在妓女身上，因为他没有钱，所以他被妓女撇弃。“你能对我这样吗？你不是说爱我吗？你怎么能因为我没有钱就这么撇弃我。”“我是爱你，但我是妓女，我是看上你的钱才爱你，那你再给我钱，拿过来我就再爱你。 没有钱吧？那我就不行，你滚！”他就这样被撇弃。就这样去给人家放猪，在放猪的时候发生特别奇妙的事情。因为他太饿了，只能去吃猪吃的豆荚，又冷又饿又孤单。所以眼睛看见的是猪，肮脏、挨冷只能看到这些。但有一天浪子本来处于又冷又饿的猪圈里，和脏兮兮的猪在一起，虽然身体无法去父家，但他的心回到了父家，见到了父亲，这是特别奇妙的。这二儿子的心回到了父家，看到父亲一早起来就呼喊他的仆人，“你耕地了吗？收割了吗？”就开始吩咐。 有的时候也会责备，然后就问他还要更多久才能耕完。看来在这样下去不行了！再雇10个工人吧！就这样清晨又雇了10个人去收割。大概到了中午，在村庄里面过来一辆马车，上面有食物，然后父亲说：“好了，到了吃午饭的时候，我们一起来吃饭吧！”二儿子看到很好的食物。

坐大韩航空的飞机时，空姐会问我吃什么？我就跟她说拌饭，我们国家的拌饭是出于全罗道这个地区的。全州这个地方田地特别肥沃，他们在田里干活的时候就会吃上拌饭。也就是说，不用带很多菜过去，直接在一个大碗里面放上米饭，放各种各样的蔬菜，然后放上辣椒酱搅拌着吃。因为那里的平原特别广阔，没有什么比吃拌饭还要好吃的。回到家的时候也吃拌饭，说这饭还剩一点，你也再吃一点，太饱了，再也吃不下去了。他想到以前在父家的田里吃拌饭的时候，我们家里有多么多的雇工口粮有余。不是别的，各位在黑暗里的时候，当各位处于绝望痛苦的时候，当崔约翰弟兄因着蝎子的毒快要死去的时候。我听了他的事，我里面也临到了死亡，在黑暗里面只有死亡，看来他只能死了。当他的父亲在达拉斯送崔约翰到非洲的时候，父亲说：“约翰！请你走好。”然后拥抱了他。在约翰的心里面有什么心呢？我死之前真想再抱一次父亲，但这已经变成不可能的事情。对，是不可能的事情。但是在这个时候我与他通话了，“喂，约翰！在圣经话语里，说：仰望耶和华的必从新得力，如果你想战胜蝎子的毒，你需要新的力量。圣经里面说如果你仰望耶和华，就赐给你新的力量。”请各位仔细听，约翰开始仰望了神，是的，神啊，我相信你，我仰望你，我相信你赐给我战胜病的力量。这个时候在约翰的心里仰望了神，他心里本来想被达拉斯的父亲抱着却做不到。

在各位的心里，虽然充满了像猪圈里一样又饿又冷又脏，但是神在浪子的心里让他能够仰望父家，虽然他身体躺在猪圈里，他的心却已经来到了父家。当神创造我们心的时候，虽然我们身体上的眼睛、鼻子、耳朵、嘴巴都在猪圈里，当我处于黑暗的时候，我的身体只能处于黑暗里，眼睛、鼻子和嘴巴都只能看到黑暗。当我在星级酒店的时候，我的脸、我的身体、眼睛、鼻子都在酒店里，我的眼睛无法脱离我的身体，我的鼻子也无法脱离我的身体，我的耳朵、我的嘴巴、我的身体、所有的器官都无法脱离我的身体。如果我的手离开我的身体就不叫我的手，我的耳朵离开我的身体就不叫我的耳朵。如果我的脚离开了我的身体就不叫我的脚。虽然我们离开了神，但只要我们的心能够转向神，我们的心就能和神同在。这个就是特别奇妙。无论是处于什么黑暗、无论是怎样的绝望，无论怎样痛苦。

我第一次去了大.邱，饿了好多天。有一次，主日礼拜结束之后，弟兄姊妹们都回家，家里没有粮食了，也没有钱。我亏欠我妻子，所以我对妻子不知道有多好，估计在全国没有一个人比我更爱妻子。不知道我的妻子知道多少。我妻子和我结婚的时候，是一个非常健康的女人，但她现在很苍老。我觉得是因为我让她受了太多的苦，所以那样，特别抱歉。但即使那样，我们住在耶稣里面，我都让给了她，我就跟她说你需要运动。我觉得跑步机挺好，刚开始做一点挺好。有一天我突然发现妻子特别老，我心想如果她死的话，真出大事了。我特别希望她能活得长久，真是这样！我觉得妻子应该时常在我旁边。随着年纪大了，不知道妻子看起来多么的可贵，真的特别感谢，我想所有的事情都让给她。虽然不知道她能理解多少我的心，我只能在这样的场合说出来。我只知道一点，就是无论我们身处何地，当我们思念神的时候，我们就能与神同在，无论是在怎样的困难，无论谁生了什么病，无论怎样困难，绝望，在各位思念神的时候，各位的心就与和神同在，在那个时候不要光思念，而是要相信，只要相信，仰望耶和华，就必从新得力。

二儿子去了远方。他与妓女在一起的时候，可能想不到父家，喝点酒，也不会想到父家，可能一直纸醉金迷，但是他到猪圈里，又饿又冷，又痛苦。可就在那时，身体是躺在猪圈里，他的心却渐渐走向父家。到了父家，也能看到父亲清早起来后，使唤雇工去干活。父亲责备人说：昨天你充分能做完的事情，为什么昨天没做完？家里的很多雇工都能吃得饱饱的。

二儿子想，在我父亲家里有很多雇工，口粮有余，但我却在这里要饿死吗？他开始想起自己的不是，浪费资财，和妓女任意放荡。这个坏女人，说爱我，怎么能这样，我真是太傻了，居然还相信她，不想再去想那些事了。但是想到父家的时候，想到老家的时候，躺在猪圈里看到天上的月亮的时候，在我的老家也能看到这个月亮吧，他的心已经回到了父家里。当他开始相信父亲的时候，神开始在他心里作工。很多人处在很大的绝望里，我特别希望他能够想到神。在交通的时候我就想说让他们相信神。只要仰望神，用心与神交流，神开始就会做工。我们的身体、眼睛、鼻子、器官都在自己的身体上。但眼睛离开我们的身体，眼睛就没有用处；耳朵离开我们身体的瞬间，耳朵就变得无用了。神创我特别不愿意人们看我挨饿的缘故给我钱，我不愿意别人看我可怜的缘故给我钱。因为我相信神会帮助我，向神祷告一次、两次。开始祷告的时候，我求的是米、钱、煤炭。

我来到纽约，过得非常忙碌，这次来到儿子的家，我感觉特别好。今天下午我和孙子们一起在院子里，后院里有一些长得不好的树，我们去砍了这些树。刚来这里能够吃上饭也特别感谢。来美国第一次感觉好像在休假。到了晚上，正好韩.国是白天，要办理的事情很多，很快过了11点，12点睡不好觉。我在耶稣里，在教会里，这一事实让我特别感谢。我看纽约教会的小孩子们特别可爱，和世上的那些孩子们完全不一样，孩子们特别明亮，特别谦卑。我就给他们说，孩子们，你们跟我一起来。过了一天看了那个小卖店也关门了，我叫了一个姊妹，我说：“孩子们你们想吃什么东西的话，你们去拿吧。”看到这些孩子们我特别高兴，虽然我的孙子不在那儿，孩子们怎么那么特别，特别的有趣，像天使一样呢。各位可能不知道，最近外面的孩子不这样，特别犟，特别坏。他们计较别人的错误，我在这里仿佛到了天国一样，特别感谢。看到弟兄姊妹们在食堂里干活儿，我第一次刮目相看纽约教会。

上次在南美的时候，最大的教会的一位总会长牧师来见我。当时合唱团在练习，他听了之后说：“这是格拉西阿斯吗？”我说：“是的。”“我能见见他们吗？”我说：“当然可以。”他就坐到了前面，他说以前看过格拉西阿斯合唱团的圣.诞主题音乐会，特别高兴，一直忙于拍照。神让我们连接那里的所有教会。昨天埃塞俄比亚的总领事过来了，总领事馆在这个亨廷顿，只有30分钟远的地方。自从现任总.统上任以后，就树立他为这里的总领事，因为他很了解这边，他特别了解我们。昨天我们聊了很长时间。他说一天会有两、三百个人找到领事馆，能够给他们讲福音就好了。他愿意给我们提供场所，希望我能他那里传福音，特别感谢。我们上周六，距离这里两个小时远的教会里举办了圣.诞主题音乐会和复活节礼拜，结束之后我讲了话语，那里的牧者们听了后特别感激。有一位牧师说他是南美的，和总会长是很好的朋友，他们俩一起到那儿参加了聚会。等我讲完道之后，那位牧师说的第一句话就是，不知多长时间里他一直以为自己是罪人。正因为我们不知道这个事实的缘故，总是说自己是罪人。他一边哭连连说感谢，我不知多么感谢，真是在神面前特别感谢。主日礼拜的时候去了曼哈顿周围的一个教会，他们的牧师们都到那里参加礼拜，他们眼睛睁得大大地看着我。有一个牧师坐在离我很近的地方，一直握着我的手说特别感谢。

各位，像我这样的人，罪恶的一个人，开始传起福音来有很多人得救。这次活动计划着有很多老会长总会长要来参加。希望我们让美国变成新的基督教国家，我们想改变美国成为信神的国家，有很多美国的牧师因着我们得救了。自从2017年3月份开始，第1次CFL的时候，有700多名的牧会者来参加，每当我们举办CFL的时候，有很多牧会者来参加，因为这个场地小，我们开始借更大的场所，为了他们准备一切，让他们能够参加我们的聚会之后得救。我想告诉他们如何传道，如何过信心的生活。我去想象这样的部分的时候特别的感谢。听到美国牧会者们的见证，我完全没有想到我能见到这么威望大的牧师。他们说 ：“我们知道格拉西阿斯合唱团，我们知道你们是特别好的团体，我们一定会参加的。”在美国有很多这样的人。

有一次我去了南美的巴拉圭，特别的感谢！大概有600多名的牧会者聚在那里。上午我讲话语，从9点半讲到11点，讲了一个小时的第1部分，从11点到13点又讲两个小时，特别的幸福！那里坐的都是大教会的牧师们，不是说代表他们个子很高的意思。他们代表这里很多的教会。接下来我需要见总.统，传完福音，我赶紧要离开。 有一个人提问：“牧师，现在我们知道我们罪得赦免，今后如果我们又犯罪的话，到时候怎么办？”我特别感谢他跟我问这样的问题，因为我确定他得救了。我就跟他说，如果得救之后又犯罪的话，开始享受永远的赎罪祭。我给他找了希伯来书9章11节：【但现在基督已经来到作了将来美事的大祭司，经过那更大，更全备的帐幕，不是人手所造，也不是属乎这世界的。】有两个圣殿，有一个牧师说礼拜堂就是圣殿，那是因为他不懂，可能他的意思是这个圣洁的地方，所以叫圣殿。 但实际上圣殿只有两个，一个在天国，一个在地上。当神赐给十诫命的时候，赐给了摩西两个十诫命石板，但无法让他只拿着十诫命石板走下去，为什么？如果是十诫命是法，若法临到这世界的话就会产生罪。神知道他们会触犯律法，犯罪，所以也教他们怎样洗罪的方法。如果要想洗罪的话，就需要献上赎罪祭。在当时一定需要动物，为什么？那是因为罪的代价乃是死。所以圣经说：无论什么物，都借着血得到洁净，若没有血，无法得到洁净。

除了耶稣的血以外，任何血都不能洗净我们的罪。有的人说悔改就能洗罪，有的人说告白就能洗罪，不是那样。不懂才那么说，实际上能够洗净我们罪的只有耶稣的宝血。天国有圣殿，地上也有圣殿，旧约的祭司长，他们在地上的祭坛上献祭，但耶稣基督没有把他的血涂抹在地上的祭坛上，而是涂抹到了天国的祭坛上。圣经是如何表达的呢？《希伯来书》9章11节里，【但现在基督已经来到作了将来美事的大祭司，经过更大，更全备的帐幕，不是人手所造的，也不是属乎这世界的。】这是指的圣殿说的，地上的圣殿是所罗门做的，会幕是以色列百姓建造的，这地上所有的圣殿都是靠人手所造的。这些圣殿会消失，为什么？那是因为它们属于时间界，正在改变的事情代表他正在消失。

当我们相信神的时候，神就会进到我们心里，然后我们和我们心里的那位耶稣，当耶稣的心与我的心成为一样的时候，耶稣与我们就是一体。我心里面的耶稣，这圣经说我们是义人。圣经里面说，当耶稣基督钉在十字架上的时候，说：“成了！”成了的意思是洗净了我们的。圣经里说，【但现在耶稣已经来到做了那将来美事的大祭司，经过那更大更全备的帐幕，不是人手所的，也不是属乎这世界的。】指的是天国的祭坛。之前的祭司长都靠着山羊和公牛的血，涂抹在地上的祭坛上，因为这地是属于时间界，没有一个是永远的，都会改变的，改变的就是走向消失。因为主所做的不能改变，当我们去永远的国度的时候，我无法继续拿着这个身体，当耶稣再临的时候，我们的身体会变为像耶稣一样的身体，我们会得到一个不老也不会改变的身体，那个时候才能永远。

我们在这地上的时候，在身体里面有我们的心。当然我们身体里面的心能够去见神，能够去思考神，能够在神里面，这样的心与耶稣成为一样的心。当我们相信并接受耶稣话语的时候，我们的心就会变得像耶稣一样。成为一样的心的时候，就像我们心脏里所输送的血会巡回我们整个身体一样，我们的心和耶稣成为一样的心，从那个时候开始由耶稣来做工。只是各位拿着与耶稣的心不一样的心时，就不是与耶稣一样。当各位信耶稣的话语的时候，各位会与耶稣成为一体，那个时候耶稣的能力同样活在我们身上。

二儿子在猪圈里不知道待了一个月、两月、两年还是三年。重要的是，他的心找到了父家，也见到了父亲，看到了口粮有余，也看到了雇工。这二儿子却很害怕，因为他得罪了天，得罪了父，但是他还是决定要回父家，去了之后我要说什么？我得罪了天，得罪了父，我不配称为你的儿子，你就看为一个雇工，你就让我睡觉，吃饱就可以！在这个时候，他能得到回到父家的勇气。如果父亲责备我，我就说：我不是你的儿子了，我不配成为你的儿子。你就当成我是一个雇工，让我吃饱就行。就这样他回了父家。

奇妙的是，你今天开始就是雇工了。如果你今天把田地耕完，我就给你吃饭，我也让你睡觉，如果我让你做的事情都做完，就这样做吧。父亲没有拿着这样的心，父亲看到儿子回来，他抱着他的颈项连连与他亲嘴。儿子说，父亲，我得罪了天，又得罪了你，从今以后我不配成为你的儿子。接着他想说，把我看作一个雇工。但是父亲看见自己特别的高兴，他无法说，因为说这个话简直是侮辱父亲，所以他只是说，父亲，我得罪了天，又得罪了你，从今以后我不配称为你的儿子。他无法继续说下去把我看成一个雇工。这是他不知道父亲的心的时候。他现在知道了父亲原来真的爱他。他父亲说：“把上好的袍子拿过来，把戒指戴在他指头上，把鞋子穿在她脚上，把那肥牛犊牵来宰了！”

我常常会说路加福音15章的话语，讲出两种画面，这世上人生最明亮的一面和最为黑暗的一面。在那黑暗的猪圈里，在猪圈里面它描绘的是最黑暗的一面，又冷又饿，但是明亮的一面就回到父家的时候，父亲说：给他穿上上好的袍子，戴上戒指，宰了肥牛犊，特别高兴。然后村子里的其他大人过来：“你过得好吗？”父亲没有说儿子是怎么过来的，他只是给二儿子穿上了好的衣服，你也经历了很多是吗？是的。真的他们一定过上特别幸福的生活。这个故事是我们需要听的，有很多人虽然得救了，但是不认为我们的神是我们的父亲。这个故事描绘的是神的心，意思是神向着我们也是拿着一样的心。 

各位知道了吗？彼得因为他不认耶稣三次，他认为他不配站在耶稣面前，我不行，我算什么耶稣的门徒，没有资格，回去捕鱼算了，就回到加利利海边。耶稣说：你爱我吗？主啊！你知道我爱你。你心里面有爱我的心，你就喂养我的羊。这个时候彼得发现否认耶稣三次不成为问题，当耶稣钉十字架上的时候，所有罪已经洗净，否认三次的罪也被洗净。各位不是因没有犯罪而明亮的生活，虽然犯了罪，虽然有缺点和软弱，虽然也犯了错，但是父亲的爱使浪子幸福，使他喜乐。我们的心与神的心见面，耶稣的心和我们的心融合在一起，神就开始做工在各位的生活上。

总.统说：“当我去了巴西医院的时候，我走到了阴暗的黑暗幽谷里，但神说，我与你同在，我的杖引领你。同样的医院，同样病房里有上议员，神为了让我做神的事情，而救活了我。”他现在成为了I.Y.F的顾问。我们I.Y.F的顾问有一位是巴拉圭的前总.统，还有一位是贝宁的前总.统。有一个人听了这个话之后，他去确认了这些人真的是I.Y.F的顾问吗？然后正好那个时候总.统来访问了我们这儿，他上次没有时间来，所以说6月份再来，贝宁的总.统也是想在任期之内来访问韩.国。但是他说警卫的费用谁来去付？这简直是天文学一般的数字，我就跟他说，那你任期结束之后再来，然后他任期结束的时候来到韩.国，过了一个星期再回去了。

期间有很多总.统们，神让这些总.统们见到我们，神为什么让我去见总.统？就是为了让我去传福音，我也去传福音了。因为时间短，有的时候我也无法确认他是否确信福音，总之有很多的总.统得救，最为感激的是艾史瓦帝尼的国王陛下，他得救后特别高兴。有一次在合唱团唱歌的时候，他参加了国立学校的毕业典礼，他看了她们的演唱之后吓一大跳，他叫这两位姊妹过来。你们是谁？然后她就说：我们I.Y.F的会长牧师10天后会过来。我到达那儿的时候，国王陛下派了一个部长，让我吓一大跳，就直接我接到国王陛下那里，让我见了国王陛下。他们给了我40分钟的时间，前面说这说那过了10分钟，然后问候，我就开始讲了30分钟的福音，然后到了40分钟就结束了。国王陛下说：“牧师，我们能不能再讲一会儿?”我又讲了30分钟，他说能不能再讲一会儿，我又讲了30分钟，那个时候他得救了。在一个半小时期间，我向国王陛下传了福音，国王陛下跟我说：“您是神真正的仆人，我要赐给你地皮，也希望在这里盖你的房子，盖礼拜堂，盖宣.教中心。”那时候他给了我们的地皮偏郊区，我跟他说，我们的学生没有车，在这里盖礼拜堂，他们就无法来。国王就把属于他的地皮给了我们。就这样，在一个离市中心近的地方，我们开始施工，特别感谢的是那块地特别的好，有很多树木，我们想把它整平之后去盖，国王给了我们45,000平方米。我说这个有点不够，我们也想做公路，他给了我们9万平米，我们现在正在施工。神让我们在很多国家建筑I.Y.F中心，我们在物资方面上也有很多困难，但是这样的时候神也帮助我们，在盖多米尼加I.Y.F中心的时候，神也帮助了我们。赞比亚的I.Y.F中心已经快要竣工。马拉维现在正在盖房顶。最近在埃塞俄比亚政府把处于市中心的地皮给了我们，特别感谢神帮助我们去做这样的事情。

各位都是神的子女，希望不要活得像浪子一样，而是过得像神的子女一样。各位，我们的儿子，孩子小的时候不失误吗？各位也是小的时候都不足，即使那样，希望各位也相信自己是神的儿女。我们都软弱不足，但是在我们心里面迎接耶稣，我们去思念、思考神，常常思考神赐给的应许，然后相信话语，这样神的心和各位的心变为一样的话，那个时候神开始改变一切。

二儿子应该在猪圈里每天咒骂妓女说：坏女人。但在圣经里，那二儿子在猪圈里没有想别的，而是想到是父家，父家的口粮有余。我的父家充满爱，所以他能迈开脚步。因为心过去了，身体也过去，这是非常荣耀的地方。各位，神向着我们说，我们是神的子女，我们需要知道什么是儿女？那是儿子，那是女儿，希望各位能够赞美神。在困难疲累的时候，让心能够脱离环境，希望能够访问父家，希望能够仰望神，那个时候所有的都能够得到解决。 

因为使徒保罗的船被破坏，他见到了神，神跟他说：你会走到凯撒面前。我不会死，那个时候风浪结束。当保罗在腓利比监狱的时候，他特别困难。到了晚上的时候，他想了想，我为什么要痛苦呢？因为有神与我同在，他午夜就开始唱起赞美。突然有地震，然后牢门打开，他就这样从牢房出来，有这样的历史。我们所信的神是全宇宙最厉害的，他是我们的父亲，让我们像个神的儿子一样，神的女儿一样，希望能够荣耀于神，能够赞美神。

希望各位过上这样的生活，不知道多么的感谢，只是希望各位的心不要走在黑暗里，而是各位的心常常与神见面。当各位困难的时候，当各位痛苦的时候，希望常常与神对话。神啊！我很困难，但是神你能拯救我是吧？因为我感觉黑暗时间太长了，希望赶紧结束。

如果各位是神的儿子，也在父亲面前撒娇，各位真的是神的儿子女儿。当各位遇到问题黑暗的话，希望各位仰望神，相信神会改变一切。父亲会把最好的袍子、戒指、鞋子、食物赐给你们，会让各位能够享受着喜乐。特别感谢能够与各位一起准备着活动，林牧师和我一起过来，这次特别感谢，也能和牧师们进行交流。在我们准备活动的时候，特别感谢能够做神的事情，我们是神的人，无论是在任何事情上都有神与我们同在。各位的问题中也有神同在，希望各位不要只是丧气，希望各位能够拥有希望，各位会变得幸福，会荣耀于神。